### ISSUE TITLE
*.g.wxs not created in TeamCity build

### ISSUE THREAD

**Issue by alexeygrant** [oleg-shilo/wixsharp#10]
When building a Wixsharp project in  Visual Studio as a part of the solution, a [ProjectName].g.wxs file is generated in the wix folder in the root of the project and build process completes successfully and .msi files is generated.

However, when I try to build the same project on TeamCity CI server, the *.g.wxs file is not generated and build fails. If I include .g.wxs files to commits, the builds succeeds.

I want to exclude .g.wxs files from from Git commits because if included, the file changes all the time due to its auto-generation nature and I don't want to record/keep all those auto-generated changes.

Is there a way that I can guarantee generating *.g.wxs files in TeamCity?

**Comment by oleg-shilo** [comment]
It's interesting one. 

The key to the problem is understanding why TeamCity prevents WiX source generatione. And another question is why is it a problem.

Wix# compiler will always generate *.g.wxs files if it was invoked with /MSBUILD param. And the out dir is a relative path (./wix) with respect to the CurrentDir.  Both command line param and CurrentDir are set by the MSBuild via WixSharp.targets:  
```
<Exec Command="&quot;$(TargetPath)&quot; &quot;/MSBUILD:$(ProjectName)&quot;" WorkingDirectory="$(ProjectDir)"/>
``` 
If TeamCity does not fully respect MSBuild runtime model and tweaks with the environment (e.g. sets its own CurrDir) the generation of *.g.wxs can be compromised. Thus in your case the files may still be generated but not in the place you expect.  Solution (if this behavior needs to be solved) is to ensure TeamCity executes msbuild target (WixSharp.targets) correctly.

Though I am not sure that *.g.wxs files is a problem. These files are marked in the "no action". Thus their absence does not affect the build outcome at all. 
![image](https://cloud.githubusercontent.com/assets/16729806/22196672/68ca4c46-e1a2-11e6-9049-5ed90347ea73.png)

Thus I am afraid you need to do some TeamCity investigation.

If you hit the wall you can always get rid of WixSharp.targets and do the build an old fashioned way. Have just an ordinary ConsoleApp project, add NuGet WixSharp.bin and add post-build event:
![image](https://cloud.githubusercontent.com/assets/16729806/22196931/b656a0f8-e1a3-11e6-9471-fe5d04a489c6.png)

This is effectively what WixSharp.targets does.

**Comment by dosarf** [comment]
The workaround I just found: make sure your folder wix\ exists under your project (e.g. have it created prior to invoking msbuild) - then the Wix# generated exe will indeed always produce the .g.wxs file, and things work. If the folder wix\ is not there neither it or the .g.wxs file will be created. This way you can mark the .g.wxs to be gitignored.
I am very far from being an expert in VS matters, but this smells like as if the generated exe would not be creating the wix\ folder, merely using it (by putting the .g.wxs file there). And that makes me wonder how the item in the ItemGroup: <None Include="wix\$(ProjectName).g.wxs" /> got to my .csproj file. Is that something that gets added when you include the Wix# NuGet packages somehow, together with the WixSharp.targets? Could the difference be that VS re-creates wix\ folder if missing, and msbuild does not?

**Comment by oleg-shilo** [comment]
Excellent. Thank you for sharing. 

The problem was caused by the Wix#-MSBuild building algorithm not recreating the `wix` folder if it was deleted for whatever reason.

The problem has been fixed in the latest [Release v1.4.0](https://github.com/oleg-shilo/wixsharp/releases/tag/v1.4.0).

A new settings has also been introduced to allow extra MSBuild control. Now you can suppress *.g.wxs generation when required (e.g. TeamCity builds):

```C#
static void Main()
{
    // suppress generation of .\wix\MyProduct.g.wxs
    MsBuild.EmitAutoGenFiles = false;
    ...
```

**Comment by oleg-shilo** [comment]
> And that makes me wonder how the item in the ItemGroup: < None Include="wix$(ProjectName).g.wxs" /> got to my .csproj file. Is that something that gets added when you include the Wix# NuGet packages somehow, together with the WixSharp.targets?

Correct. And now you can control the inclusion with the  it with the `MsBuild.EmitAutoGenFiles` setting:
```C#
static void Main()
{
    // suppress generation of .\wix\MyProduct.g.wxs
    MsBuild.EmitAutoGenFiles = false;
    ...
```

**Comment by alexeygrant** [comment]
Hi Oleg,

Thanks a lot for fixing the issue! 
I can now ignore g.wxs without breaking TeamCity builds, that's a good news.

**Comment by oleg-shilo** [comment]
Not a problem,

It was `dosarf` who identified the cause of the problem. Most likely TeamCity does some sort of directory clearing and removes the `wix` folder.

Keep in mind that `MsBuild.EmitAutoGenFiles` just ste's/gets a process envar `WIXSHARP_SuppressMSBuildAutoGenFiles` and nothing else.
Thus you can remove `MsBuild.EmitAutoGenFiles` from your code and set the envar globally (e.g. on TeamCity build PC):
```
set WIXSHARP_SuppressMSBuildAutoGenFiles=true
```
This in turn will unconditionally suppress the *.g.wxs creation for all Wix# projects on your build PC and yet if the same code is compiled on a dev PCs a *.g.wxs will be generated to assist you with the development.

**Comment by dosarf** [comment]
Thanks Oleg, for fixing the issue promptly.
