### ISSUE TITLE
Add/Remove help

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1007]
Please help me.
I have created bootstrapper project included MSI.
When i install setup it install setup successfully without any issue.
When i open add/remove program  in the control panel. i could see Product name in the organizer column. But publisher column in the add/remove is always empty. How to set publisher column in the wixsharp - boot strapper project model.

i could find any valid property in the bootstrapper class.
Even i set controlpanel propery in the MSI project. But i could not see Name in the publisher column. could you assist me to resolve the issue.

**Comment by RecursiveNerd** [comment]
Sharing your code is going to be the easiest way to understand what you're currently doing vs. what needs to be done in order to get the information you want into the Add/Remove Programs window. To get the publisher column filled out in Windows - you need to set the [Manufacturer](https://github.com/oleg-shilo/wixsharp/blob/d809ad85510a84849ee0ab0a249d375077c64ef5/Source/src/WixSharp/ProductInfo.cs#L54) property. This is part of the ManagedProject's ControlPanelInfo.

A really quick and dirty example:

`var project = new ManagedProject("My Product")
{
    ControlPanelInfo = { Manufacturer = "My Company" }
};`

The text "My Company" should be the text you want to display in the Publisher column.

**Comment by saiprabhur** [comment]
Thanks it worked..
