### ISSUE TITLE
Set file permission to a specific file in Files

### ISSUE THREAD

**Issue by MarcelDec** [oleg-shilo/wixsharp#1011]
Hello,

i need to set specific permission to a file. The file is part of a folder of files gathered with the WixSharp.Files object.

Example code:
```
Files files = new Files(@"C:\Temp\WixSharpTestDirSource\*.*");
Dir testDir = new Dir(@"C:\Temp\", files);
//find "SomeFile2.txt" and set permissions
```

Is this even possible? 

Thank you

**Comment by oleg-shilo** [comment]
Thigh may help:
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Permissions/setup.cs

**Comment by MarcelDec** [comment]
Hi Oleg,

thanks for your replay. But my question is not how to set permission.
I wan´t to know how to add permissions to a file inside a fileCollection.

Thanks

**Comment by oleg-shilo** [comment]
You can add `FilePermission` to every file you need to:

```C#
new File(@"Files\Docs\Manual.txt",
    new FilePermission("Everyone", GenericPermission.Read | GenericPermission.Execute),
```

**Comment by MarcelDec** [comment]
Hi Oleg,

i get that. But look:

My dir looks like this:
```
Files files = new Files(@"C:\Temp\WixSharpTestDirSource\*.*");
Dir testDir = new Dir(@"C:\Temp\", files);
```

Now i need to add permissions to a file that **already** is inside my testDir Object. My code looks like this:
```
Files files = new Files(@"C:\Temp\WixSharpTestDirSource\*.*");
Dir testDir = new Dir(@"C:\Temp\", files);

var fileWithPermission = new File(@"C:\Temp\WixSharpTestDirSource\Manual.txt",
    new FilePermission("Everyone", GenericPermission.Read | GenericPermission.Execute));

testDir.AddFile(fileWithPermission );

```
But then i get an error saying that i do have an duplicate symbol (Manual.txt).

**Comment by oleg-shilo** [comment]
Ah you are using wild cards....
You should start with that :)

When you specify wildcards they are not resolved until build time. 
The duplicated symbol is most likely due to the fact you pick the `Manual.txt` file twice. once with `*.*` and second time when you add it manually.

You can easily check it by analyzing the produced `*.g.wsx` file.

Your solution would be either prevent `*.*` from picking this file by supplying the filter in the constructor (`Files(string sourcePath, Predicate<string> filter)`).

Or you can resolve all files before the build and then find your `Manual.txt` and add the permissions.
Something similar to this:
```C#
project.ResolveWildCards();

project.AllFiles
        .Where(file => file.Name.EndsWith("Manual.txt"))
        .ForEach(file => file.Permissions = new[] { new FilePermission(...}));
```

**Comment by MarcelDec** [comment]
Thank you. That helped me :)
