### ISSUE TITLE
Please include a build guide for the NuGet package

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#1037]
I would like to build this as a package, but my attempts so far have all failed. I would suggest either a build guide or a script to be written.

I would also suggest moving to the simplified SDK Project Format to simplify package creation, if possible. This would enable usage of the dotnet command line tool and allow contributions from non-Windows users without WINE or other work-arounds. This would be a LOT of work, which is why I'm only mentioning it off-hand and didn't make a task for it (yet), but it's something that might be worth pursuing.

**Comment by sonicbhoc** [comment]
I would like to know how to build so I don't have to keep bothering you to package hotfixes, and so I can test my changes faster and easier. Unfortunately, I'm stuck until packages are updated and I want to finish this before work picks up again.

**Comment by oleg-shilo** [comment]
When working on a new project format please be aware that it may not be as beneficial as it seems.
Thus it will not eliminate the need for building packages from nuspec. This is required because the output of the one VS project will end up in multiple packages. And on top of it, the package will need to include `targets` which is difficult to achieve without nuspec.

**Comment by sonicbhoc** [comment]
I know about the differences between the formats. I actually wanted to present a case for changing how certain things are packaged, but I didn't want to suggest anything until I have made sure that everything works first.
