### ISSUE TITLE
MSM project type does not support the Dependency tag

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#1047]
Merge modules support Dependencies as a tag, which allows merge modules to depend on other merge modules, as seen here:
https://wixtoolset.org/documentation/manual/v3/xsd/wix/dependency.html

**Comment by oleg-shilo** [comment]
Sorry, I am not sure the whole MSM is a feature that is still relevant. In many cases, MSM can be considered as an antipattern as it creates tight coupling between deployments of the product and the dependency SW (e.g. OTS). Whilse in some cases it is OK in many others it is a drawback. While WixSharp supports MSM, I am not sure about investing in the advanced features of this MSI technology. Particularly because as a work around `Dependency` can be injec6ted even now.

Don't get me wrong, MSM's `Dependency` element is a valid functionality. Probably as valid as MFC projects support in Visual Studio. 

Anyway, the feature is simple and if someone can put an effort into it I am happy to let it in. Otherwise I have to put it in the low priority list.

Making it the 'enhancement'
