### ISSUE TITLE
Potential problem with ServiceConfig

### ISSUE THREAD

**Issue by marcobeninca71** [oleg-shilo/wixsharp#1062]
Hello Oleg
I took your example (\wixsharp\source\src\WixSharp.Samples\Wix# Samples\WinService\With_WiX\setup.cs) to install a Windows Service but while compiling it I get the following warning from the wix framework

warning CNDL1150: ServiceConfig functionality is documented in the Windows Installer SDK to "not [work] as expected." Consider replacing ServiceConfig with the WixUtilExtension ServiceConfig element.

Could this warning be a potential issue during installation? Is there a way to avoid it?
Is it better to use the other example in \wixsharp\Source\src\WixSharp.Samples\Wix# Samples\WinService\With_InstrallUtil\setup.cs which uses ElevatedManagedAction to do it?
If the latter is the case it's better to remove the With_Wix example to avoid confusion.
Thanks in advance
Marco

**Comment by oleg-shilo** [comment]
Hi Marco,

`ServiceConfig` element support was a difficult one to bring. The initial implementation somewhat worked but then WiX has introduced an enhanced version of this via the Util extension. I was planning to remove the support for the raw `ServiceConfig` but then learned that the `Utils.ServiceConfig` does not fully match the `ServiceConfig` functionality wise. So I had no choice but to keep them both and combine them in a single WixSharp class.

 https://github.com/oleg-shilo/wixsharp/blob/d809ad85510a84849ee0ab0a249d375077c64ef5/Source/src/WixSharp/ServiceInstaller.cs#L357-L382

 As you can see some attributes present in `ServiceConfig` are absent in `Utils.ServiceConfig`.

Thus if you are not setting up the attributes that are from`ServiceConfig`  then WixSharp will emit only `Utils.ServiceConfig` otherwise you will have both elements in the wxs as there is no other way.  

How safe it is? Cannot really say.

**Comment by marcobeninca71** [comment]
Hi Oleg
so in case that I avoid to use ServiceConfig and switch to ServiceConfigUtil I'll avoid the wanring from wix?
But I tried not to set the attributes of ServiceConfig (the ones listed in your code) but then I get the following error:

error CNDL0044: The ServiceConfig element's DelayedAutoStart, FailureActionsWhen, PreShutdownDelay, ServiceSid, or RequiredPrivilege attribute was not found; one of these is required.

Anyway my installer works fine actually so I'll keep the code and the warning for now.

Marco

**Comment by oleg-shilo** [comment]
Marco, you are right. It was one property that triggered the insertion of the `ServiceElement` **always**. Regardless of the relevant attributes being used or not.

It was a mistake. Corrected now.
Thank you for pointing it out.

You can continue use the code as this waning was about only the presence of the `ServiceConfig` element. But since it is not doing anything (you did not set other attributes), you are in no danger.

**Comment by marcobeninca71** [comment]
Oleg, ok I'll keep the code as it is. 
Thanks
