### ISSUE TITLE
[FEAT] Add error if LaunchApplicationFromExitDialog using in common Project

### ISSUE THREAD

**Issue by HavenDV** [oleg-shilo/wixsharp#1075]
Trying to use `LaunchApplicationFromExitDialog` in WixSharp 1.19.0. When building, the following error appears:
```
2>Building MSI
2>Object reference not set to an instance of an object.
```

I forgot that it requires using `ManagedProject`. I think an adequate error message needs to be added if `LaunchApplicationFromExitDialog` applies to Project and not ManagedProject.

**Comment by oleg-shilo** [comment]
An update for point 3

I tested and was able to reproduce the problem. It is caused by the conflict between 
It is actually expected two MSI/WixSharp features: `LaunchApplicationFromExitDialog` is trying to modify native UI but `ManagedUI` is depressing native UI. Thus you need to use either one but not both of them.

Saying that, it is not easy for the user to avoid this mistake so I have added an extra validation so the user is notified about exact error and the way of avoiding it:

![image](https://user-images.githubusercontent.com/16729806/191021328-7b6f66fd-e5b4-4f1f-a323-7e6f29ab448e.png)

**Comment by labmem0zero** [comment]
You may yse such crutch and it works. Why? I don't know. Maybe any other action makes project to be managed.
