### ISSUE TITLE
Upgrade button - how to?

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1086]
Hi Oleg!
I'm having a `Managed - Custom UI` project.
Using `MajorUpgrade ` element
Upgrade works well - thank you!
As it is now, to perform upgrade,
user have to run higher installer to get the upgrade.
I want to implement the same upgrade but with `upgrade ` button. (e.g user run the lower installer and have upgrade button that will perform upgrade)
Do you example of how to do it?
Thank you!!

**Comment by oleg-shilo** [comment]
I suggest you use ManagedUI project created from CustomUI VS template. This way you will have access to the all UI elements (e.g. buttons) and will be able to create any customization.

**Comment by oleg-shilo** [comment]
Hi Rechel,

You closed the issue. Did my suggestion help you?

**Comment by RachelXGanon** [comment]
Hi,
Actually I used `Managed - Custom UI` 
my question wasn't of how to add button to the ui but how to implement that logic that clicking update will perform an upgrade.
Is it possible? from the other [question](https://github.com/oleg-shilo/wixsharp/issues/1098) I asked you seems like wix doesn't support upgrade to the same msi anyway.
btw - I'd like to donate you, how can I?
Thanks for being responsive ..

**Comment by oleg-shilo** [comment]
Yeah, upgrades are tricky. Even MS dos no longer promotes patches. Still supports but does not promote. The same with MSMs.
That's why they have completely dropped the these minor deployment techniques in ClisckOnce.

Anyway, if indeed you want to support project you can click the donate button on the major page:
https://github.com/oleg-shilo/wixsharp
![image](https://user-images.githubusercontent.com/16729806/144746125-727bbf74-7443-40c6-9a6e-c55f01d1ade8.png)

thank you.

**Comment by RachelXGanon** [comment]
Thanks.
