### ISSUE TITLE
How to configure binding redirect for a assembly with CustomActions

### ISSUE THREAD

**Issue by xmarshal** [oleg-shilo/wixsharp#1100]
Can I use AutoGenerateBindingRedirects in .csproj attribute for this? 
Or just add CustomAction.config to assembly and add redirects by hand? (did not works!)
Or I should set CAConfigFile property only? 
CAConfigFile property should be path to CustomAction.config anв this file must have exactly CustomAction.config name?
What if i have more than one assembly with CustomActions?

**Comment by oleg-shilo** [comment]
Sorry, only now got time to respond.

> Can I use AutoGenerateBindingRedirects in .csproj attribute for this?
Not really as it will not be used on the target system so it will not do anything useful for you,

> Or just add CustomAction.config to assembly and add redirects by hand? (did not works!)
>Or I should set CAConfigFile property only?
Probably you can do it but it is deeply in the hands of WiX runtime so not sure if you can **easily** succeed. 
You will need to set `project.CAConfigFile = "<path to your CustomAction.config>";` 

> CAConfigFile property should be path to CustomAction.config anв this file must have exactly CustomAction.config name?
Yes, it does have to have this very name otherwise WiX runtime will not process it.

> What if i have more than one assembly with CustomActions? 
This is more WiX than WixSharp question.
WixSharp attitude is quite different as it actually actively tries to encourage you to not to have any external assembly for custom actions at all. And also to have a minimal set of actions.

Thus you can have a few event handlers:
```C#
project.BeforeInstall += args =>
{
    if (!args.IsUninstalling)
    {
        // do your tasks
    }
};

project.AfterInstall += args =>
{
    if (!args.IsUninstalling)
    {
        // do some other tasks. Even call other assemblies methods
    }
};
```
