### ISSUE TITLE
Can WixSharp be used on MacOs to create an MSI?

### ISSUE THREAD

**Issue by merijndejonge** [oleg-shilo/wixsharp#1110]
Hello,

I want to create an MSI installer such that I can install my software on the Windows platform.
However, my build/dev environment is JetBrains Rider on MacOS. Can I  use WixSharp to create an MSI on MacOs from with Rider, or can I only use WixSharp on a windows platform?

Thanks for your help.

**Comment by oleg-shilo** [comment]
Most likely you cannot. 
The problem is not even WixSharp. It can run on any platform. The problem is the set of compilers WixSharp is using under the hood. They are the set of compiling utilities from WiX toolset (https://wixtoolset.org/)

If you can install MacOS equivalent then you indeed can build your MSI. 
While I am sceptical WiX is portable, would be thrilled if I am wrong.
