### ISSUE TITLE
Question: How to add files to Setup

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1111]
Hallo, i have tech question.  Until now i always add installfiles like dlls, xml file or .config as single line.
Like string file1 = path + "\\test.xml", string file2 = path + "\\mydll.dll" etc. 
Is there any option to add it as List to Msi files by using extension as criteria ? 
In my new project, i have too many of them (round 50 files ). 

Can someone pls help me with ?

**Comment by oleg-shilo** [comment]
Have a look here:
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Release%20Folder/setup.cs
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/WildCard%20Files/setup.cs

**Comment by Torchok19081986** [comment]
Thanks, Oleg. Last question, after this one, close the question. How do i add Exeshortcut, that wasnt created by msi-installer. Exesortcut already exists as file in project ? Any possibility ?

**Comment by oleg-shilo** [comment]
I am not sure you can. The shortcut file embeds the path to the file that is specific to the file system on the target machine. If you have a shortcut file in the project then it means it has the path of the build machine that in many cases will be invalid after the installation.

That's why shortcuts need to be created during the installation, not deployed/copyed.
