### ISSUE TITLE
Update a version without removing missing files in the new version

### ISSUE THREAD

**Issue by Chani6935** [oleg-shilo/wixsharp#1121]
Hey,
I created an MSI file
In version update mode, I do not want files that are missing in the new version to be deleted (like log files, DB, etc.)
How can I do that?
This is my code:
`                ManagedProject project = new ManagedProject(projectName, // Msi file name                                                                         
                    new Dir(installPathFolder, // The path of the folder to which the files will be copied
                      new Files(_rootFolderName + @"\*.*") // The folders or files we want to copy                  
                      ));

                project.Version = new Version(projectVersion);

                project.AllFiles.ForEach<File>((f) => f.OverwriteOnInstall = true);                

                //project.GenerateProductGuids();
                project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
                project.Id = Project.CalculateProductId(project.GUID.Value, project.Version).ToString();

        

                project.ReinstallMode = "amus";

                project.MajorUpgrade = MajorUpgrade.Default;
                project.MajorUpgrade.AllowDowngrades = true;
                project.MajorUpgrade.DowngradeErrorMessage = null;`

**Comment by Chani6935** [comment]
These are files that are created while using the software by the user (for example: the user adds data to his database, the insertion creates a file that contains the new data, file name is dynamically created by the user or depending on the data name)
I have no way of knowing in advance the names of the files I do not want to remove,
I just want all the files that do not exist in the new version installation not to be deleted, or deleted but I will have a way to copy them in real time to the new installation

**Comment by oleg-shilo** [comment]
Ah... they are not the files you deployed. Then I am not sure what is happening in your case. 

The defaul MSI behaviour that it only deleted (on uninstall) the files that were deployed on install. In fact is a common question: "why the folder in program files is not deleted on uninstall" - because your app created the log files there :) 

At the same time, I cannot help it, you would be better off and to follow good deployment practices and not creating the log files in the deployment folder but somewhere in the user profile. Then you would not be facing this problem even if your MSI is not exactly behaving as you expect.
