### ISSUE TITLE
Detection of upgrade

### ISSUE THREAD

**Issue by pikausp** [oleg-shilo/wixsharp#1123]
Hello,

I'm running some issues when detecting whether the installer is updating an existing version. I attempted to use the `Session` passed to the custom action, but properties `IsInstalled`, `IsUpgrading`, `GetProductVersionFromUpgradeCode`, `LookupInstalledVersion` do not work, they all return false/null.  (**Editted** false/true typo)

When I look at the MSI logs it clearly shows it detected the current version

```
FindRelatedProducts: Found application: {F20433EF-8BCB-420A-816C-870D35CEC137}
MSI (c) (84:48) [17:34:39:718]: PROPERTY CHANGE: Adding WIX_UPGRADE_DETECTED property. Its value is '{F20433EF-8BCB-420A-816C-870D35CEC137}'.
MSI (c) (84:48) [17:34:39:718]: PROPERTY CHANGE: Adding MIGRATE property. Its value is '{F20433EF-8BCB-420A-816C-870D35CEC137}'.
```
When I access the `WIX_UPGRADE_DETECTED ` property using `Session.Property(string)` I get the correct value found from logs. 

Also running the following query returns a matching record with expected ProductId and UpgradeId
```
gwmi -Query "SELECT ProductCode,Value FROM Win32_Property WHERE Property='UpgradeCode'" | Sort -Property ProductCode | Format-Table ProductCode,Value
```

Do you have any tips?

**Comment by oleg-shilo** [comment]
> ... IsInstalled, IsUpgrading, GetProductVersionFromUpgradeCode, LookupInstalledVersion do not work, they all return false/true.

Not sure I follow. 
- `IsInstalled` and `IsUpgrading` return boolean as they are supposed to. 
- `GetProductVersionFromUpgradeCode` and `LookupInstalledVersion` return `Version`, not boolean
    Mind you, they will only work correctly before installation/upgrade starts. I.e. in UI sequence:
    ```C#
     project.UIInitialized += (SetupEventArgs e) =>
            {
                if (e.IsInstalling && !e.IsUpgrading)
                {
                    ...
                }
            };
    ``` 
    It is because Major Upgrade in MSI works as "uninstall_existing --> install_new"
    
    Hope it does help

**Comment by pikausp** [comment]
> Not sure I follow.

Sorry for the confusion. What I meant was that the methods with return type `bool` always return `false` and the methods with return type `Version` always return `null`

> Mind you, they will only work correctly before installation/upgrade starts. I.e. in UI sequence

What is the correct way to handle fresh install logic in a custom action then? Currently, I attempted to execute the action after `FindRelatedProducts` completes and using methods defined on the `Session` object.

```
new ManagedAction(CustomActions.ValidateCredentials) {
    Id = "Validate_Credentials",
    When = When.After,
    Step = Step.FindRelatedProducts,
    Return = Return.check,
    Execute = Execute.immediate,
    Impersonate = true,
}
```

As far as your code snippet goes, what type is project? The installer I inherited uses `WixSharp.Project` and it doesn't declare `UIInitialized` event.

We are using WixSharp v1.16.2.

**Comment by oleg-shilo** [comment]
:)
All good. Now I understand your challenge.
I suggest you use `WixSharp.ManagedProject` instead of `WixSharp.Project`. This way you will ensure that we are talking about the same scenarios.

In the `ManagedProject` you can get rid of all messy CustomActions and replace them with a much simpler and intuitive simple event-driven model: https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#event-driven-custom-actions

This is the sample I took the code snippet from: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/SetupEvents/setup.cs

`AfterInstall` is the most frequently used event handler for custom deployment logic. It is fired when setup is completed in all three scenarios: install, modify/repair, uninstall. All the data in the session object is already prepared for you.

If you want to prepare the data manually you can have a look at this sample: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/MajorUpgrade/setup.cs
It is very relevant to your case. 

As for the conditions in `AfterInstall` event handler (from my memory):
```C#

e.IsInstalling // fresh install
e.IsUpgrading // do not use it is is marked as obsolete use `IsUpgradingInstalledVersion` instead
e.IsUpgradingInstalledVersion // obvious :)
. . .
```
there are other quite useful properties of the `SetupEventArgs`:
![image](https://user-images.githubusercontent.com/16729806/154060339-ff557622-056b-4f1e-8aa8-ce0a4ecd9a67.png)

But all of them require `ManagedProject`

**Comment by oleg-shilo** [comment]
> In case it's relevant I'll add that the project allowed multiple installations and as result I had troubles uninstalling all versions...

Yes, I think it is relevant. 
MSI is a stubborn creature. :( 
"Major Upgrade" implies a simple replacement of one version install with another. If the user wants to deviate from it then all other bits and pieces may stop working. 

WixSharp implements defining the canonical "Major Upgrade" scenario. For any customisation of this scenario, you would need to do WiX **custom** detection unless the default detection happens to work.

Just to check you have exhosted all straight ways of achieving the upgrade and it is not some glitch caused by the target environment of a defect in WixSharp, or even misinterpretation of the MSI execution flow, check out MajorUpgrade sample:

![image](https://user-images.githubusercontent.com/16729806/154146194-71dd2aa2-247d-40e1-b651-5a8413c4aa3b.png)

It prints ALL relevant properties of the session at various stages of the installation.

**Comment by pikausp** [comment]
@oleg-shilo thank you for your help. I've successfully migrated to `ManagedProject` using the custom definition of `ManagedUI` etc. There is the last thing I'm not completely sure about.

How can I detect in before/after callbacks for uninstallation during the upgrade that the application will be reinstalled? Because there is custom logic I need to execute for final uninstallation, but not for upgrades.

The properties have the following values 

```
IsInstalling=false,
IsUninstalling=false,
IsUpgradingInstalledVersion=false
```

Secondly, I noticed the `IsUpgradingInstalledVersion` doesn't seem to work in `UIInitialized` (it works in the before/after callbacks) and I use `args.Session.LookupInstalledVersion() != null). Is this the correct approach?

**Comment by oleg-shilo** [comment]
Correct. It is because MSI does not differentiate these two use-cases. Thus you need to create some sort of evidence that a previous version was present before a new one was installed and is now being uninstalled. 

Basically it is a constrain of the MSI technology but not of your deployment solution.

**Comment by pikausp** [comment]
Thank you for all your help
