### ISSUE TITLE
Repair button in Dialogs.MaintenanceType changes IsModifying, has no effect on IsRepairing

### ISSUE THREAD

**Issue by sanikolov** [oleg-shilo/wixsharp#1129]
Consider this snippet
```
project.ManagedUI.ModifyDialogs.Add(Dialogs.MaintenanceType).Add(Dialogs.Progress).Add(Dialogs.Exit);
```

Observation: when you click on Repair in the UI widget that shows "Change, Repair, Remove", the session property IsRepairing is `false`, and IsModifying is `true`.
Expectation: IsRepairing should be `true` and IsModifying `false`.

If you choose Repair from a right click on the MSI in file explorer then IsRepairing is set correctly to `true`.

**Comment by oleg-shilo** [comment]
Not sure I can reproduce it.

This is the modified `CustomUI.Sequence` sample:
![image](https://user-images.githubusercontent.com/16729806/156718627-38af8f86-33fd-4300-9df8-f0b1d98dc0a9.png)

```C#
        //removing entry dialog
        project.ManagedUI.ModifyDialogs.Add(Dialogs.MaintenanceType)
                                       .Add(Dialogs.Progress)
                                       .Add(Dialogs.Exit);
```

And after install when I click Repair button it does repair:
![install](https://user-images.githubusercontent.com/16729806/156718757-3d23522b-a27e-4539-a014-8589e636d11b.gif)

**Comment by sanikolov** [comment]
Click on the MSI to install it again and then click on the Repair button in the Maintenance dialog that will come up.
The way that you click Repair in your example works and I say as much in my description.
![image](https://user-images.githubusercontent.com/19896827/156762599-dc44370c-8a93-4288-b936-b26de611797d.png)

**Comment by oleg-shilo** [comment]
I see. 
There is confusion about what `IsReparing` constitutes.

MSI file can be run in these possible modes `Install`, `Uninstall`, `Modify`, `Repair`.
These modes are indicating how you loaded the msi (in `msiexec`) but not what input you, as a user, made when/if you were prompted. 

When you started your MSI you did it in the maintenance mode. That's why you see the maintenance dialog. 
That's why doesn't matter what you do you are in the `Modify` mode. Simply you cosen the repair action while being in the `IsModifying` state.

Thus if you are trying to pass the information about the button you clicked to the further actions you can check the session for that:


![image](https://user-images.githubusercontent.com/16729806/156855105-0a6f2889-5670-438e-9bd4-14ee5683e86f.png)

**Comment by sanikolov** [comment]
Great, thanks for the clarification. This solves my problem.
