### ISSUE TITLE
Feature w/o files doesn't generated in .wxs file

### ISSUE THREAD

**Issue by lord2kim** [oleg-shilo/wixsharp#113]
Hi.

I have follow situation: create "Driver" feature with 2 sub features ("Driver 1" & "Driver 2") and w/o any files.

```C#
var application = new Feature("Application") { Name = "Application", Description = "Application" };
var drivers = new Feature("Drivers") { Name = "Drivers", Description = "Drivers", AttributesDefinition = $"Display = {FeatureDisplay.expand}" };
var driver1 = new Feature("Driver 1") { Name = "Driver 1", Description = "Driver 1", IsEnabled = false };
var driver2 = new Feature("Driver 2") { Name = "Driver 2", Description = "Driver 2" };

var project = new ManagedProject("Application",
    new Dir(@"C:\Application",

        new Files(application, @"C:\files\Application\*.*"),

        //new File(drivers, @"C:\files\file.txt"),

        new Dir("Drivers",

            new Dir("Driver 2",
                        new Files(driver2, @"C:\files\driver2\*.*")),

            new Dir("Driver 1",
                        new Files(driver1, @"C:\files\drive1\*.*")))

        ),
    );

drivers.Add(driver1);
drivers.Add(driver2);
```

In appropriate with screen 1 we are haven't any files in "Drivers" feature and this feature wasn't generated in .wxs file. Only I uncomment "file.txt" and add it to "Drivers" feature all will ok as on screen 2.

![image](https://user-images.githubusercontent.com/25769643/28869199-02a86976-778d-11e7-9d2f-135724f27940.png)

![image](https://user-images.githubusercontent.com/25769643/28869184-fab079f2-778c-11e7-9206-60e918cdacaa.png)

I think this is bug, because follow WIX block is correct:
```XML
<Feature Id="A" Level="3">
  <Feature Id="A1" Level="10" />
  <Feature Id="A2" Level="10" />
</Feature>
```

**Comment by oleg-shilo** [comment]
Yes it is a problem and unfortunately it doesn't have a good generic solution at the moment. 

The problem is that MSI does not allow associating feature with the file/directory directly and requires a component to be used as a link. Wix# completely eliminates the components as a "relic of the past" by automatically generating them on-fly. Thus from C# code you can associate a feature directly with a file/directory. Though this approach does not cover file-less features. I will mark it as an enhancement and see what can be done.   

As for your very case, it has a quit straight forward solution. You just need to place the `drivers` feature in the parent directory:

```C#
new Dir(drivers, "Drivers",
    new Dir("Driver 2",
        new Files(driver2, @"C:\files\driver2\*.*")),
    new Dir("Driver 1",
        new Files(driver1, @"C:\files\drive1\*.*")))
...
```

**Comment by lord2kim** [comment]
@oleg-shilo, thank you.
Looks like this case is work for me.

**Comment by oleg-shilo** [comment]
And as you probably noticed (from the commits) the problem has been properly fixed and the fix will be available in the next release.

**Comment by lord2kim** [comment]
@oleg-shilo, yes I see. Thank u. Will check it.
