### ISSUE TITLE
Project.ResolveWildCards(ignoreEmptyDirectories: true) removes Start Menu shortcut

### ISSUE THREAD

**Issue by CADbloke** [oleg-shilo/wixsharp#1132]
`project.ResolveWildCards(ignoreEmptyDirectories: true);` seems to remove the start menu EXE shortcut I added in the Project ctor.

I think maybe this code ...

https://github.com/oleg-shilo/wixsharp/blob/e046cc13eaa34778c9b29113c06add22b0c8b625/Source/src/WixSharp/Project.cs#L722

... misses "non-files" like shortcuts maybe?

I used with `project.FindFirstFile(exeFileName).Associations = new FileAssociation[]  {....}` which crashes with a Null Reference error if I don't run `Project.ResolveWildCards()` before it. Running with no parameter (so `false`) works fine. 

that parameter perhaps should have been called `pruneEmptyDirectories` ?

**Comment by oleg-shilo** [comment]
Agree.
Very reasonable suggestion. Will rename in the very next release.

**Comment by CADbloke** [comment]
@oleg-shilo as per the title of the issue, I didn't expect any folder containing shortcuts to be considered empty and pruned. Calling true on the resolve wildcards method deleted the start menu shortcuts.

**Comment by oleg-shilo** [comment]
The folders you are digging through do not **really contain** any shortcuts. 
You can use wildcards to automate the generation of the deployment specification (`WixProject` instance) by analysing the build machine structure of a specified folder.  Thus now I am not even sure I did the right thing by renaming the arg in 'prune' because it made you believe even stronger that you are iterating through the "installed" files/folders while you are not.

You have a choice either add files/folders/shortcuts manually or automate adding files/folders with wildcards add you still need to add shortcuts manually. There is no other way.

The only middle ground is if you define complete visitor delegates that you pass to the wild card definition but only you can tell if the effort worth the benefit.

**Comment by CADbloke** [comment]
Hi Oleg

Sorry for my tardy reply. [insert the usual excuses here]

This is the code that I'm using ...

````c#
ManagedProject project = new ManagedProject("CableScheduler",
     new Dir(@"%ProgramFiles%\CADbloke\CableScheduler",
     new Files($"{exeDir}\\*.*", f => f.StartsWith(exeFileNameNoExt) || !f.EndsWith(".xml"))),
     
     new Dir(@"%ProgramMenu%\CADbloke\CableScheduler",
             new ExeFileShortcut("Cable Scheduler", $"[INSTALLDIR]{exeFileName}", ""))
     );
````

I didn't expect `project.ResolveWildCards(true)` to remove the start menu shortcut.

**Comment by oleg-shilo** [comment]
Thank you. With the sample, I was able to reproduce it.
 Fixed.
 Will be available in the very next release.

**Comment by CADbloke** [comment]
Thanks @oleg-shilo 
Love your work!
Sorry about my tardiness.

**Comment by oleg-shilo** [comment]
Don't stress. All good. :)
Glad we managed to sort it out
