### ISSUE TITLE
How to add image to setup file?

### ISSUE THREAD

**Issue by saklanmaz** [oleg-shilo/wixsharp#1135]
Hello,

I want to place some images while customizing the setup file. I created a folder named Images in the WixSharp setup project. I added my pictures in this folder. I changed the Build action of the images to "Embedded Source". I cannot view the images even though I have implemented the following in the WelcomeDialog. What is the missing point?

` <Image Source="/Images/Logo.png"/>`

**Comment by Torchok19081986** [comment]
morning, Msi and ManagedUI or Bootstrapper Intall ?
if you use ManagedUI, can completly customize standarddialogs. Just set Pictures in Dialog. Its nothing else winform project.

**Comment by saklanmaz** [comment]
Thank you, I using ManagedSetup - Custom WPF UI. I add the image as I do in standard wpf applications. In the xaml field, the image appears when the project is not compiled. When I set it up, I cannot view the picture in the setup. Could the problem be something else?

**Comment by oleg-shilo** [comment]
If you create the project from the WPF templete you can investigate how images are loaded there

The best way is to load them in the pound property of `Source`. The reason for this is that most likely your source URI path only works for a static Window WPF application,. But since you are loading the UI assembly dynamically you will need to provide a complete URI with the assembly name. It is a standard WPF technique
