### ISSUE TITLE
Change license file path according to the user's language choice

### ISSUE THREAD

**Issue by RicardoKCavati** [oleg-shilo/wixsharp#1161]
Hello, how are you?

I needed to build a msi for my application, and I found out about WixSharp and simply loved it!

One of the things I needed was to give the user the possibility to change the language of the installer, I used your Managed Setup sample, MuiltiLanguageUI and it worked perfectly.

But besides the installer itself, I would like to change the license file according to the user's choice, I have the .rtf files, and when I set one of their paths to be in the `LicenceFile` property, it works as expected, but I would like to change the value of this property if the user chooses another language.

I've been trying to do it and couldn't find a way, I've tried to call the WinForm and then get the result to change it, and also tried to change the property inside the `UIInitialized` event, but it also didn't work.

I would like to know if it is actually possible, and if so, how it should be done or if there is already an example I couldn't find.

Thank you kindly!

**Comment by oleg-shilo** [comment]
Hi Ricardo,

Because you want to do it dynamically (at install time) it is not directly supported by the MSI architecture.
But you can achieve it very easily with the WixSharp code-behind approach.

You will need to build your custom UI for that. 
Create your project from WPF or WinForm "Custom UI" VS project template. It will ensure that all your dialogs source code is in your codebase. 

Now, in the `LicenceDialog` initialization routine, you can set your licence text box to the content based on the user-selected language. This means that you will need to store (and retrieve at runtime) multiple licence files either:
- your project assembly resources
- or in your MSI by adding `Binary` to your project
```C#
var project =
    new Project("MyProduct",
        ...
        new Binary(new Id("en_licence"), @"licences\en.rtf"),
        new Binary(new Id("ge_licence"), @"licences\ge.rtf"),
. . .

byte[] licence_rtf  = session.TryReadBinary("ge_licence");
  ```

**Comment by RicardoKCavati** [comment]
Hello, Oleg,

Thank you for answering so fast!

I've just finished and it is working really well.

I have decided to add only the `LicenceDialog` form to my project, instead of using the whole template, then I added the .rtf files as binaries.

When the user chooses the desired language, I add a key called "license" with a number 0 or 1 to the UIText property according to the chosen language.

On the `LicenceDialog` Load, I check the value of the "license" key, convert it to an int and then cast to the Enum type (just like in the MuiltiLanguageUI sample), and with a switch I load the binary with the right language.

Thank you so much for your help, I hope everyone who needs to build a .msi finds WixSharp because it is simply great!

**Comment by oleg-shilo** [comment]
I am glad you like WixSharp.

What you have described as your struggle and your solution is exactly the scenario and the goal that I had in mind when created WixSharp.

I wanted developers to be free from the necessity to comply with the ridiculously restricted and convoluted "development story" of MSI. Thus you can rely on your normal programming experiences but not some obscure knowledge and exotic techniques.
