### ISSUE TITLE
RegFileImporter does not support hex(b): REG_QWORD

### ISSUE THREAD

**Issue by grayfox99** [oleg-shilo/wixsharp#1171]
Hi Oleg,

First of all, I would like to thank you for making such a great product. I hope you are doing well.

I have been trying to import a .REG file to my Installer to embed a license for one of our APIs. However, everytime I try building the Installer, it throws the following exception:

`Unhandled Exception: System.Exception: Cannot deserialize RegFile value: 'hex(b):00,00,00,00,00,00,00,00'
     at WixSharp.RegFileImporter.Deserialize(String text, Encoding encoding)
     at WixSharp.RegFileImporter.ImportFrom(String regFile)
     at WixSharp.CommonTasks.Tasks.ImportRegFile(Project project, String regFile)`

Upon taking a closer look at the RegFileImporter code, it looks like the error is being thrown because the case for parsing a hex(b) does not exist (among some other hex codes). I am not sure if this is an oversight or on purpose due to some limitation. If it is on purpose, do you have an alternative suggestion?

**Comment by oleg-shilo** [comment]
That is an interesting issue. 
WixSharp does not implement handling QWORD simply because WiX does not support it. As you can see there is no Type value that is mapped to the 64-bit integer: https://wixtoolset.org/documentation/manual/v3/xsd/wix/registryvalue.html

I found that this WiX problem was reported in 2013: https://github.com/wixtoolset/issues/issues/3994. It was closed as "implemented" and yet the current documentation does not say how to use it.

I have updated to WixSharp engine ([05633cc](https://github.com/oleg-shilo/wixsharp/commit/05633cc68c5fc6165c4986a109aac2b0a83f3a57)) to handle the value internally so you can start using it right away as WiX implement support for QWORD.

Sadly, I see no way to have any workaround. Unless you manage to find some magic trick on WiX forums. Then we can definitely integrate it with WixSharp :(

**Comment by oleg-shilo** [comment]
WiX4 still does not support it internally.
