### ISSUE TITLE
Question: Install Condition when bundle with dotnet 6

### ISSUE THREAD

**Issue by Mikkelcv** [oleg-shilo/wixsharp#1175]
Hi,

I have an application that require ".NET Desktop Runtime 6" and is trying to bundle the installation with that. The bundle is working but the condition for when to install it is a bit difficult.

The official way to determine if it is installed as I understand from microsoft documenation is to run the command: "dotnet --list-runtimes" (ref: https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows)

Is it possible to setup a WixFragment for that?

Example:

```
var msiPath = Compiler.BuildMsi(project);
var bundle = new Bundle(PRODUCT_NAME,
                new ExePackage
                {
                    Name = ".NET Desktop Runtime 6",
                    SourceFile = @".\Dotnet6\windowsdesktop-runtime-6.0.5-win-x64.exe",
                    DownloadUrl = "https://download.visualstudio.microsoft.com/download/pr/5681bdf9-0a48-45ac-b7bf-21b7b61657aa/bbdc43bc7bf0d15b97c1a98ae2e82ec0/windowsdesktop-runtime-6.0.5-win-x64.exe",
                    Compressed = false,
                    Vital = true,
                    Permanent = true,
                    InstallCondition = "1 = 1", // this needs to be updated, to the output of the WixFragment
                    InstallCommand = "/install /passive /norestart"
                },
                new MsiPackage(msiPath) { Compressed = true, Vital = true })
            {
                UpgradeCode = UPGRADE_CODE,
                Version = version,
                OutDir = workingDirectory
            };
            
bundle.Include(WixExtension.Util);
            
bundle.AddWixFragment("Wix/Bundle",
            // Here instead of registry search then I need to call the dotnet command instead, possible?
            new UtilRegistrySearch
            {
                Value = "Version",
                Root = RegistryHive.LocalMachine,
                Key = @"SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedhost",
                Variable = "DOTNET_RUNTIMEVERSION"
            });
            
Compiler.Build(bundle, $"{PRODUCT_NAME}.exe");
```

Should I try to write my own class that implements: IXmlAware for this or is there some support for it?
Any suggestions here?

Thanks
Mikkel

**Comment by Torchok19081986** [comment]
morning, i found https://wixtoolset.org/development/wips/6264-add-dotnet-runtime-compatibility-check/ link on wixtoolset. Maybe you need to change your .wxs file in WixSource_Generated Event. Try it. Same procedure works on Net 5 and core for 3.1

**Comment by oleg-shilo** [comment]
@Torchok19081986, your proposal will only work for MSI. It will not though if Mikkel indeed wants to do the check it the bundle.  

Mikkel, you will not be able to call dotnet command from the Bundle as it completely lacks support for custom actions like MSI does.

An excellent read on the topic: https://stackoverflow.com/questions/13018511/how-to-use-customaction-in-wix-bundle

The simples workaround is to build your own BA this way you execute your "dotnet command" directly from BA and then in `OnDetectPackageComplete` event handler you decide how you want to proceed. Though in this case you will need to do the effort of defining the custom UI.

---

It is a rather disappointing WiX architecture limitation that is not easy to overcome. Your post has triggered my another attempt to implement the WixSharp own _bundle custom action_ mechanism. 

I thought that the subclassing the default bootstrapper app with user-defined custom action would be the most elegant approach and was even prepared to go with the Reflection magic and reverse engineering for it since WiX does not expose the default bootstrapper app class to the developer. To my surprise, I could not find it in any WiX SDK assemblies. So I have to assume that the default bootstrapper app managed implementation does not exists and bootstrapper simply builds it at runtime. Maybe even as a native unmanaged UI.

**Comment by Mikkelcv** [comment]
Thank you for the suggestions,

I did start with a CustomAction in the MSI and found that easy that way to determine if dotnet is installed. I might be able to do things manually from the custom action, but would rather bundle the instalation correct.

After looking at it I think I am going with the solution of compiling the application as "self contained", it makes the msi much larger but gets the job done for now.

/Mikkel
