### ISSUE TITLE
WelcomeDialog doesn't show title.

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#1178]
Wix Toolset v3.11.2.4516 installed. WixSharp 1.20.1.0 installed. WixSharp templates for Visual Studio 2019 Community installed. :-)
Steps for reproduce:
1. Start Visual Studio,
2. Choose the "WixSharp Managed Setup - Custom UI" template,
3. Open the WelcomeDialog.xaml file,
4. In line numbered as 10 change the DialogTitle. From "[ProductName] Setup" to "Instalator [ProductName]",
5. Build the solution.
6. Run the MSI.
and the first dialog showed on screen (and it is WelcomeDialog) haven't title. 
One is interesting. After clicking the "Next" button the next dialog will be shown. And now we can click "Back". And the WelcomeDialoe is shown again. Now with title. MSI attached.
[MyProduct.zip](https://github.com/oleg-shilo/wixsharp/files/8899468/MyProduct.zip)
.

**Comment by oleg-shilo** [comment]
The problem is not related to your change of title (it can be reproduced without your change) but a UI localization defect that is triggered by the localization being done later the top level window is created and the title is set.

I am fixing the problem but for now please use this work around:
```C#
    public partial class WelcomeDialog : WpfDialog, IWpfDialog
    {
        public WelcomeDialog()
        {
            InitializeComponent();
        }

        public void Init()
        {
            ManagedFormHost.Parent.Text = ManagedFormHost.Text; // this is the work around
            ViewModelBinder.Bind(new WelcomeDialogModel { Host = ManagedFormHost }, this, null);
        }
    }
```

**Comment by sadam2** [comment]
Oleg, you are amazing. Thanks a lot.

An problem with BackgroundWorker?

**Comment by oleg-shilo** [comment]
No. The title of the shell is set on the creation of the step dialog/panel and it is set to the value of the panel title. But the correct and localized title becomes available only from the OnLoad event of the panel. Thus with the current implementation of the dialog/panel scheduler, the title is always one step behind. It is caused by the need to introduce an extra WinForm control (`ManagedFormHost`) to host WPF panel. The fix is simple - to update the shell form title in the OnLoad event ([789b81e](https://github.com/oleg-shilo/wixsharp/commit/789b81e33bd385297fc88cd59b0ae73024c23219)).
