### ISSUE TITLE
Microsoft Smart App Control

### ISSUE THREAD

**Issue by shragoe** [oleg-shilo/wixsharp#1184]
Hello,
I'm facing issues when Microsoft Smart App Control (new features) is enabled in Windows 11 build 22621.
MSFT blocking tmp files of MSI package that I'm using to install signed by MSFT components.
Any suggestion we'll be appreciated.

**Comment by shragoe** [comment]
I appreciate your timely feedback, Oleg.

MSI signed as well (according to MSFT).

I'm getting toast (notification) from OS that *.tmp files were blocked by Smart App Control(SAC) while running my MSI.
Interesting if only my package is failing on Windows OS with Smart App Control enabled. Maybe Win11 SAC will block any app that uses the core functionality of WiX.

**Comment by raksanyi** [comment]
We're having the same problem. We changed to use `project.BuildMsiCmd("...");` to build just the cmd. Before calling the cmd file, we sign every file that is generated by Wix. Smart App Control still blocks the app from installing.

@oleg-shilo Do you know any workarounds to this besides getting the exemption somehow?

**Comment by raksanyi** [comment]
Actually the file that is being blocked is the %this%.CA.dll, which is being packed into the .msi and gets a different name (as I was testing it it seems it is being renamed to the first custom action it finds + "_File"). We tried signing that file manually and then reassembling the .msi - that didn't work.
Do you think this would work?

- Put all custom actions into an external .dll
- Sign the dll
- Add the signed dll as a binary to the project and register the custom actions

**Comment by oleg-shilo** [comment]
Yes, it does make sense to try. In fact, it might be the key to the problem.
Just FYI, `%this%.CA.dll` is a renamed file of the WixSharp project executable ("msi builder"). It needs to be duplicated and renamed otherwise, WiX tools cannot embed it as it is locked (being executed) during the msi build.

> We tried signing that file manually and then reassembling the .msi - that didn't work.
 This is not a good sign. But it is possible that some of the WiX tools are upset about renaming assembly files. Even CLR does not particularly "like" it even though there is nothing wrong with the technique.
 
 But a simple test as you described would fully answer the question if the workaround is possible.
 You can take a ready-to-go sample for that:
 
![image](https://user-images.githubusercontent.com/16729806/179400963-d69c37b1-f8bf-4d1b-9ac7-a667c775889c.png)
