### ISSUE TITLE
Add Support for Custom Style Window TitleBar

### ISSUE THREAD

**Issue by nickdollahz** [oleg-shilo/wixsharp#1196]
Is it possible to add support for Custom Style Window TitleBar? 

Particularly I would love to see MetroWindow from [MahApps](https://github.com/MahApps/MahApps.Metro) for Wpf.

Things like changing the color and being able to add buttons to the title bar would be beneficial. 
From what I can tell the WPF area is hosted inside of a WinForms Control.
Is this a msi limitation? It doesn't look something I can change without building my own WixSharp. 

Instead we would need to be able to define a WPF Window which MetroWindow inherits from. 

Maybe some other way to do it?

**Comment by Torchok19081986** [comment]
morning, mahapps is pure Wpf and NET Framework C#.  customUI WPF Template is nice to have, but i think you cant change it., cause it wpfhoseted inside winforms. 
Good point to start, download lates wixsharp samples. Here seach for externalUI folder and here after open it, folder WPF Installer CustomU project. Rebuild. 
I was able to add mahapps metro as Window Style . After that you have to control your installer process.

**Comment by oleg-shilo** [comment]
Yes, it is a limitation of the default support for WPF custom UI.
You guys are both right. The custom UI is implemented as WinForm host that has only one child control WpfHostControl. It allows a seamless switch between WPF and WinForm hosting. Thus the only visible part of the top-level window is the titlebar. And that window is a WinForm window. 

It usually is absolutely OK as the styling and customization are in the client area only. Though in your case, since you are specifically interested in the title bar, I recommend implementing your own CustomUI instead of using WixSharp stock UI.

The sample you are looking for is this one:
![image](https://user-images.githubusercontent.com/16729806/183246051-d450fae0-4c0f-4a23-b5bb-038a003fcff2.png)

**Comment by nickdollahz** [comment]
I ended up doing like you said. Looking at that example and changing it until it worked the way I wanted it to.
