### ISSUE TITLE
ExitDialog not showing ProductName correctly

### ISSUE THREAD

**Issue by Arthur-Neto** [oleg-shilo/wixsharp#1198]
Hi, I'm trying to use a language selector before the UI is initialized, it's working alright for the rest of the dialogs but I have a issue with the ExitDialog, for some reason it's losing the ProductName from the context, I have a working example: https://github.com/Arthur-Neto/wixsharp-issue

Strangely it's localizing the strings on it, only the ProductName that it's not showing correctly.

**Comment by oleg-shilo** [comment]
Hi Arthur, I initially thought that the problem is caused, somehow, by the localization. 
Though when I modified your code by removing BR support, to my surprise the problems stayed.
I even put the test code in the ExitDialog initialization and found that the `this.Localize();` does not longer work and cannot resolve `[ProductName]` in the actual name.

This makes me think that somewhere in your code the session resources mapping is getting corrupted. 
Just to assist you with further investigation I have attached the project that maintains resource mapping all the way.

[wixsharp-issue.zip](https://github.com/oleg-shilo/wixsharp/files/9452580/wixsharp-issue.zip)
