### ISSUE TITLE
Nsisbootstrapper silent and multiple msi

### ISSUE THREAD

**Issue by Ishtiy** [oleg-shilo/wixsharp#1205]
Hi Oleg,
How to make the NSIS bootsrapper silent? I see the writer line being added but the created exe doesn't work in silent mode.

Secondly, what's the best way to add multiple msi/exe to nsisbootstrapper. I'm creating an silent bundle for multiple setup files. Move to nsis after several failed attempts with WIX.

As always, thank you so much for lib and help.

**Comment by tgeghamyan** [comment]
Hi @Ishtiy ,
NSIS boostrapper acts as a simple wrapper and has no UI of its own. Whatever you pass in the command line is going to be passed to the "primary" package see [example](https://github.com/oleg-shilo/wixsharp/blob/69bf82e496b715b34f64dd19ecf7d875776e63d7/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L184).
By passing "/qn" parameter to the exe bootstrapper, which in turn is passed to the underlying msi, you can make the setup silent.. See [here](https://github.com/oleg-shilo/wixsharp/blob/69bf82e496b715b34f64dd19ecf7d875776e63d7/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L162)
The options can be embedded in boostrapper during the compile time as well, by specifying them in the "Arguments" parameter.. [See](https://github.com/oleg-shilo/wixsharp/blob/69bf82e496b715b34f64dd19ecf7d875776e63d7/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L189) . In your case it can be:
`Arguments = @"/qn":`

NSIS bootstrapper is intended to be a simple installer of an additional dependency, such as .Net Framework, and it does not replace Burn Chainer mechanism. 
Embedding multiple [payloads](https://github.com/oleg-shilo/wixsharp/blob/69bf82e496b715b34f64dd19ecf7d875776e63d7/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L177) can be used as a workaround 
exe files, and then write the primary application that includes logic to install them one by one, but this is basically duplicating the standard Wix Bootstrapper logic.

You may also consider using the standard bootrapper [application](https://github.com/oleg-shilo/wixsharp/blob/789b81e33bd385297fc88cd59b0ae73024c23219/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/WixBootstrapper/setup.cs#L35
) in order to facilitate chaining, rollback, and other mechanisms, and build the NSIS bootstrapper over it to make it silent by default.
`Arguments = @"-silent":`

See [here](https://stackoverflow.com/questions/44332496/comprehensive-list-of-command-line-flags-options-for-burn-bootstrapper-in-wix) for comprehensive list of all standard switches.

**Comment by Ishtiy** [comment]
Thank you so much, built a solution around this idea.
I was thinking with NSISBootstrapper I could build a complete NSIS script with execwait statements.

Much appreciated.

**Comment by Ishtiy** [comment]
Thank you once again.

**Comment by geghamyan** [comment]
Glad to hear you were able to built a solution. Which approach have you implemented? Payloads or standardboostrapper ?

**Comment by Ishtiy** [comment]
Actually both, thinking of modifying to use NSIS payload (prerequisite) and BootStrapper bundle. Silent and unattended is the main feature. 

Earlier I have a developed a custom interface, where my tech team would add the required msi/exe files and create a bundle - using Oleg's super simple Bootstrapper.

But, the SilentBootStrapper is failing, couldn't figure out how to pass custom BootStarpperCore.Config. Even I tried NoUI sample as is and it is failing, I posted an issue, guess work in progress.

1. So now, my idea is add the dependency application setup files(installshield), as payload (there many cabs).

2. Using my old interface create the bundle for other msis.

3. Use Nsis bootstrapper to combine the 1 and 2 as prereq and primary file. 

I'm an hobbyist developer, just putting on my developer hat to help my team. Was not able to understand "Solution/Issue: Custom Logic for SilentBootstrapperApplication #475" 
https://github.com/oleg-shilo/wixsharp/issues/475

Hence all this re-work and remodel.

**Comment by tgeghamyan** [comment]
A word of caution about Wix Burn Boostrappers - it is not a fire-and-forget bootrapper: it gets registered in the windows registry and should be explicitly uninstalled. Upgrades and downgrades should be considered as well. As far as I remember it tracks MSI versions as well, so be careful if you upgrade individual MSIs without upgrading the whole bundle.
My advice would be - you should use it if all MSI and EXE files you install constitute one whole product and the modifications you make will be at the Bundle level, not at the individual MSI level.
Back then, I tried but couldn't make "WixBootstrapper_NoUI" work reliably. There were a lot of nuances and edge cases, which would take an enormous amount of time to fix and stabilize.

**Comment by Ishtiy** [comment]
Thank you, that's a very good advice. Yes, 2 or 3 apps are ours rest all
from our dev community and each bundle will be unique for a certain
scenario/customer.

We already have a guy who prepares NSIS scripts for these bundles but he is
overloaded with custom requests, that's where I thought I would chip in.

Maybe I will explore to create a GUI for creating our own NSIS scripts,
where we unzip all files to a folder and run each exe/msi with ExecWait.

Thanks any further suggestions are welcome.
I looked at Choco but no bundle/exe option, it creates nupkg, getting C4B
will be a challenge.

Regards,

Ishtiy

**Comment by tgeghamyan** [comment]
1) If you enable "[PreserveTempFiles](https://github.com/oleg-shilo/wixsharp/blob/69bf82e496b715b34f64dd19ecf7d875776e63d7/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L29)", temporary NSIS files will not be deleted, so you can use them as initial templates. 

2) As I mentioned earlier, you don't even need to bother with NSIS files (ExecWait etc) if you write a tiny C# application that enumerates and installs MSI files in the current folder and use this app as your primary application for the NSIS boostrapper. As an alternative to file enumeration the app can have a config file, which can be a part of the payload as well along with MSI and EXE files.

**Comment by Ishtiy** [comment]
Thanks a lot, yes i will go this route.
