### ISSUE TITLE
Trouble using ManagedAction in ManagedProject

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#121]
I have a ManagedProject which i am trying to add a ManagedAction. 

```C#

var wixObjects = GetInstallables();
            
var project = new ManagedProject(Configuration.PROJECT_NAME, wixObjects)
{
    GUID = Configuration.InstallerGuid,
    ManagedUI = new ManagedUI(),
    Description = Configuration.INSTALLER_DESCRIPTION,
    OutFileName = Configuration.INSTALLER_NAME + " V" + Configuration.InstallerVersion,
    Version = Configuration.InstallerVersion,
    MajorUpgradeStrategy = new MajorUpgradeStrategy
    {
         UpgradeVersions = VersionRange.OlderThanThis,
         PreventDowngradingVersions = VersionRange.NewerThanThis,
         NewerProductInstalledErrorMessage = "A Newer version is already installed"
     },
};

project.AddProperty(new Property { Name = "INSTANCE_NAME", Value = "Default" });
project.Actions = new Action[]{ new ManagedAction(GetInstance) };
Compiler.BuildMsi(project);

...

[CustomAction]
private static ActionResult GetInstance(Session session)
{
    Instance = (string)session.Database.ExecuteScalar("SELECT `Value` FROM `Property` WHERE `Property` = 'INSTANCE_NAME'");
            
    return ActionResult.Success;
 }
```

I am however getting the following error and can not understand why:
**'Cannot package ManagedCA assembly(%this%)'**
 
I also tried doing this in the same way as the "Multiple Instances Install" example with my ManagedProject but still get the same error. Am i missing something?

**Comment by oleg-shilo** [comment]
In your code there are so many points to reflect on that I will need to do it one by one. 

_As a general comment, please follow the code samples as close as possible. The are designed in a way to help devs to avoid common mistakes that MSI/WiX makes so easy to make but hard to fix. That is the reason why samples makes ~90% of Wix# codebase._

- When having problems with building, analyze WiX compiler output carefully. Very often Wix# injects extra info in the limited WiX output to assist with troubleshooting (like in your case): 
    ![image](https://user-images.githubusercontent.com/16729806/29148586-c24d3066-7db1-11e7-92a9-e2ddb2959f3a.png)

- The custom action you implemented needs some rework:
    ```C#
    [CustomAction]
    private static ActionResult GetInstance(Session session)
    {
        Instance = (string)session.Database.ExecuteScalar("SELECT `Value` FROM `Property` WHERE `Property` = 'INSTANCE_NAME'");
        ...
   ``` 
    - You don't need to do SQL against MSI db. Access properties directly via the session object: `session.Property("INSTANCE_NAME")`
    - CA Implementation must be public.
    - `Instance` is a type member. You should use only local variables. Any other CA that will try to use presumably initialized `Instance` will fail as that very type member `Instance` will not be initialized any more.  This is an unfortunate ugly nature of MSI - every CA is executed in an individual process.
    - If you want to use CA it's probably better to declare it with an explicit scheduling (unless you are happy with the default one):
    ```C#
    new ManagedAction(CustomActions.GetInstance, Return.check, When.Before, Step.LaunchConditions, Condition.NOT_Installed)
    ```
- You are using `ManagedProject` then why don't you utilize the benefits of this type of project and use more intuitive event instead of the old fashioned CA:
```C#
project.UILoaded += project_UIInit;
project.Load += project_Load;
project.BeforeInstall += project_BeforeInstall;
project.AfterInstall += project_AfterInstall;
```

**Comment by johnferry0** [comment]
Thanks for the feedback. I have found your code samples and answers very helpful.
