### ISSUE TITLE
Does wixsharp.bin and wixsharp supports .net6 framework?

### ISSUE THREAD

**Issue by Pinapala39** [oleg-shilo/wixsharp#1215]
I am migrating my project from .net 48 to .net 6 framework.
While creating the msi package from the program.cs file facing this following issue.Also would like to check if wixsharp and wixsharp.bin supports .net 6 framework.

FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

I have modified the respective version to the Version=2.0.3500.0 but still facing the same issue.

So would like ot check if wixsharp.bin and wixsharp supports .net6 framework

**Comment by oleg-shilo** [comment]
WixSharp is compiled for the target runtime that MSI/WiX supports so the project compiled assembly can be hosted at runtime (during msi installation).

Since MSI cannot host .NET Core assemblies (e.g. .NET 6), WixSharp project assembly needs to be compiled against MSI-supported runtime .NET Framework.

**Comment by Pinapala39** [comment]
Thank you.
