### ISSUE TITLE
MajorUpgradeStrategy Behavior

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#122]
I have the following code:

```cs
var project = new ManagedProject(Configuration.PROJECT_NAME, wixObjects)
{
    GUID = Configuration.InstallerGuid,
    ManagedUI = new ManagedUI(),
    Description = Configuration.INSTALLER_DESCRIPTION,
    OutFileName = Configuration.INSTALLER_NAME + " V" + Configuration.InstallerVersion,
    Version = new Version(2,0,001),
    MajorUpgradeStrategy = MajorUpgradeStrategy.Default
};
```

When i deliberately try to run an MSI with an older Version than a current installation, the installer navigates through the Install Dialogs and then fails on the ExitDialog with no mention of it being due to the Version. It does not seem to prompt the user that a newer version is installed already. 

I expected it to prompt the user that a newer version is installed when the Installer begins.

**Comment by oleg-shilo** [comment]
> I expected it to prompt the user that a newer version is installed when the Installer begins.

Wix# does not do anything for the Upgrade use-case. It completely relies on whatever WiX implements for it. Thus it's is really a WiX question/problem. Unless, of course, if Wix# generates upgrade-related WiX code incorrectly. But this is exactly what you will determine if you start looking into this problem.  Thus I advice to have a look at the wxs code and verify that it has all required elements.

----

You may want to consider using `MajorUpgrade` member instead. It may (or may not) fix your problem but at least it's much simpler and it is the currently recommended (by WiX) technique. Wix# reflects it in the code documentation:

![image](https://user-images.githubusercontent.com/16729806/29149030-be345330-7db4-11e7-9a1e-6d1960c87b4e.png)

**Comment by johnferry0** [comment]
Thanks for the help. Your knowledge is greatly appreciated.

**Comment by jimfoye** [comment]
This is interesting, I'm seeing the same behavior, and I've tried with both approaches. I would swear this used to work. I'm running latest for both Wix and Wix#.

**Comment by oleg-shilo** [comment]
I've just tested and the latest Wix# with WiX v3.11.0.1701. It definitely works correctly. 

Please verify that the canonical sample works i your environment. 
- Build the MajorUpgrade sample and install it.  With the version as it is:
    ```c#
    project.Version = new Version("1.0.709.10040");
    ``` 
- Change the version:
    ```C#
    project.Version = new Version("1.1.709.10040");
    ``` 
- Build and install

Observe change in the Control Panel:

_First install:_
![image](https://user-images.githubusercontent.com/16729806/29258059-f85dd0c0-80f9-11e7-8140-88026c692a60.png)

_Second install:_
![image](https://user-images.githubusercontent.com/16729806/29258050-ebb3f26e-80f9-11e7-8c5e-267ad92facaf.png)

**Comment by jimfoye** [comment]
Yes, this works, going from an earlier version to a later version. The problem is when you go the other way. At least, that's what I started seeing, and if I'm reading what the original poster said correctly, that's what he was pointing out.

I tried this again today, installing first 2.0.0.0, then installing 1.36.0.0. I expect the installer to stop and show the user the DowngradeErrorMessage (if I'm using MajorUpgrade, which  I am - I'm not sure what  the message is expected to be if I'm using MajorUpgradeStrategy). But instead the installer runs all the way through, though when it's finished, the newer version is still in place (so, it seems like this whole problem is an annoyance more than anything else).

Here's my code:

```
project.MajorUpgrade <- MajorUpgrade(Schedule = Nullable UpgradeSchedule.afterInstallInitialize, 
                                     DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit.")

```

And here's the generated WIX

`    <MajorUpgrade DowngradeErrorMessage="A later version of [ProductName] is already installed. Setup will now exit." Schedule="afterInstallInitialize" />
`
And this time, I looked at the log. My error message appears there!

Error: A later version of LAS Doctor is already installed. Setup will now exit.

Of course I'm expecting this to be shown to the user, but it isn't. Again, I would swear that at one time this worked.

**Comment by oleg-shilo** [comment]
When using 'MajorUpgradeStrategy' sample it still works:
* Build two msi  "Samples/MajorUpgrade" sample projects: MajorUpgrade1 and   MajorUpgrade2.
* Install  setup.2.msi (MajorUpgrade2)
* Try to install setup.1.msi (MajorUpgrade1)
* Observe error message:
![image](https://user-images.githubusercontent.com/16729806/29347069-20c20f60-828d-11e7-9643-4dbfcaa9ef9b.png)

My feeling is that 'OnlyDetect' is what does the trick:
```C#
 project.Version = new Version("1.0.714.10040");
 project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
 project.MajorUpgradeStrategy.PreventDowngradingVersions.OnlyDetect = false;
```
Also note that it is setup.2.msi (the newer setup) who is supplying the error message. Not the one that you are trying to install.

As for `MajorUpgrade` approach, the same story. This is the set of steps to test the solution:

* Build "Samples/MajorUpgrade/MajorUpgrade" sample project. Rename the msi into 'setup.latest.msi'
* Install  `setup.latest.msi`
* In the setup.cs change the version to lower: `project.Version = new Version("1.0.709.10040");` -> `project.Version = new Version("1.0.209.10040");`
* Build "Samples/MajorUpgrade/MajorUpgrade" sample project again. Leave setup.msi as is.
* Try to install setup.msi
* Observe error message:

![image](https://user-images.githubusercontent.com/16729806/29347924-3881083a-8293-11e7-80b6-196c964a7c74.png)

**Comment by jimfoye** [comment]
I have the same result, the install fails (good), and the error message is logged (good), but the user does not see this error message, only the final dialog saying that setup was interrupted.

I'm using ManagedUI - could that have something to do with it? Perhaps I need to add code to show the user this message? I was just assuming it it happened automatically.

**Comment by oleg-shilo** [comment]
> I'm using ManagedUI - could that have something to do with it?

Yes-yes-yes. I am positive it does. 

MSI/WiX always overlook the possibility of the UI being implemented as `EmbeddedUI` even though it is a standard officially supported technique. That message box on the screenshot is a part of MSI UI sequence, which is completely suppressed when `EmbeddedUI` is enabled. Thus indeed it is a responsibility of the ManagedUI to interact with the user. 

Can you please log a feature request for ManagedUI to have a mechanism for handling upgrading failure.

I am not sure what is involved in this. It would be ideal if MSI sets some dedicated property indicating the failure so ManagedUI can evaluate it and show the error message. If it's not the case then some sort of runtime test by ManagedUI itself needs to be done in order to detect any version conflict. But one or another way it needs to be done as a generic solution.

But until the feature is ready you can do it from the UI:
```C#
project.UILoaded += (SetupEventArgs e) =>
{
    string QueryProperty(string name) => 
              (string)e.Session.Database.ExecuteScalar($"SELECT `Value` FROM `Property` WHERE `Property` = '{name}'");


    var installedVersion = AppSearch.GetProductVersionFromUpgradeCode(QueryProperty("UpgradeCode"));
    var thisVersion = new Version(QueryProperty("ProductVersion"));

    if (installedVersion != null && installedVersion >= thisVersion)
    {
        MessageBox.Show("Later version of the product is already installed : " + installedVersion);
        //e.Result = Microsoft.Deployment.WindowsInstaller.ActionResult.UserExit;
    }
};
```
Note,  `// e.Result` is commented out. It is because setting it will not make any difference as at this stage MSI session is not initialized yes so MSI runtime does not analyse any return value. Thus just show the message and let the setup fail on the LaunchCondition evaluation (where logging will also occur).  

The fact that the session is not initialized is also the reason why the properties directly queried from the DB isnstead being read from the session property bag.

**Comment by oleg-shilo** [comment]
The first implementation (c684512) allows simplified way of scheduling checking for MajorUpgrade compatibility from ManagedUI:

```C#
project.ManagedUI = ManagedUI.Default;
project.ScheduleDowngradeUICheck(
           "Later version of the product is already installed : ${installedVersion}",
            (thisVersion, installedVersion) => thisVersion <= installedVersion);
```

**Comment by jimfoye** [comment]
That looks good, sorry I did not create a separate request, you beat me to the punch.

**Comment by oleg-shilo** [comment]
Yeah, I got intrigued by the challenge and steamed ahead :)

After a few experiments I extended the solution even further. 

The thought was "Why bother with scheduling the check manually if it can be done automatically?". After all in 99% of cases user will only be interested in the "upgrade use-case" that prevents installation of the same or lower version.  

The next question was "Why bother specifying the the error message it another one (identical) is already provided in `MajorUpgrade` initializer?".  

Thus the approach evolved into the automatic call of `project.ScheduleDowngradeUICheck` if `project.ManagedUI` and `project.MajorUpgrade` are defined:
```C#
project.ManagedUI = ManagedUI.Default;
project.MajorUpgrade = new MajorUpgrade
{
    ScheduleManagedUICheck = true,
    Schedule = UpgradeSchedule.afterInstallInitialize,
    DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
};
```
I had to introduce a dedicated `MajorUpgrade.ScheduleManagedUICheck` flag. This is because WiX's `MajorUpgrade` element, despite the name, controls upgrades, downgrades and same-version installs.  Thus there is a need for `project.ScheduleDowngradeUICheck` auto-invoke to be suppressed sometimes (e.g. for downgrades). 

But as a recognition of the predominance of the "true upgrade" use-cases the final shape of the MajorUpgrade support comes in this form:
```C#
project.ManagedUI = ManagedUI.Default;
project.MajorUpgrade = MajorUpgrade.Default;
```
Where `MajorUpgrade.Default` is just a predefined instance you can use right away:
```
public class MajorUpgrade
{
    public static MajorUpgrade Default = new MajorUpgrade
    {
        ScheduleManagedUICheck = true,
        Schedule = UpgradeSchedule.afterInstallInitialize,
        DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
    };
    ...
```

**Comment by jimfoye** [comment]
Awesome!

**Comment by johnferry0** [comment]
This should be quite useful.
