### ISSUE TITLE
project.UIInitialized is not invoked for a bundled installer

### ISSUE THREAD

**Issue by shengxue** [oleg-shilo/wixsharp#1228]
project.UIInitialized is not invoked for a bundled installer. are there anyway to make it invoked?

If it could not be invoked in bundled installer, how to know if the installer runs in silent mode?

**Comment by oleg-shilo** [comment]
This event is only expected to be triggered when EmbeddedUI (ManagedUI) is used.
However, bootstrapper (bundle) suppresses the embedded UI due to the long-standing bug of WiX/Burn. 

I suggest you see this page: https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-integration-notes

The last question there " Why setting DisplayInternalUI ..." is specifically about your scenario.

**Comment by shengxue** [comment]
@oleg-shilo   I wanted to add codes like ```session["quietRun"] = "false"``` in  ``project.UIInitialized```, as  ``project.UIInitialized``` is not triggered in silent mode.   do you have any better idea to know if the installer runs in silent mode?

**Comment by oleg-shilo** [comment]
It's kinda the same answer as for #1230.
you need to remember that if you use managed UI then your UILevel is always 2. 
if you use native UI then UILevel works but UIInitialized is not going to be fired as it is applicable only for ManagedUI.
