### ISSUE TITLE
Folder not removed on uninstalling

### ISSUE THREAD

**Issue by JeremyAnsel** [oleg-shilo/wixsharp#123]
Consider the following code:
```csharp
var project = new ManagedProject("MyProduct",
    new Dir(@"%ProgramFiles%\My Company\My Product",
        new File(@"Files\File1.txt")),
    new RegValue(RegistryHive.LocalMachine, "Software\\My Company\\My Product", "MyRegKey", "1"));

project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.ManagedUI = ManagedUI.Default;

project.BuildMsi();
```

On uninstalling, the folder `%ProgramFiles%\My Company` is not removed.

The generated `wxs` file contains:
```xml
<Directory Id="TARGETDIR" Name="SourceDir">
  <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
    <Directory Id="ProgramFilesFolder.My_Company" Name="My Company">
      <Directory Id="INSTALLDIR" Name="My Product">

        <Component Id="Component.File1.txt" Guid="6f330b47-2577-43ad-9095-18610a53ec84">
          <File Id="File1.txt" Source="Files\File1.txt" />
        </Component>

        <Component Id="Registry1" Guid="6f330b47-2577-43ad-9095-1861b7315623" KeyPath="yes">
          <RegistryKey Root="HKLM" Key="Software\My Company\My Product">
            <RegistryValue Id="MyRegKey" Type="string" KeyPath="no" Value="1" Name="MyRegKey" />
          </RegistryKey>
          <RemoveFolder Id="INSTALLDIR" On="uninstall" />
        </Component>

      </Directory>
    </Directory>
  </Directory>
</Directory>
```

**Comment by oleg-shilo** [comment]
This behavior is a side effect of the `KeyPath="yes"` being used with the registry key element. WiX recommends to set it to "yes" (http://wixtoolset.org/documentation/manual/v3/xsd/wix/component.html).  Otherwise it "can be dangerous". The explanation "why" is not very detailed. And combined with the fact that they forgot to mention such a side effect as yours makes me really question the quality of that documentation article.

Anyway, I just tested and disabling of the KeyPath auto-insertion does solve the problem:
```C#
AutoElements.DisableAutoKeyPath = true;

var project = new ManagedProject("MyProduct",...
``` 

Just in case if you wander why it's not disabled by default - it would trigger WiX/MSI problems for other scenarios (e.g. Certificates, EnvVariables and SqlDatabase samples).  And... `KeyPath="yes"` is what recommended by WiX team.

Though I will see if anay improvements are possible in that area.

**Comment by oleg-shilo** [comment]
Indeed some improvement were possible. Currently  auto-injection of the KeyPass is suppressed for components containing files. But actually it needed to be expanded for registries (your case) as well. 

Done. Will be available in the next release.

**Comment by JeremyAnsel** [comment]
Thanks

**Comment by oleg-shilo** [comment]
Until the fix is available you can change the KeyPass attribute in the post-build event `Project.WxsGenerated`. Or if you are eager to try the fix you can just grab the latest binary WixSharp.dll for GitHub: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples

**Comment by ErikParso** [comment]
Hello, is it released already ? I see this thread is 2 years old and i have a same problem now. Here is project definition.

    var project = new Project("MyProduct",
                      new Dir(@"%ProgramFiles%\My Company\My Product",
                        new Dir("Client", 
                            new Files(System.IO.Path.Combine(clientFiles, "*.*"))),
                        new Dir("Service",
                            new Files(System.IO.Path.Combine(serviceFiles, "*.*")))),
                      new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Run",
                        "AspWinServiceClient", @"[INSTALLDIR]Client\AspWinServiceClient.exe")
                      {
                          Win64 = true
                      })
    {
        Platform = Platform.x64,
        GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b"),
        Version = new Version("1.0.0.0"),                                                              
        MajorUpgradeStrategy = MajorUpgradeStrategy.Default,
    };

**Comment by oleg-shilo** [comment]
Yes it is released.

WiX may have numerous causes of leaving the folders behind.You may want to
analyse your generated WXS for clues.
The problem described in this issue was related to the WiX workflow for `
KeyPath="yes" `attribute. It is fixed now by WixSharp implementing work
around but your case may be different.
