### ISSUE TITLE
project.AfterInstall unable to remove service and delete installation directory

### ISSUE THREAD

**Issue by SOliyhan** [oleg-shilo/wixsharp#1245]
Hi Oleg, I'm using e.IsUninstalling to remove the path variable. ServiceInstaller is supposed to remove the service and installation directory automatically after calling this function in AfterInstall but somehow it couldn't. 
```
project.AfterInstallfunc()
  {
  if (e.IsUninstalling)
              {
                  loging.log("some logs");
                  new SomeFunction(e.InstallDir).RemovePath();
              }
  }
```
I'm using this in ServiceInstaller for remove and stop:
```
StopOn = SvcEvent.InstallUninstall_Wait,
RemoveOn = SvcEvent.InstallUninstall_Wait,
```

**Comment by oleg-shilo** [comment]
Services are stubborn creatures. OS often fails to remove service (e.g. because it's locked) in such cases Service Manager "Marks Service For Deletion" but does not delete the files/dirs, Thus Service Manager only schedules the deletion of the service file structure in the future at the appropriate moment.

The actual deletion time is non-deterministic. 

All this complexity has nothing to do with MSI/WiX/WixSharp it is how Windows works..
