### ISSUE TITLE
Error installing package built in linux + wine

### ISSUE THREAD

**Issue by igorekRnd** [oleg-shilo/wixsharp#1248]
I built the MSI package using cscs.exe from a VM and it installs without error. I'm trying to do the same through wine, the package is 2 MB more than in Windows, and during installation it gives an error unpacking user functions. That is, I see the initial form and then the error. Tried building with wine-mono and also installed various dotnets in wine. The result is the same. The error is like this:

SFXCA: Extracting custom action to temporary directory: C:\users\igor\Temp\msi6d4c.tmp-\
SFXCA: Failed to extract to temporary directory. Cabinet error code 1.

I myself tried to solve this problem for 2 days, but could not. Please help. I can write my email for quick feedback.

Wixsharp version 1.20 (latest)
Wix Version 3.1.1
wine version 7.22

**Comment by oleg-shilo** [comment]
Hi Igor,

It is a difficult one to overcome. 
WiX heam has created a hosting infrastructure that allows a native dll that implements custom action to load a user-defined assembly (from resources) and exercise the well-known entry point from that assembly at runtime.

Seems straightforward. Though. WiX expects this assembly to be compatible with a particular CLR. Thus you may (or may not) experience runtime compatibility problems depending on how you built your assembly. I am guessing wine/mono introduces something into an assembly that does not allow it to be extracted, loaded and executed on windows. The excessive size of the assembly file is an indirect confirmation size.

Thus you have only a few options. Either:

1. Use windows only to build msi
2. Use a windows-built assembly bridge that embeds CS-Script script engine so instead of compiling your custom action it will be executed at runtime as a script. Your script will need to be embedded in your msi as a file.

#2 is way more complicated than #1

**Comment by igorekRnd** [comment]
Here is a person who managed to build an MSI package using wine from Linux. True, I do not know if he used user functions in c#. By the way, Oleg, he turned to you for help (this is discussed in the article), and you helped him.
https://bozaro.ru/2016/04/19/wix-wine-wixsharp/

**Comment by oleg-shilo** [comment]
LOL, it was l-o-o-o-ng time ago :)
I forgot about it completely.
Indeed Artem was using WixSharp to build raw native MSI without managed custom actions.

wine is not a problem. It is Mono who is building the assembly. And judging from the size of the file, most likely it is embedding runtime CLR in the assembly. And this would prevent such an assembly to be a portable one.  

Most likely there is a magic Mono compiler param that allows building naked assembly but I do not know it. 
Though if you do then you can simply tunnel it to the compiler:
```
PS D:\dev\cs-script\src> cscs -co ?
-co:<options>
    Passes compiler options directly to the language compiler.
    (e.g.  `-co:/d:TRACE` pass `/d:TRACE` option to C# compiler
     or    `-co:/platform:x86` to produce Win32 executable)
``` 

You can test the switch by trying to build the builder executable from the script (instead of running it). 
```
cscs -e <magic-mono-compiler-switch> setup.cs
```

If the executable is small then most likely it is a naked assembly. If it is large then it contains mono runtime.

**Comment by igorekRnd** [comment]
I didn't succeed. I tried to build using wine + .Net4.0 (without mono. Mono gave some other errors when building). So far, I decided to compile from Linux using a virtual box in headless mode (without GUI) + window10 + autorun of the build script.

**Comment by oleg-shilo** [comment]
Great. If it works... it works 😄

**Comment by igorekRnd** [comment]
Олег, а как с тобой связаться по этому вопросу?

12 января 2023 г. 16:28:17 GMT+03:00, Oleg Shilo ***@***.***> пишет:

**Comment by oleg-shilo** [comment]
Arguably GitHub is the best place for that.
