### ISSUE TITLE
Question: Installation files not getting removed when MSI was installed from a windows service.

### ISSUE THREAD

**Issue by pr4v33nv3rm4** [oleg-shilo/wixsharp#1251]
Hi,
We have a wix# code that was generating reliable MSI for a long time, given we use to do the manual installation and provided all the properties using managed UI.

Now there is a need to automate the installation process and we have a windows service (running as a local user with admin rights) that is invoking msiexec with parameters and /quiet.  

Installation is working fine but whenever we try to uninstall the build manually (using the same user account which was used for installation) either from "uninstall shortcut" or "from programs & features" or via the MSI remove option it simply shows success and removes the entry from programs & features but doesn't remove any of the installation files.

The same behavior is observed if giving uninstall command to the windows service (which has done the installation) note: uninstall is using ManagementObjectSearcher and InvokeMethod("Uninstall", null) and not using msiexec -x.

However, if the same MSI is installed manually using UI, it is getting uninstalled also properly.
Any help would be appreciated to narrow down my RCA.

**Comment by Torchok19081986** [comment]
Hiho, many open questions here. 
1. is your msi for current user or fot all users on targetmachine?
2. has your msi access to path for uninstal files? If not , it should appear UAC for credentials. quiet parameter is here useless.
3. according to MS, windows services should not interact with desktop, cause many problems with registry. 

you can check for updates etc. in windows services, then compare and show it to user, , but install should be with UI. Only if user clicked it for Update etc. Good Example is Adobe Reader DC  package. Maybe open msi of it and check it for windows services entry in install. 

Had same issue with msi, was not doable. Had to change deployment strategy here.

**Comment by oleg-shilo** [comment]
Since MSI reported success then, it looks even more like ServiceManeger is holding some files.
Did you try to restart just after a "successful" uninstall?

If this does not help, you can try this simple experiment.
- Install your service with MSI
- start the service
- stop the service
- Delete service with `sc.exe delete <service name>` (you may also use PS commands for that)
- Verify with the service manager that the service does not exist anymore.
- restart again
- Uninstall your service msi. Doesn't matter how, either via control panel or msiexec

I expect it to remove the service files
