### ISSUE TITLE
Cancel during uninstall not working

### ISSUE THREAD

**Issue by SOliyhan** [oleg-shilo/wixsharp#1255]
Hi,
I have been trying to cancel the install/uninstall process to ensure a rollback is performed when cancel button click event is called. I am not able to cancel the on going uninstall process to prevent the removal of application if cancel button is clicked. Although I am successfully able to prevent installation during install action. Any suggestions ?

**Comment by SOliyhan** [comment]
Hi Oleg, can you provide a way to proceed in this direction. Thanks

**Comment by oleg-shilo** [comment]
I am not sure I have the answer you are looking for.
Uninstalling used MSI native uninstall UI. WixSharp is not involved in it. 
Most likely the answer will be in the MSI-related forums.
Sorry

**Comment by oleg-shilo** [comment]
I'll have a look at it

**Comment by oleg-shilo** [comment]
It is a n interesting but difficult problem to solve.

MS did not provide any way to cancel a started setup (both install and uninstall) if UmbeddedUI is used. Thus their interface `IEmbeddedUI` don't have any method for cancellation.

WixSharp provided the workaround by injecting a custom action `CancelRequestHandler` that is executed just before `InstallFiles` action. This custom action does not do anything but simply returns a failure code if the cancel button was pressed before we reached this point of installation. This will abort the whole setup. 

This workaround is not perfect and was intended for installations only. That's why it is disabled for the uninstalls vial ` (NOT (REMOVE="ALL")) ` condition:

```xml
<InstallExecuteSequence>
      <Custom Action="WixSharp_InitRuntime_Action" Before="AppSearch"> (1) </Custom>
      <Custom Action="Set_CancelRequestHandler_Props" Before="InstallFinalize" />
      <Custom Action="CancelRequestHandler" After="Set_CancelRequestHandler_Props"> (NOT (REMOVE="ALL")) </Custom>
      <Custom Action="WixSharp_Load_Action" Before="AppSearch">1</Custom>
      <Custom Action="Set_ARPINSTALLLOCATION" After="CostFinalize"> (NOT Installed) </Custom>
    </InstallExecuteSequence>
```

What I haven't done is the disabling the cancel button for uninstalls.

Though you can try an experiment and try to use the same workaround but for uninstalls. For that you will need to remove that condition with this code:

```C#
        project.WixSourceGenerated += Project_WixSourceGenerated;

        project.BuildMsi();
    }

    private static void Project_WixSourceGenerated(System.Xml.Linq.XDocument document)
    {
        var customAction = document.FindAll("Custom").FirstOrDefault(x => x.HasAttribute("Action", "CancelRequestHandler"));
        customAction.Value = "1";
    }
```

This may, or may not work. I cannot test it as I don't have a long-running uninstall to experiment with.
But you can try. Let me know how the outcome.

**Comment by oleg-shilo** [comment]
You can also look at the code for details: https://github.com/oleg-shilo/wixsharp/blob/053fef6acfd31eba0cd8148db33247cc29399581/Source/src/WixSharp.UI/ManagedUI/ManagedUI.cs#L235-L242

**Comment by SOliyhan** [comment]
Thank you, the workaround you suggested did worked for me. Closing it now!!

**Comment by oleg-shilo** [comment]
This will be the default behaviour in the next release ([6cd40a5](https://github.com/oleg-shilo/wixsharp/commit/6cd40a5e8e63ebdc14450f44b8a0cc564ad526e4)).

**Comment by RachelXGanon** [comment]
@oleg-shilo  Did release it?

**Comment by oleg-shilo** [comment]
yes
