### ISSUE TITLE
From Inno to WixSharp

### ISSUE THREAD

**Issue by DieselBY** [oleg-shilo/wixsharp#126]
Hello, Oleg!
I have one old project made with Inno installer. Now I need msi installer and WixSharp if perfect. 

but Inno setup have one bad side:
ProductId isn't guid, but guid but guid with suffix something like with
{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}_is
so I faced to problem how you update my project with installer made be WixSharp. 
I have no idea how to solve it, I hope on you :-)

with regards, Mike...

**Comment by oleg-shilo** [comment]
Hi Mike,

_**Guids**_
As far as I remember Inno is not an MSI based installer but a custom deployment solution/technology. I remember reading about Inno plans to move to MSI but not sure if they did. 

This is important because if your Inno setup is an MSI setup then you would want to reuse the same GUIDs. The easiest way to solve this is to verify if your setup binary is an *.msi file. If it is, you would need to open it in Orca (msi reader) and capture the all guids. After that you can reuse these guids in your WixSharp setup. 

If your setup file is an *.exe then it may be because it is an MSI bootstrapper or a non-MSI setup at all. In case of the bootstrapper it's hard to extract guids without knowing the Inno internals. If it is non-MSI setup then you have no need for any Inno specific guids anyway.

**_Updating_**
The actual update of the already installed (with Inno) products it's complicated. If your previous Inno setup version is MSI-based **and authored as upgradable** then you can build a new MSI setup with WixSharp that would smoothly upgrade any previous deployment. However if it's not (or it is not an MSI setup) then you are out of luck. :(

You can still build your new MSI setup (e.g. with WixSharp) but you will need tho think how you are going to deal any with previous installations. The options are:

- Have them side-by-side without affecting each other
- Detect older version, ask user to uninstall it and do not proceed until it's done.
- Detect older version, automatically remove it and proceed with the new MSI deployment.

I hope it gives you some prospective...

**Comment by DieselBY** [comment]
Thank, for your answer.

Yes, Inno isn't MSI based installer. 
My question is:
can I make ProductID with WixSharp not as guid, but as string like in Inno:
![reg](https://user-images.githubusercontent.com/30905635/29205254-61ced6da-7e84-11e7-8797-99768f7146d8.png)

**Comment by oleg-shilo** [comment]
Well, you can change the Id:
```C#
project.WixSourceGenerated += 
    doc => doc.Root
              .Select("Product")
              .SetAttribute("Id", "6f330b47-2577-43ad-9095-1861ba25889b_is1");
```
And it does yield the desired Id string:
![image](https://user-images.githubusercontent.com/16729806/29215370-269f94f4-7eee-11e7-830b-d797fef582b7.png)

But it is WiX/MSI (not Wix#) who is not happy about a non-guid Id:
```
...\Wix# Samples\Explicit IDs\MyProduct.wxs(3) : error CNDL0009 : The Product/@Id attribute's 
value, '6f330b47-2577-43ad-9095-1861ba25889b_is1', is not a legal guid value.
```
If you can find the way to trick WiX compiler then you will achieve your objective.

**Comment by DieselBY** [comment]
Thanks...
Eeh... no easy ways...

**Comment by oleg-shilo** [comment]
You can also try manually patch (replace the Id value) the produced msi with Orca. If it works then you can do the patch programatically after the build.
