### ISSUE TITLE
arm64 support for project templates extension

### ISSUE THREAD

**Issue by Laptop765** [oleg-shilo/wixsharp#1270]
Are there plans to support installing the [WixSharp Project Templates extension](https://marketplace.visualstudio.com/items?itemName=OlegShilo.WixSharpProjectTemplates&ssr=false#overview) on [`arm64` builds of Visual Studio 2022](https://sinclairinat0r.com/2022/12/23/add-arm64-support-to-your-visual-studio-2022-extensions)? I'm building an `x86`-targeted binary and my development machine is `arm64`.

**Comment by oleg-shilo** [comment]
Not really,
The VS project is in fact a builder executable. You run it and it invokes WiX tools that build the actual MSI. Thus the CPU architecture of the project is completely irrelevant.

The only case when it is important is when you use managed custom actions to `ManegedProject`, which also creates managed custom actions. In this case the custom action assembly is the same assembly that VS project builds.

But... since custom action assembly needs to be of the same CPU architecture as the MSI service runtime installed on the target machine. And MSI only supports x86. 

Thus even if you change the target platform of the project manually, it will not do you any good.

If you need to install your product on the x64 machine in the x64 system and user profile, then this is what you need:[you simply need to set the platform of your project.](https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#x64-components)

**Comment by Laptop765** [comment]
I'll still be targeting 'x86' with all of my builds including the installer. I was wondering about the template extension, not the actual installer project. The extension isn't even installable on 'arm64'.

**Comment by oleg-shilo** [comment]
Ah, I see see your point. Agree.
Will do over wekend

**Comment by oleg-shilo** [comment]
Done. Published. Check out the version v1.17.3

**Comment by Laptop765** [comment]
Wow that was quick! Thanks a bunch 😀
