### ISSUE TITLE
Error while installing IIS certificate

### ISSUE THREAD

**Issue by strozzac** [oleg-shilo/wixsharp#1303]
I'm using the following code to define my IIS certificate entity:

``` 
Certificate = new IISCertificate
                                    {
                                        Name = "iisCertName",
                                        Id = "iisCertId",
                                        CertificatePath = "[IIS_CERT]",
                                        StoreLocation = IISCertificate.CertificateStoreLocation.localMachine,
                                        StoreName = IISCertificate.CertificateStoreName.personal,
                                        Request = false,
                                        Overwrite = true,
                                    }
```
it generates the following .wxs code:
```
                ...
                <WebAddress Id="WebSite_Address1" IP="*" Port="8085" Secure="yes" />

                <CertificateRef Id="iisCertId" />
              </WebSite>

              <Certificate Id="iisCertId" Name="iisCertName" CertificatePath="[IIS_CERT]" Overwrite="yes" Request="no" StoreLocation="localMachine" StoreName="personal" xmlns="http://schemas.microsoft.com/wix/IIsExtension" />

```
which looks good to me, but during the installation process I got the error:
```
Info: InstallCertificates:  Error 0x80070057: Invalid Certificate.Attributes.
Info: InstallCertificates:  Error 0x80070057: Failed to resolve certificate: iisCertId
Info: CustomAction InstallCertificates returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

I found this 12yo issue regarding wix on the internet: https://wix-users.narkive.com/JLo0bkKH/certificatepath-in-certificate-element-does-not-work
they blame `Overwrite="yes"` there.

I decided to test my code with `Overwrite` set `false` and I got a new one:

```
Info: InstallCertificates:  Error 0x8000ffff: Unexpected certificate type read from disk.
Info: InstallCertificates:  Error 0x8000ffff: Failed to read certificate from file path.
Info: InstallCertificates:  Error 0x8000ffff: Failed to resolve certificate: iisCertId
```

Could you help with a solution or at least a workaround for this? I'm passing a valid certificate which works if I insert the actual path to the `File` property, but I want to take a path from parameters so I can pass it dynamically during the installation process.

**Comment by oleg-shilo** [comment]
It works with the hardcoded path, so everything is OK with your setup architecture.

This type of problem can be caused by sometimes property dereferencing in the attribute value not being allowed by the WiX specification. Thus I have checked the [spec](https://wixtoolset.org/docs/v3/xsd/iis/certificate/) and it seems that `CertificatePath` attribute indeed may be set via a formatted Property (e.g. [MyProperty]). 

Then it is possible that your property `IIS_CERT` is not set when it is dereferenced in the `Certificate` element.

To check this idea you can ensure that the property is set to the hardcoded property value just from the start of the setup.
```C#
var project  =  new Project(...
                    ...
                    new Property("IIS_CERT", "<your hardcodded path>"),
                    ...);
``` 

If this test works it means that somehow your setup is failing to initialize the `IIS_CERT` property to the right value at the right time.

Hope it helps.

**Comment by strozzac** [comment]
It doesn't work with the property as well, the error is the same:
```
Info: InstallCertificates:  Error 0x8000ffff: Unexpected certificate type read from disk.
Info: InstallCertificates:  Error 0x8000ffff: Failed to read certificate from file path.
Info: InstallCertificates:  Error 0x8000ffff: Failed to resolve certificate: iisCertId
```
