### ISSUE TITLE
Bootstrapper debug

### ISSUE THREAD

**Issue by DieselBY** [oleg-shilo/wixsharp#132]
Hello, Oleg

Is it any ability to debug setup which made by bootstrapper?

  ```C#
ManagedProject proj = new ManagedProject( "My project"
// some files and regvalues
                                );
      proj.ProductId = new Guid( "5E64BACA-8A96-49FA-8879-42E50FE8E354" );

      proj.LicenceFile = "SOFTWARE-AGREEMENT.rtf";
      proj.OutFileName = "SomeSetup";

      proj.ControlPanelInfo.Manufacturer = "Some Manufacturer";
      proj.ControlPanelInfo.ProductIcon = "app.ico";

      proj.Version = new Version( "1.2.3.4" );

      proj.SetNetFxPrerequisite( "NETFRAMEWORK40CLIENT='#1'", "Please install .NET 4.0 client profile first." );

      proj.ManagedUI = new ManagedUI();
      proj.ManagedUI.InstallDialogs.Add( Dialogs.Welcome )
                                   .Add( Dialogs.Licence )
                                   .Add( Dialogs.InstallDir )
                                   .Add( Dialogs.Progress )
                                   .Add( Dialogs.Exit );

      proj.Load += LoadMSI;
      proj.AfterInstall += AfterInstall;

      WixSharp.AutoElements.DisableAutoKeyPath = true;

      string productMsi = Compiler.BuildMsi( proj );

      var bootstrapper =
        new Bundle( "Q Die Prod",
            new PackageGroupRef( "NetFx40ClientRedist" ),
            new MsiPackage( productMsi ) { Id = "DieProductPackageId", DisplayInternalUI = true } );

      bootstrapper.Version = new Version( "1.0.0.0" );
      bootstrapper.UpgradeCode = new Guid( "6f330b47-2577-43ad-9095-1861bb25889a" );
      bootstrapper.Application = new SilentBootstrapperApplication(); //ManagedBootstrapperApplication( "%this%" ); // you can also use System.Reflection.Assembly.GetExecutingAssembly().Location

      bootstrapper.PreserveTempFiles = true;
      bootstrapper.SuppressWixMbaPrereqVars = true;

      bootstrapper.Build();

```

In case .NET 4.0 is not installed I get installation and nothing more, but I can't uninstall "Q Die Prod" also nothing happens. 
In case NET 4.0 is installed I get nothing. 
Is it at any way to get any information of setup execution?

Maybe I Have made stupid mistake and there no need in setup debugging.

Regards, Mike

**Comment by oleg-shilo** [comment]
Hi Mike,

OK. The good news is that I can explain the believer. The bad one is that I cannot help you to fix it.

If you check your compilation output then most likely you will see the warning line:
```
"WARNING: You have selected enabled DisplayInternalUI for EmbeddedUI-based...
```
It is Wix# is warning you about the problem.

You are using ManagedUI (MsiEmbeddedUI in MSI terminology). Great. But WiX has a long standing bug that exhibits itself in failure to display WmiEmbeddedUI but native UI only: wixtoolset/issues#4921. The bug is ~2 years old and WiX team schedule the fix for x4.x milestone. But if it ever happen... Who knows?

Thus, unfortunately no changes in Wix# can address the problem.

This leaves you only a few options. None of them is particularly great. Use native UI but with an injected custom CLR dialog (dedicated VS template). Or rely only on a custom Bootstrapper UI and hide MSI UI completely. Similar options are also nominated in the related issue #15 discussion.

Cheers,
Oleg

**Comment by DieselBY** [comment]
thanks, Oleg.
I'll try native UI.

**Comment by DieselBY** [comment]
its works with native UI, but how can I add more than one tool to install?
I need .net and vcredist installed

Regards, Mike

**Comment by oleg-shilo** [comment]
This is the task for a Bootstrapper bundle. You will find the corresponding samples in the "Samples" folder.

**Comment by DieselBY** [comment]
But this back problem back me to first question, when I can't use UI or have to use native UI...
Native UI is good, but is't works with only one additional tool to install...
can you suggest something?

Regargs, Mike

**Comment by DieselBY** [comment]
btw one more question

when I remove UI

```
      var bootstrapper =
        new Bundle( "Q Die Prod D2",
            new MsiPackage( productMsi )/* { DisplayInternalUI = true }*/,
            new ExePackage( @"dotNetFx40_Client_x86_x64.exe" )
            {
                 Name = "Microsoft .NET Framework 4.0 Client",
                 InstallCommand = "/passive /norestart",
                 Permanent = true,
                 Vital = true,
                 DetectCondition = "Netfx4Client"
            },
            new ExePackage( @"vcredist2010sp1_x86.exe" )
            {
              Name = "VC 2010 Redist",
              InstallCommand = "/install /quiet /norestart",
              Permanent = true,
              Vital = true,
              DetectCondition = "VC10Redist86"
            }
            );

      bootstrapper.IncludeWixExtension( WixExtension.Util );

      bootstrapper.AddWixFragment("Wix/Bundle",
                                    new UtilRegistrySearch
                                    {
                                        Root = RegistryHive.LocalMachine,
                                        Key = @"Key=SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Client",
                                        Value = "Install",
                                        Variable = "NOT Netfx4Client"  // I was trying "Netfx4Client" with out not
                                    },
                                    new UtilRegistrySearch
                                    {
                                        Root = RegistryHive.LocalMachine,
                                        Key = @"Key=SOFTWARE\Microsoft\VisualStudio\10.0\VC\VCRedist\x86",
                                        Value = "Installed",
                                        Variable = "NOT VC10Redist86"  // I was trying "VC10Redist86" with out not
                                    } );
```

As I see detection isn't work, all the time vcredist and .net are installing
May be not, the installation date does not change, but progress is running
 Variable = "NOT VC10Redist86"  or Variable = "VC10Redist86" all the same

This thoughts comes from native UI, when no progress run if tool already installed...

Thanks.

Regards, Mike.

**Comment by oleg-shilo** [comment]
> ...or have to use native UI...
Native UI is good, but is't works with only one additional tool to install...

I have already suggested two options: 
1. Use native UI but **with an injected custom CLR dialog** (dedicated VS template). 
2. Or rely only on a custom Bootstrapper UI and hide MSI UI completely. 

Option 1 involves custom UI that can be displayed form your bootstrapper.
Option 2 involves custom UI of the bootstrapper itself.

**Comment by oleg-shilo** [comment]
As for you last question it's hard for me to comment on what is the accurate definition of the conditions you are looking for. 

Thus your best chance is to consult Bundle/Bootstrapper documentation. Particularly `Util:RegistrySearch` element.

A one strong suspect is `Variable = "NOT VC10Redist86"`. It's supposed to be a name of the variable not a condition expression: http://wixtoolset.org/documentation/manual/v3/xsd/util/registrysearch.html

**Comment by DieselBY** [comment]
sorry, but we walk in a circle

> 
> its works with native UI, but how can I add more than one tool to install?
>  I need .net and vcredist installed
> 

> This is the task for a Bootstrapper bundle. You will find the corresponding samples in the "Samples" folder.

may be exists solution for 2 tools to install and native UI or Bootstrapper bundle with UI to set up installation path

**Comment by oleg-shilo** [comment]
Yes such a solution exists. Your description is pretty much what I was suggesting. 

A typical boostrapper use-case is when you wants to distribute a product and also wants to have an option to deploy prerequisites and some tools/utilities. 

All this screams "bootstrappar". Good. 

Thus you make your product to be a primary package in your bundle, while prerequisite and tools are also included as secondary packages. "Primary" in this context  mans that the package defines the bootstrapper startup action: if package is detected then bootstrapper should uninstall the whole bundle or install it otherwise. Secondary packages will align to the primary one (e.g. deployment destination). 

Next, you need to decide how to collect the user input (e.g. install dir). You can do it from the custom bootstrapper UI before any package installation. This will also imply that you suppress any package own UI. 

Alternatively you can customize the primary package UI while using standard bootstrapper UI.

The above is the same set of two options that I mentioned but with more details.

Though you will need to sort out how to pass the data (e.g. installdir, variables) between packages. And this is where  you have the problem that is not solved yet (see my very previous post).

**Comment by DieselBY** [comment]
Thanks a lot, Oleg.

I have understand all your thoughts about UI.

And I still need your help, thanks for your patience.

I started to fulfill from simple path: correct cwith my msi, .net and vcredist.
As I described above, code was the same. I had such a problem that after installation I have 4 programs in installed programms:
my project
vcredistr
.net
and 
Bundle named "Q Die Prod D2"

and I can't uninstall this "Q Die Prod D2"
If all other products installed, uninstall do nothing.
If something uninstalled and I want to uninstall "Q Die Prod D2" it want to install all other things. 

You have write about primary and secondary packages.I was playing with Bundle settings and features and broke something. Problem was with rights (as I think), I was trying back, but failed and have unknown problem. I'll attach logs.
I beg to help me...

third small question with sample WixBootstrapper_UI
error LGHT0195 : The Windows Installer XML variable 'WixMbaPrereqPackageId' is declared in more than one location.  Please remove one of the declarations.
error LGHT0195 : The Windows Installer XML variable 'WixMbaPrereqLicenseUrl' is declared in more than one location.  Please remove one of the declarations.
can I fix it myself?

Regards, Mike.

**Comment by DieselBY** [comment]
thanks, a lot.
