### ISSUE TITLE
Wix V4: the sample of Install on x64 generate a msi which installs components to Program Files (x86)

### ISSUE THREAD

**Issue by akiras-ssrd** [oleg-shilo/wixsharp#1329]
When I try to do the sample of Install on x64 at wix-v4-master branch, the generated msi installs components(e.g., MyApp.exe) to Program Files (x86).
It looks the generated msi is a x86 installer. I checked it using orca.exe: View -> Edit Summary Information -> Platform: x86.

Add "-arch x64" options to build command like the followings:

```
        // uncomment this line if you want to make the build of the x64 vs x86 controlled by the external condition.
        // if (Environment.GetEnvironmentVariable("buid_as_64") != null)
        project.Platform = Platform.x64;

        project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");

        project.WixOptions = "-arch x64";
        project.BuildMsi();
```

After add that, the platform on orca.exe was changed from x86 to x64 and components was installed to Program Files.

**Comment by oleg-shilo** [comment]
I checked it and indeed it is a defect.
This is strange and ..., to put it bluntly, really bad.

**Strange,** because the msi produced with and without "-arch x64" are virtually identical. WXS are completely identical;. The only difference is the hidden section of MSI `Summary Information.

**Bad,** because in WiX3 version compilers were able to infer the architecture from the WXS elements. But in WiX4 one needs to provide a special CLI argument for that. To make it worse WXS still have all x64 context present but when compiled without "-arch x64" it produces. Well... technically speaking who knows what (the documentation is silent about that) but seems like a x86 setup:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/d798a50f-26e1-4c91-a567-b87db69624ac)

It is a serious defect caused by the WiX3-WiX4 changes. Will be releasing the fix asap.

**Comment by akiras-ssrd** [comment]
Thank you for quick fix! I also do the sample of Install on x64 and it works fine.

The following is just a guess of this issue:
- The Bitness attribute controls just only msidbComponentAttributes64bit(256).
- Windows installer expands ProgramFiles64Folder to Program Files (x86) if the hidden plafrom section is x86 regardless of msidbComponentAttributes64bit(256).
- (In WiX4, moved the flag which contorls the hidden section used as platform selection from Package element to command line argument, so remove Platform attribute from Package element.)

**Comment by oleg-shilo** [comment]
Yes, I think you are right.

> Windows installer expands ProgramFiles64Folder to Program Files (x86) if the hidden plafrom section is x86...

Yep, my point is that I prefer it to throw the compile error instead. But, well it's not the last awkward thing about MSI 😄

Anyway, a single-line statement now takes care of this:  
```C#
project.Platform = Platform.x64;
```
