### ISSUE TITLE
[Bug / Request] I am attempting to use bootstrapper.SetVersionFromFile(@"..\..\..\#######") but get a compiler error

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1374]
As mentioned in #1373

# Bug
I am attempting to use `bootstrapper.SetVersionFromFile(@"..\..\..\#######");` for the version, but I then get the following error
```
4>Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Deployment.WindowsInstaller, Version=3.0.0.0, Culture=neutral, PublicKeyToken=ce35f76fcda82bad' or one of its dependencies. The system cannot find the file specified.
4>   at WixSharp.CommonTasks.Tasks.GetVersionFromFile(String filePath)
4>   at SRLESuiteInstallerUI.Program.Main() in Z:\Repos\SRLE\6EndInstall\Poc\SRLESuiteInstallerUI\Program.cs:line 25
4>Z:\Repos\nuget\wixsharp\1.23.0\build\WixSharp.targets(5,5): error MSB3073: The command ""Z:\Repos\SRLE\6EndInstall\Poc\SRLESuiteInstallerUI\bin\Release\net48\SRLESuiteInstallerUI.exe" "/MSBUILD:SRLESuiteInstallerUI" "/WIXBIN:" "/Configuration:Release" "/Platform:AnyCPU"" exited with code -532462766.
```

Which is stating the missing `Microsoft.Deployment.WindowsInstaller` and not the missing file path name passed into the API call.

# Request
It appears that the nuget package for WixSharp should also include a reference to https://stackoverflow.com/a/15749287
```
Update 5/10/2023-

As part of WiX Toolset's migration to Nuget and ProjectStyle SDKs, this assembly has been renamed to WixToolset.Dtf.WindowsInstaller and is available via Nuget.

https://www.nuget.org/packages/WixToolset.Dtf.WindowsInstaller
```

i..e Change the existing prjects to use the nuget, and also change the published nuget to state a pull requirement for `WixToolset.Dtf.WindowsInstaller`

**Comment by oleg-shilo** [comment]
The error message for the invalid path is reporting the problem correctly:
```c#
bootstrapper.SetVersionFromFile("c:\\invalid_file_that_doesnot_exist");
```
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/3b4f5fe8-2798-44e0-88a7-bb4c415264ba)

What you have observed in your experiment was the result of using broken package that we were using while troubleshooting. Currently, the problem is solved and the `WixToolset.Dtf.WindowsInstaller` asset is restored in the `WixSharp.bin` package.

Note, the old WiX3 targeting packages have `WixToolset.Dtf.WindowsInstaller` embedded in the package. This is because WiX team at that time distributed `WixToolset.Dtf.WindowsInstaller` as part of the WiX SDK.

But Wix4 targeting packages have the package dependency for `WixToolset.Dtf.WindowsInstaller`. It is possible now because WiX4 has changed the distribution model for the tool itself and the tool dependencies.
