### ISSUE TITLE
[Request] Cannot update to latest Caliburn.Micro

### ISSUE THREAD

**Issue by BorderKeeper** [oleg-shilo/wixsharp#1387]
STR:
1. Update to latest Caliburn.Micro in your Installer project
2. Compile your installer
Expected: Caliburn DLLs are loaded into the installer context and used for the custom XAML UI pages
Actual: Installation fails due to error in `GetUiDialogsDependencies`

Looking into `GetUiDialogsDependencies` it seems that the assembly names are hardcoded, but sadly Caliburn.Micro renamed `Caliburn.Micro.dll` into `Caliburn.Micro.Core.dll` in the 4.0 version.
```System.Reflection.Assembly.Load("Caliburn.Micro").Location,
System.Reflection.Assembly.Load("Caliburn.Micro.Platform").Location,
System.Reflection.Assembly.Load("Caliburn.Micro.Platform.Core").Location,
System.Reflection.Assembly.Load("System.Windows.Interactivity").Location
```

We would normally be happy to stay on the old version, but our different UI project us updated and causing the installer to fail if we have Caliburn mismatch.

**Comment by BorderKeeper** [comment]
DLLs you would see on older Caliburn versions:
![image](https://github.com/oleg-shilo/wixsharp/assets/7063238/d660d162-f375-438e-8b2d-c9b336ab2504)

DLLs you see compiled on the 4.0 version:
![image](https://github.com/oleg-shilo/wixsharp/assets/7063238/f4d2cbff-f1cd-4c05-9eb0-b622e780b2b4)

**Comment by oleg-shilo** [comment]
Great, thank you for letting me know. Will try to release the patch on weekend.

**Comment by oleg-shilo** [comment]
Done. You can import now v1.24.0.0 packages

**Comment by PatrickKursawe** [comment]
This brings a runtime failure in my setup using a WPF dialog because it can't load caliburn.micro.core - downgrading to .2 of WixSharp makes it work again.

**Comment by oleg-shilo** [comment]
Thank you. Indeed assembly probing got broken for WiX4 build. Looking into it.

**Comment by oleg-shilo** [comment]
This is a very interesting problem caused by some peculiar behaviour of Nuget package manager.

The WixSharp VS template nominates the project dependency on WixSharp v2.0.0.0, which in turn depends on Caliburn.Micro v3.3.  On build both these packages are installed and successfully embedded in the msi file, which behaves at runtime as expected.

However, when you go to the package manager and update WixSharp (e.g. to v2.0.4.0) it fails to update Caliburn packages. It's is not fully unexpected because the latest WixSharp package dependencies are require not updated. Thus the new WixSharp is still trying to build with the old Caliburn. 

This can be easily addressed but updating the Caliburn package to the v4.* version manually. See the attached solution. 
[WixSharp Setup9.zip](https://github.com/oleg-shilo/wixsharp/files/13996633/WixSharp.Setup9.zip)


This will be fixed with the very next release by updating WixSharp metadata with the dependency on Caliburn v4 so no annual update is required.

However, what is really strange is that VS nuget manager does not prompt the user that there is an update for the Caliburn package as it normally does:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/84856e3b-b8f1-40be-ab95-59cb011fa5f4)


--------------

Until the fix is available, please update Caliburn manually.

**Comment by PatrickKursawe** [comment]
I think you only get prompted for direct dependencies.

Thanks for looking into this so quickly.

Patrick


Patrick Kursawe PhD.
Senior Software Developer
Trajan Scientific and Medical

Direct: +49 2339 1209-10
***@***.***

<https://www.linkedin.com/in/>

[cid:horizontalasbytrajan_rgb_300dpi_01f7acdb-55a0-4d4c-8ed6-67c5cc602d87.png]<http://www.axelsemrau.com/>

www.axelsemrau.com<http://www.axelsemrau.com/>

Find out more about Trajan<https://www.trajanscimed.com/>

[https://assets.trajanscimed.com/email-v1/twitter_icon.png]<https://twitter.com/trajanscimed>  [https://assets.trajanscimed.com/email-v1/facebook_icon.png] <https://www.facebook.com/trajanscimed>   [https://assets.trajanscimed.com/email-v1/youtube_icon.png] <https://youtube.com/c/TrajanScientificandMedicalRingwood>   [https://assets.trajanscimed.com/email-v1/linkedin_icon.png] <https://www.linkedin.com/company/axel-semrau/>

Axel Semrau GmbH
Stefansbecke 42
45549 Sprockh?vel, Germany
Tel: +49 2339 12090

AG Essen HRB 15438, Sitz Sprockh?vel
Gesch?ftsf?hrer: Frank Sasse, Dr. Andreas Bruchmann

Note: Our email domain has changed from @axelsemrau.de to @trajanscimed.com (please add to safe senders list).
Von: Oleg Shilo ***@***.***>
Gesendet: Samstag, 20. Januar 2024 05:12
An: oleg-shilo/wixsharp ***@***.***>
Cc: Patrick Kursawe PhD. ***@***.***>; Comment ***@***.***>
Betreff: Re: [oleg-shilo/wixsharp] [Request] Cannot update to latest Caliburn.Micro (Issue #1387)


Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>


This is a very interesting problem caused by some peculiar behaviour of Nuget package manager.

The WixSharp VS template nominates the project dependency on WixSharp v2.0.0.0, which in turn depends on Caliburn.Micro v3.3. On build both these packages are installed and successfully embedded in the msi file, which behaves at runtime as expected.

However, when you go to the package manager and update WixSharp (e.g. to v2.0.4.0) it fails to update Caliburn packages. It's is not fully unexpected because the latest WixSharp package dependencies are require not updated. Thus the new WixSharp is still trying to build with the old Caliburn.

This can be easily addressed but updating the Caliburn package to the v4.* version manually. See the attached solution.
WixSharp Setup9.zip<https://github.com/oleg-shilo/wixsharp/files/13996633/WixSharp.Setup9.zip>

This will be fixed with the very next release by updating WixSharp metadata with the dependency on Caliburn v4 so no annual update is required.

However, what is really strange is that VS nuget manager does not prompt the user that there is an update for the Caliburn package as it normally does:

image.png (view on web)<https://github.com/oleg-shilo/wixsharp/assets/16729806/84856e3b-b8f1-40be-ab95-59cb011fa5f4>

________________________________

Until the fix is available, please update Caliburn manually.

-

**Comment by oleg-shilo** [comment]
This would explain

**Comment by BorderKeeper** [comment]
Thank you @oleg-shilo will check this soon, but looking at the fix it will fix our problem. Closing this down.
