### ISSUE TITLE
UIInitialized not working with EmbeddedUI

### ISSUE THREAD

**Issue by bh-ubunye** [oleg-shilo/wixsharp#1394]
Hi Team,

My current MSI installer using an embedded WPF UI, implementing the IEmbeddedUI interface, which, when the IEmbeddedUI.Initialize function returns, the msi is started automatically.

Could you please explain why using project.UIInitialized with EmbeddedUI is not working? I launched the installation, but it didn't trigger.

Should project.UIInitialized fail to function with embeddedUI, is there a feature that might accomplish the same task?

**Comment by oleg-shilo** [comment]
I just have tried and it seems that the event is fired as expected.
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/39870384-fdc3-4946-b2f0-27d1dea6ecae)

I have attached the sample project.
[WixSharp_Setup62.zip](https://github.com/oleg-shilo/wixsharp/files/13559759/WixSharp_Setup62.zip)

**Comment by bh-ubunye** [comment]
Hi Oleg, the ManagedUI is not being used in our project. Since we're using EmbeddedUI, this type of custom UI can't call UIInitialized, right?

`EmbeddedUI = new EmbeddedAssembly(typeof(MainWindow).Assembly.Location)`

If project.UIInitialized does not work with EmbeddedUI, is there a method that could do the same thing?

**Comment by oleg-shilo** [comment]
Correct. 
WixSharp own UI is implemented as `EmbeddedUI`. And because I have full control of it I simply invoke `UIInitialized` when my EmbeddedUI assembly is loaded by MSI runtime. 
Since third-party `EmbeddedUI` does not implement the same algorithm, the event is not fired.

**Comment by bh-ubunye** [comment]
So there is no other ways to call functions before `UIInitialized`? I need to check the Installer whether run elevated before UI display.

**Comment by oleg-shilo** [comment]
No, unfortunately none.

This is because MSI starts embedded UI before the actual msi session starts. Thus it is only that very same embedded UI whocan perform any user actions. 

Anyway, I want to ask you a question. Why do you need to do the evaluation check and why from UI?

The reasons for the question are simple: 
- MSI always run UI unelevated. 
- But it does elevate the actual MSI session. Just before it starts the installation. 

Thus it's certain, your user is not going to install anything unelewated.

If you still want to elevate your UI you can use an alternative approach. You can create an extremelly simple executable and embed your MSI in it as a resource and extract an launch the msi but only if it is elevated. Then it will show the EmbeddedUI as usual.

Have a look at the Self-executable_Msi sample.
And the whole solution will be as simple as below:

```C#
static public int Main(string[] args)
{
    // you can check if you are elevated here
    var msi = Path.GetTempFileName();
    try
    {
        File.WriteAllBytes(msi, Resources.ManagedSetup);
        string msi_args = args.Any() ? string.Join(" ", args) : "/i";

        var p = Process.Start("msiexec.exe", $"{msi_args} \"{msi}\"");
        p.WaitForExit();
        return p.ExitCode;
    }
    catch
    {
        // report the error
        return -1;
    }
    finally
    {
        try
        {
            if (File.Exists(msi))
                File.Delete(msi);
        }
        catch { }
    }
}
```

**Comment by oleg-shilo** [comment]
I have captured the essence of our discussion on the Tips'n'Trics page: https://github.com/oleg-shilo/wixsharp/wiki/Tips'n'Tricks#checking-prerequisite-conditions-as-soon-as-possible

**Comment by bh-ubunye** [comment]
I want to check the MSI run with elevated access if not then use the restart MSI logic to restart it with elevated privileges. 

I am currently facing the issue of inserting MSI registry keys into HKLM and HKCU roots due to administrator privileges.

**Comment by oleg-shilo** [comment]
> I am currently facing the issue of inserting MSI registry keys into HKLM and HKCU roots due to administrator privileges.

Then you can simply run the standard MSI and simply insert registry form the msi session which is always elevated. UI is not but msi session is.

Just subscribe to the `AfterInstall` event and you can do it with C#. Did you try that?
