### ISSUE TITLE
BootstrapperCustomBA WiX4 is not showing MSI package's UI

### ISSUE THREAD

**Issue by se** [oleg-shilo/wixsharp#1396]
This code is from the WixSharp's Wix4 template. We have tried to show this MSI package's UI but we couldn't make it happen. 

What could be the problem?

It seems it doesn't respect `DisplayInternalUI = true`.

Example project: https://github.com/se/wixsharp-wix4-bootstrap

We have tried many ways before post this, I'm sorry if we miss anything.

```csharp
using System;
using WixSharp;
using WixSharp.Bootstrapper;

namespace WixSharpSetupBootstrapperCustomBAWiX4
{
    internal class Program
    {
        static void Main()
        {
            string productMsi = BuildMsi();

            var bootstrapper =
                new Bundle("MyProduct",
                    new MsiPackage(productMsi)
                    {
                        Id = "MyProductPackageId",
                        DisplayInternalUI = true
                    });

            bootstrapper.Version = new Version("1.0.0.0");
            bootstrapper.UpgradeCode = new Guid("aeaffa48-66a6-4ee6-97a2-87746024e4f4");

            bootstrapper.Application = new ManagedBootstrapperApplication("%this%");

            bootstrapper.Build("MyProduct.exe");
        }

        static string BuildMsi()
        {
            var project = new Project("MyProduct",
                              new Dir(@"%ProgramFiles%\My Company\My Product",
                                  new File("Program.cs")));

            project.GUID = new Guid("bfd0f215-8e51-41ee-87d4-ce70f42968f8");

            return project.BuildMsi();
        }
    }
}
```

**Comment by oleg-shilo** [comment]
I tried the template and it seems to show the UI as expected:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/18727010-9600-4100-9723-880006be1163)

Please find the attached project sample
[WixSharp Setup6.zip](https://github.com/oleg-shilo/wixsharp/files/13632509/WixSharp.Setup6.zip)

Please note that the sample is just a standard project template without any changes to the code.

**Comment by oleg-shilo** [comment]
Done.

OK, I am not even sure it is a problem. But it is definitely something that needs to be reflected in the template content.

The template contains the code for BA app and showing MSI UI is kinda extra that's why I did not provide the code for displaying the UI and it creates the confusion. So first, let's fix your problem.

You can fix your project by adding this:

```c#
    public MainViewModel(ManagedBA bootstrapper)
    {
        this.IsBusy = false;
        . . .
        // code below will trigger displaying msi UI. Since you are using custom BA 
        // `MsiPackage.DisplayInternalUI` property has no impact and it is the BA who needs to trigget UI popup.
        this.Bootstrapper.PlanMsiPackage += (s, e) =>
        {
            if (e.PackageId == "MyProductPackageId")
                e.UiLevel = e.Action == ActionState.Uninstall ?
                                INSTALLUILEVEL.ProgressOnly :
                                    INSTALLUILEVEL.Full;
        };
``` 

All this is quite an unfortunate side effect of the WiX4 BA hosting architecture. Thus if one is using standard BA then WixSharp can detect `DisplayInternalUI` and inject a "magic" attribute (`bal:DisplayInternalUICondition="WixBundleAction = 6"`) into the bundle WXS definition.

But when user defines a custom BA the the BA must take care about msi UI and it needs to be done from that custom C# UI code. WixSharp can no longer help.

I simply will need to ensure that it is all very clear in the documentation and the template comment.
.

**Comment by se** [comment]
It works fine with this! Thank you so much (especially bringing this  project to the life!).

**Comment by oleg-shilo** [comment]
I have now updated the API documentation:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/c0c0c46f-767b-45b5-9e7b-8c734395e81d)

And the compiler will generate the error if DisplayInternalUI is used with custom BA:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/e284d2b7-8741-49c6-9f9a-8f75342fa1ce)

The change will be available in the very next release.

**Comment by oleg-shilo** [comment]
I have also reflected our discussion here: https://github.com/oleg-shilo/wixsharp/wiki/Tips'n'Tricks#showing-msi-internal-ui-from-bootstrapper-application
