### ISSUE TITLE
Strange path in InstallDirDialog (WPF)?

### ISSUE THREAD

**Issue by clawton** [oleg-shilo/wixsharp#1411]
Hi All,

I'm creating a WixSharp installer and I've set the main directory to:

```
 WixSharp.Dir mainDir = new WixSharp.Dir($@"%ProgramFiles%\{CompanyName}\{ProductName}",everythingToInstall);
```

When running the installer, it shows the following path:

![PathIssue](https://github.com/oleg-shilo/wixsharp/assets/4242667/1325de22-8132-4835-8a2e-5474d1050f88)

Any thoughts on why it shows "PFiles64" instead of "C:\Program Files"?

Using latest version (4.0.3) of Wix.
I've attached the main C# code for reference.
[Program.zip](https://github.com/oleg-shilo/wixsharp/files/13795693/Program.zip)

**Comment by Torchok19081986** [comment]
Morning, looks like Env Variable was set wrong. What happens if you use Environment Class from .NET ?

**Comment by oleg-shilo** [comment]
The problem is caused by the decision that WiX4 team has made. They have changed the name of the default Program Files directory variable in `Directory` table the generated msi file. This variable is never used by the user but only by custom UIs. 

WiX team, understandably, updated their UI implementation. But... sadly has failed to mention it in any WiX3 -> WiX4 migration guidance. :(

This issue was detected as a potential problem by one of the WiXSharp users when WiX4 was a beta, but it looks like it got in the released product.
I will fix this in the next release. For now please use this work around:

In the `InstallDirDialog_Load` do this:


```C#
        string GetProgramFiles64()
        {
            var pf64_from_32bit_process = Environment.GetEnvironmentVariable("ProgramW6432");
            if (pf64_from_32bit_process.IsEmpty()) // old version of Win
                pf64_from_32bit_process = Environment.SpecialFolder.ProgramFiles.GetPath();
            return pf64_from_32bit_process;
        }
. . .
 installDir.Text = installDir.Text
                    .Replace("PFiles64", GetProgramFiles64())
                    .Replace("PFiles", Environment.SpecialFolder.ProgramFilesX86.GetPath());
```

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/fafcea11-6293-4b48-a4ec-bad857e48561)

**Comment by clawton** [comment]
Thanks!  Is there an ETA on the next release?

**Comment by clawton** [comment]
Just went to look at this in my code.  Just an FYI for anyone else who might be reading this, ( @oleg-shilo ), the solution provided works but the instructions are for the WinForms based installer.  Mine was using the WPF version so the solution goes into the View Model for the InstallDirDialog.

**Comment by oleg-shilo** [comment]
>Is there an ETA on the next release?

I will be back on this on 3-rd week of Jan. So within ~2 weeks.
