### ISSUE TITLE
Question How to deal with Bootstrapper in Wix V4.

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1467]
Morning,  i have following scenario and currently dont know if possible to do so. I have package where Dependecies are not msi , exe installer from 3. party manufacturer , two of them. bootstrapper doesnt have Depencies of exe, only MSIPackge as class to add msi to Bootstrapper Package. 
Problem is , i cant extract msi from another exe installer.  Both of them has to execute BEFORE my installer starts to installer software. Is this scenario somehow possible and there is exmaple for something like this ? 

Many thanks for advices.

**Comment by oleg-shilo** [comment]
There is `ExePackage` class for that:

```c#
var bootstrapper = new Bundle("My Product",
                       new ExePackage(...

```
See `WixBootstrapper` sample:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/066c7e2b-4077-4f9a-90e7-59fea0151617)

**Comment by Torchok19081986** [comment]
many thanks, oleg. I going to investigate it. I do not understand only thing , how to add or execute this packages BEFORE main setup / installer and how to reflect it back as resultcode if insallation failed or not.

**Comment by oleg-shilo** [comment]
You will need to look at the sample.
The order of execution of the included packages is the same as they are added to the project.
And the communication between packages can be done in this case based on the presence of some reg keys or files. This can be tested in the following msi OnLoad event. This is my preferred way.
Quite possibly there is a more orthodox way of doing that. You will need to check WiX forums for that.

**Comment by Torchok19081986** [comment]
morning, some feedback here. I was able, kind of 😉, to do so. I done just like your suggeston, get values in registry for each exe installer and if some exists then do something. Am i right, that msi session is  pointing to currently installation : CA with Session are only for current installation process ? 
There is no Interface or some supirior Instance over there, also right ? I question it , cause i was not able to reflect msi exitcode from one installation to another , to start or cancel it.

**Comment by oleg-shilo** [comment]
>  CA with Session are only for current installation process ?

Yes install session life cycle is bound by the process `msiexec <your msi>`. There are even more constrains., Each CA is an individual process `rundll32.exe <your CA dll>` and a serializable instance session (a property bag) is the only thing that keeps these CA together. 
This concept was introduced ~25 years ago and at that time was arguably acceptable. But today....

> There is no Interface or some supirior Instance over there, also right

There is but very limited. It is the instance if your Bundle (bootstrapper) it can push bundle variables into your MSI as session properties. But updating variable from msi is not possible. 

> current installation at end msi exitcode from one installation to another , to start or cancel it.

It should be relatively easy. If you install product A and B and they go to `%PROGRAMFILES%\A` and `%PROGRAMFILES%\B`

Then as a launch condition for the product B you should simply check the existence of `%PROGRAMFILES%\B`. If it does not exist (doesn't matter why) then stop the installation and let user know that you are aborting the install because product A was bot installed.

**Comment by Torchok19081986** [comment]
Many thanks for quick answer, @oleg-shilo. Then is it up to me to find right solution for this purpose.  I have to add only launch condition to bootstrapper itself and debug some output. It best way to this, without looking deeper in msi or wix toolset v4. 
😉😉😉.
