### ISSUE TITLE
MSI wildcard resolution error

### ISSUE THREAD

**Issue by vincho1** [oleg-shilo/wixsharp#1478]
The msi format has a list of wildcards that can be used to target a specific folder inside the computer. For instance, `%Desktop%` can be used to target the desktop folder of the user executing the .msi

However, there is a bug with the wildcard `%PersonalFolder%`. While the .msi is executed, the wildcard `%PersonalFolder%` should  be converted into an absolute path to "Documents" folder of the user executing the msi.
- If user Gabriel is executing the msi, the `%PersonalFolder%` should be converted to `"C:\Users\Gabriel\Documents\"`

When I install the .msi, the wildcard `%PersonalFolder%` is converted into  **`"C:\PersonalFolder\"`** and not into `"C:\Users\[current user]\Documents\"`

**Notes:**
1. A list of all msi wildcards can be obtained by: `Compiler.GetMappedWixConstants(true).ForEach(Console.WriteLine);`
2. Wildcard issue confirmed by msi dump: `msiexec.exe /i installKit.msi /L*vx! dump.log`

WixSharp.wix.bin v.3.14.0.1
WixSharp.bin v.1.25.2
WixSharpv.1.25.2
Using dotNET 4.6.2

**Comment by Torchok19081986** [comment]
Morning, are you sure there exists EnviromentVariable %PersonalFolder% ? AFAIK there is only %username% which resolved in curent username. If so you have to add %username% to your msi .  EnviromentVariables for personal Document is 
```csharp
Environment.SpecialFolder.MyDocuments

```
best regards, Torchok.

**Comment by oleg-shilo** [comment]
It looks like a WiX issue.
WixSharp simply converts C# `%PersonalFolder%` expression into a WiX `PersonalFilder` Directory Id:

```c#
new Dir(@"%PersonalFolder%\\My Product",    
    new File(@"setup.cs"))
```
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/d2bd74f4-6ca6-42d9-9603-b9c53e262925)

And it does it correctly, as you can see it from this WiX spec for built-in constants: https://wixtoolset.org/docs/v3/bundle/bundle_built_in_variables/

So why it is not deploying in the correct destination is something that is can only be discovered on the WiX side.

Unless.... the WiX XML is not generated correctly because of some WixSharp deficiency. Can you check your WXS file?
