### ISSUE TITLE
External Install software

### ISSUE THREAD

**Issue by rdt23** [oleg-shilo/wixsharp#15]
hi

i have an installer  that i wrote  with custom ui (winform base)
i want to add to it an sqlexpress and .net(if needed)
i tryied to run it from the installer , but i cant run 2 windows installer at the same time
i tryied to do it with bootsrap but it doesnt show my ui (at least i didnt succeed to do it)
i saw your WixBootstrapper UI example but as i understand i require a big change

what is the easiest  way to do it

**Comment by oleg-shilo** [comment]
Hi there,
It looks like you've already done some good matter investigation. 

The bootstrapper would be the most logical choice in your case. However as you correctly identified it has a problem. Because of the WiX/Burn bug the external UI cannot be displayed at runtime. The defect is acknowledged by WiX team (https://github.com/wixtoolset/issues/issues/4921/) and they plan to fix it for the v4.x. But until then I am afraid you cannot use this approach.

The only option you have is a hybrid bootstrapper. You can have all your setups (your primary and conditional SQLExpress) run without UI. But you can have the major UI implemented as a Bootstrapper BA (WixBootstrapper_UI).

Yes it does require the changes but it's not necessarily complicated. Follow the sample from the Wix# samples dir and keep it simple. The only thing that you need to do from your UI is to analyse the environment, make certain business decisions and interact with the user. Store the results of these actions in the MSI properties and make these properties into MSI conditions of your setups.

The Wix# samples should be a good starting point.

**Comment by rdt23** [comment]
thanks im going to try that
