### ISSUE TITLE
UAC prompt appears minimized in TaskBar

### ISSUE THREAD

**Issue by jimfoye** [oleg-shilo/wixsharp#151]
I'm using ManagedUI, and testing with UAC setting at max. When I launch the MSI I go through the UI and then when I start the installation, I get the UAC confirmation prompt, as expected. However, the prompt appears as a flashing button in the taskbar, and I have to click on that button to see it. Obviously this is not ideal (though I assume at this point in the history of Windows, most users will probably figure out what is going on and click on the button).

I did some searching, and found this on Stack Overflow:

[https://superuser.com/a/89026](url)

The answer says "Some products are badly programmed", I certainly don't mean to imply that WixSharp is badly programmed (lol). Then it says

> so although their window is the current focus, they don't pass that window's handle for UAC to use. In that case, UAC will not put its dialog in front, but will rather signal its presence thru the taskbar.

I'm not sure what he means by "pass that window's handle for UAC", but is there possibly a way for WixSharp to do exactly that so that the UAC prompt will appear properly and not minimized?

**Comment by oleg-shilo** [comment]
Yeah, I noticed that too. It is indeed annoying. I thought that it's one of those things that cannot be addressed but can be lived with. Glad to see that there is something that theoretically can fix this behavior. 

Though, the problem is that it is not the Wix# runtime who triggers the UAC prompt but the MSI one. WiX also has nothing to do with this (at least I don't see how it can). 

> If a program other than the foreground program requests elevation, instead of interrupting your work (the foreground task) with a UAC dialog box prompt, UAC signals its request with a flashing taskbar button. Click the taskbar button to see the UAC prompt.


This is exactly the problem. The process that pops up the EmbeddedUI is msiexec.exe, which isn't a background process but a service. MSI is taking triggering the UIC prompt and it supposed to somehow "pass that window's handle". It does this for its own UI but not for the external one.  

I am marking this a feature request as may be there is a way for any routine to register itself with UAC prior the prompt. Will need to do some reading...

**Comment by oleg-shilo** [comment]
Yes found it: https://msdn.microsoft.com/en-us/library/bb756922.aspx

> However, some foreground applications currently prompt as background applications on Windows Vista. This behavior is the result of an absent parent HWND. In order to ensure that Windows Vista acknowledges your application as a foreground application, you must pass a parent HWND with a ShellExecute, CoCreateInstanceAsAdmin, or managed code call.

It is MSI who calls `ShellExecute`. Maning that neither WiX nor Wix# can change it :(

**Comment by monty241** [comment]
Problem also appears on Windows 7 x86. But also with traditional WIX installer, not WIX#. On Windows 10 it works fine.

**Comment by oleg-shilo** [comment]
Yes, and also with the official EmbeddedUI sample for WiX. All these problems are caused by a mistake in the MSI implementation thus it will affect everything. I even found InstallShield error report about this and (of course) no solution.

Though I just finished testing an aggressive but very simple trick that seems to fool the OS window manager and trigger the desired behavior.  Thus the work around is on the way. Unless some other problems discovered :)

**Comment by monty241** [comment]
Tested on last release. In WXS:

    <Property Id="UAC_REVEALER_ENABLED" Value="true" />

On Windows 7, but does not pop-up:

![image](https://user-images.githubusercontent.com/7579444/30590544-51651956-9d3f-11e7-8c13-8dfb45021413.png)

**Comment by oleg-shilo** [comment]
As I mentioned the problem cannot be solved form Wix# but needs to be addressed in MSI. 

The f302112 delivers what I called an "aggressive but very simple trick", which is a weak work around but not a reliable solution to the problem. Thus I am not surprised to hear that it can fail.

The trick itself is dead simple. Before triggering elevation, Wix# runtime tries to shift the focus from the setup UI window to the desktop app window. In result. UAC is fooled an pops up the prompt. Though I was able to defeat the work around every time by forcefully setting the focus back to the setup UI Window by a mouse click.

It looks like in your case the work around is defeated the same way. Your screenshot clearly indicates that your setup window **does** have focus.

Can you please do a simple test to verify that my interpretation of your test is correct.

Have a fresh instance of notepad window positioned next to your setup window. 
Just after clicking the "next" button (the one that triggers elevation) immediately click the notepad window. This would be the same f302112 trick but performed manually. It works on Win10 but let's see if it does on Win7.

**Comment by monty241** [comment]
Tried it, but still doesn't seem to do the trick on Win7. Well, good argument to start thinking about desupporting it :-)

![image](https://user-images.githubusercontent.com/7579444/30615918-c0d08928-9d90-11e7-91f3-f798ba731a6a.png)

**Comment by oleg-shilo** [comment]
Well, indeed not much we can do...
I'll keep it. It's simple and safe. And it works at least in some cases. Fortunately severity of the problem is not so high - just inconvenience. 

But II am glad this issue has been raised. At least we now have a good understanding of what is causing this problem.

I am closing this issue until something new comes into orbit.

**Comment by oleg-shilo** [comment]
There have been a new development in this direction triggered by #301 

An improved algorithm for this nasty MSI/UAC defect has been implemented (https://github.com/oleg-shilo/wixsharp/releases/tag/v1.6.3.0-HotFix).

It's now released as as a HotFix release. NuGet per-release packages are also published.
