### ISSUE TITLE
[INSTALLDIR] subdirectories question

### ISSUE THREAD

**Issue by T1-Frank** [oleg-shilo/wixsharp#1510]
I have an installer project that has 2 different exe files. each exe is in its own subdirectory.

when creating a shortcut with new ExeFileShortcut("MyApp", "[INSTALLDIR]MyApp.exe", arguments: "")

is there a way to reference a subdirectory in the install directory? I have tried using variations of [INSTALLDIR]Folder/MyApp.exe but this throws an error during building. 

I can create working shortcuts using FileShortcut but I cant add conditions to those due to Wix not supporting that. 

Any help would be appreciated.

**Comment by Torchok19081986** [comment]
Morning, questions over questions. Which version do use for creating your installer ? Wix v4 or v3 and Wix# Version ? 
In stackoverflow in link https://stackoverflow.com/questions/73199492/how-to-install-into-a-sub-folder-using-wix-3-11 , suggest create each Id and nested Installdir as Path. Only Oleg can say if this approach can be successfull. I dont know what happens if you add custom Id to your Installer also for Installdir. you can try it self. Create Test project and add for each Dir new Id("CustomDir1") and so an. See output and try installer. If nothing works, only way remains is BA installer , wtih 2 msi installer as payload. Start installer first install into  own installdir and second same. Little complicated, but there is no another way, im afraid .

**Comment by oleg-shilo** [comment]
You can reference installdir-based files in the `ExeFileShortcut`. The example in this repo demonstrates exactly that. The algorithm is how @Torchok19081986  suggested, you need tp provide the id of the directory not the composite path (id + subdir) but the id.
I just modified the Sortcuts-2 sample to follow your scenario. and it builds fine: 

In C#:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/b6aeb055-41ed-41e7-aa6b-ba38202e0c27)

and the XML:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/9054dba8-a139-47c5-be4e-65b183e959ea)

If you want more control over the id value then you can specify it in the dir constructor:

```c#
new Dir(new Id("my_src_id"), "src", ...
```
