### ISSUE TITLE
Externl Ui and Silent intallation

### ISSUE THREAD

**Issue by Diddlik** [oleg-shilo/wixsharp#1512]
I have built an external UI for the installer and this starts the msi installer under the hood. Everything works fine. But what I can't manage is the possibility to build silent isntaller with external ui.

I.e. I start e.g. myinstaller.exe --mode:silent --path: "c:\data\mayapp" and it is installed in the background in my path, if you start it without parameters, it runs as usual via gui

I read this topic (https://github.com/oleg-shilo/wixsharp/issues/594) but direct usage off parameters starts ui nevertheless

**Comment by oleg-shilo** [comment]
you can always start your msi with the dedicated launcher `msiexec.exe`

It has a special command line arg for starting it without UI.
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/71341049-c2d7-4714-8434-135c01304758)

**Comment by Diddlik** [comment]
Or wait, do you mean in this part of code?

I catch the command line and start msiexec as a process with needed parameters?

private void Application_Startup(object sender, StartupEventArgs e)
{
    splashscreen = new SplashScreen();
    splashscreen.Show();
    App.DoEvents();

    byte[] msiData = DGO.Installer.Properties.Resources.Deloitte_Grouping_Optimizer;
    MsiFile = Path.Combine(Path.GetTempPath(), "myApp.msi");

    if (!File.Exists(MsiFile) || new FileInfo(MsiFile).Length != msiData.Length)
        File.WriteAllBytes(MsiFile, msiData);

    AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
}

**Comment by oleg-shilo** [comment]
Pavel, you are loosing me :)

You are asking me about the project you have implemented. I have no idea what you are dealing with. The only description you gave me is "I have built an external UI for the installer and this starts the msi installer under the hood".

What exactly are you building?

**Comment by oleg-shilo** [comment]
Great. Then we are talking about the `<Wix# Samples>\External_UI\WpfSetup` based project.

In this sample the click on 'install' button triggers the `base.StartInstall` of the `MyProductSetup` class.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/ca4b3db6-b193-4805-b23e-1d6d52faced4)

Since the base class `StartInstall` does not do the job you need, you need to provide your own alternative implementation:

```C#

public class MyProductSetup : GenericSetup
{
. . .
    public override void StartInstall(string msiParams = null)
    {
        if (!IsCurrentlyInstalled)
        {
            // Experiment in the command prompt to find the required params
            Process.Start("msiexec.exe", $" /i \"{MsiFile}\" /qn {msiParams}");
                                
            LogFileCreated = true;
            IsRunning = true;
        }
        else
        {
            ErrorStatus = "Product is already installed";
        }
    }
```

However, if you do not need MSI default UI, why don't you just switch it all completely when you build your msi?

```C#
project.UI = WUI.WixUI_ProgressOnly;
```
Then you don't need to do anything in your WPF UI at all. as MSI will only have UI that is a tiny progress dialog. 
It's just an option for you to consider...

**Comment by Diddlik** [comment]
My idea was to have both, UI installer and silent mode for automatic deployment.
Since I don't need MSI GUI, I would make it leaner with your template. I'll try with StartInstall function.

Thanks for the tips!
