### ISSUE TITLE
WixSharp NET Core UI Project

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1523]
Morning, thanks for create MSI for NET core possibility. I just tested it. Works. Buildtime is much, much longer than normal. 
There is limitations of building MSI with this, right? There is some quesions here 
how should project for UI be look ? Cant we just add WixSharp Dialogs Library for standard dialogs to it and build it ?
According to info, i can use .NET Framework for UI, but do i have to set it in NET Core MSI building as <TargetFrameworks> .NET Framework; NET8.0-x64windows</>  in .sln File ?
Custom Action are not possbile, because it not supported directly by wix toolset self. How to use here AddActions Methods ? Example ? 
Many Thanks, @oleg-shilo , again for answers.

**Comment by oleg-shilo** [comment]
Yes it is because of AOT compilation that is heavier than IL one.

Though it's not that bad. Around 15 seconds for me. But it can easily jump to ~40 seconds if I use any WinForm stuff in the custom action.

Note, bilding MSI with .NET Core gives you absolute zero advantage. It was simply done because of the user requests but not because of the necessity.

As for UI indeed there is a sample project of that exact configuration that you described. 

See this [sample](https://github.com/oleg-shilo/wixsharp/tree/wix-v4-master/Source/src/NET-Core/Sample/CustomUI-WinForms)

**Comment by Torchok19081986** [comment]
morning, many thanks again. :-), @oleg-shilo.  Last question here, after this, close issue pls. Just to understand : BA Installer can be created in V4 as NET Core Family and it has endless bug with display internal UI not anymore, but MSI that runs , not really can be build like "normaly" MSI with CA´s, because lack of support from WixToolset. Sofar understandable. BUT How to build then BA Installer if msi has another type of NET Framework ? AFAIK this cant be done, right ? I think, only time will show, maybe breaking changes in v5,  if MSI will be supported in future. Maybe internal move from MSI to MSIX, which should happens from WixTeam self. I give up on this, too many problem, that i currently cant solve. BA and MSI will remain .NET Framework 4.8.
