### ISSUE TITLE
If you enter the project name in Chinese, a question mark is displayed on the installation package

### ISSUE THREAD

**Issue by JusterWork** [oleg-shilo/wixsharp#1527]
` var project =
        new ManagedProject("你好",
            new Dir(@"%ProgramFiles%\My Product",
            new WixSharp.File(@"myapp.exe",
            new FileShortcut("My App", "INSTALLDIR") { Advertise = true })));`

"你好" The installation package is displayed as a question mark

The version of the framework I use is WixSharp-wix4.WPF 2.1.2

**Comment by lvsheng2022** [comment]
me too...(T_T)

**Comment by JusterWork** [comment]
help me

**Comment by oleg-shilo** [comment]
Hm, I cannot even build it:

```C#
 var project =
            new ManagedProject("你好",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new Dir("SubDirA",
                        new File(@"Files\Bin\MyApp.exe")),
                    new Dir("SubDirB",
                        new File(@"Files\Bin\MyApp.cs"))));

        // project.Codepage = "UTF-8";
        project.ManagedUI = ManagedUI.Default;
        project.OutFileName = "setup";
        project.BuildMsi();
```
It produces: 

```
D:\dev\wixsharp-wix4\Source\src\WixSharp.Samples\Wix# Samples\Install Files\setup.wxs(2): error WIX0311: A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Package/@Codepage, Module/@Codepage, Patch/@Codepage, or WixLocalization/@Codepage.
```

TBH I do not know how WiX is handling Chinise language. What code page it is su[opposed to be.

**Comment by JusterWork** [comment]
1. Building is actually very simple, open any demo you provide in the open source project sample,  Then pass the first name parameter of ManagedProject “你好” ， new ManagedProject("你好", x,x,)

2. With Pagecode I tried 936 and 65001
 https://learn.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

**Comment by oleg-shilo** [comment]
> 1. Building is actually very simple,....

It must be because you are building it on the simplified-Chinese ready OS. What I posted there is a default English-Wn11.

But... since you actually can build it, try to play with the language tag `project.Language = CultureInfo.GetCultureInfo(1041).IetfLanguageTag;` as well. Maybe it will give you something.

You see, WixSharp does not deal with encoding. It simply uses WiX localization mechanism, which as far as I understand has only two attributes to play with:   `project.Codepage` and `project.Language`. 

You may want to search on WiX forums too. There is a chance you can find something.... I doubt you are the first person to have this problem.

**Comment by JusterWork** [comment]
Thank you very much for your answer, I will try again. Right, I can't find a solution on the Internet that has the same problem as me.
