### ISSUE TITLE
Does Wixsharp support dacpac deployment in SQL server?

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1556]
Hi @oleg-shilo 
Does Wixsharp support dacpac deployment in SQL server? If yes, can you please provide any sample code?
Standard samples solution does not dacpac approach. It runs a sql script there.

**Comment by oleg-shilo** [comment]
Sorry, no. 
WixSharp is not an installer as such. It is a tool (an orchestrator of WiX build process) to build MSI setup files.
Thus since MSI and dacpac have nothing in common, I do not see a direct use case for WixSharp in your scenario.

Though, of course, you can build msi distributing dacpac file and at the end of the installation you can deploy it using sqlpackage.

But I am not sure it is what you need.

**Comment by abskulkarni** [comment]
Thanks @oleg-shilo . I will go by route where I will put dacpac file on disk through MSI and then run it later.
