### ISSUE TITLE
Dynamic localization via custom dialog

### ISSUE THREAD

**Issue by kipamgs** [oleg-shilo/wixsharp#1564]
Hi, 
I added a combobox to the welcome dialog so the user can choose the language of the installer.
I tried doing it in a similar way to the [MultiLanguagesUI Example](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/MultiLanguageUI) .

I would like to switch the languages if a user chooses another language of the combobox. The ideal way would be to load the localized strings in the ComboBox_SelectionChanged method.

Once I selected another language via  `runtime.UIText.InitFromWxl `how can I switch back to english?

![image](https://github.com/oleg-shilo/wixsharp/assets/110532150/0b5d217f-3a29-4bfa-8487-3b75ae2f9830)

```
        private void ComboBox_SelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
        {

            try
            {
             var runtime = Host?.Shell.MsiRuntime(); // Host?.MsiRuntime();
             switch((SupportedLanguages) LanguageCombobox.SelectedIndex)
             {
                 case SupportedLanguages.German:
                     runtime.UIText.InitFromWxl(Host?.Session().ReadBinary("de_xsl"));
                     break;
                 case SupportedLanguages.English:
                     // How can i switch back to english?
                     break;
             }
            }
            catch (System.Exception ex) {
                MessageBox.Show(ex.Message);
            }
        }
```

**Comment by oleg-shilo** [comment]
Sorry for the delayed response. 

The English localization is stored in the same table where other localizations are, though under the `WixSharp_UIText` key.
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/e0be60c5-b2ae-46eb-b094-874a0cd7abac)

The English localization is always stored there regardless if you embed other languages or not.

At runtime you need to update the localization between dialogs. You do this by subscribing to the UI events that are triggered on the dialog change. Since you want to re-localize the second dialog then you need to do that right in the UILoaded event handler:

```c#
project.UILoaded += (SetupEventArgs e) =>
        {
            // first dialog is loaded
            MsiRuntime runtime = e.ManagedUI.Shell.MsiRuntime();
            runtime.UIText.InitFromWxl(e.Session.ReadBinary("WixSharp_UIText"));

            e.ManagedUI.OnCurrentDialogChanged += (IManagedDialog obj) =>
            {
                // any dialog after the first one is loaded
                // you can also check the dialog type here
            };
        };
```

**Comment by kipamgs** [comment]
Thank you
