### ISSUE TITLE
Overview of which SetupEventHandler is fired on which type of project

### ISSUE THREAD

**Issue by blutswende** [oleg-shilo/wixsharp#1592]
Hi,

i have problems to get the right SetupEventHandler (Load, BeforeInstall, ...) to get fired with my ManagedProject with Managed UI.

Is there a overview which SetupEventHandler is fired with which type of Project (ManagedProject, ...) , Bootstrapper ... with CustomUI ?

I need this to read registry values to show them in my CustomUI before it is displayed. support for silent and UI installation.
Is there a best practice, i could not find anything the sample solution ?

`var project = new ManagedProject(productName, ...);`
`project.ManagedUI = new ManagedUI();`
`project.Load += Load;`
`project.BeforeInstall += BeforeInstall;`
`project.AfterInstall += AfterInstall;`

regards
Florian

**Comment by oleg-shilo** [comment]
Hi Florian,

You can find the overview of the managed events here:
https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#event-driven-custom-actions

Events are nothing else but custom actions that are defined with C# CLR event syntax.

```
Load          -> When.Before, Step.AppSearch, Execute.Immediate
BeforeInstall -> When.Before, Step.InstallFiles, Execute.Immediate
AfterInstall  -> When.After,  Step.InstallFiles, Execute.Deferred
```

Thus events are part of an msi and fired during the msi setup.
You can only define events for the `ManagedProject` because it is the only project that is capable of building managed Custom Actions.

These three events are fired always. Regardless of the installation type.
Though there are two additional UI events `UIInitialized` and `UILoaded` they are fired only if you have ManagedUI (not native).

The section that I gave you the link has a reasonable overview of the events. The diagram there is particularly important as it shows when the events are fired.

**Comment by blutswende** [comment]
Thanks, that is what i was searching.
