### ISSUE TITLE
Reg. Value Compare with NSIS BootStrapper

### ISSUE THREAD

**Issue by ravi2004** [oleg-shilo/wixsharp#1600]
Hi oleg-shilo,

I am new user of wixsharp. Thank for this amazing product. I am facing issue to compare Registry Value . I want to trigger .Net Framework 4.7.2 installation if it is not available on user machine. I am using the given below Registry key for the same . But whenever we are running setup it is triggering the .Net Setup installation . I want to check if .Net Version 4.7.2 or latest version available on target or not . if Not only that time it will start .Net frame workinstallation.

PrerequisiteRegKeyValue = @"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full,Version=v4.7.2:",
I tried with given below values as well.
PrerequisiteRegKeyValue = @"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\Version:4.7.2",
and 
PrerequisiteRegKeyValue = @"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full:Version=4.7.2",

But no success. looking for your support

**Comment by oleg-shilo** [comment]
I assume you are using `NsisBootstrapper`.
If this is the case then your first sample seems to be a correct one.

Interestingly enough @geghamyan (the author of NSIS integration who takes the whole credit) used a different path to check the version in the code sample:
```C#
setup.PrerequisiteRegKeyValue = @"HKLM:SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework,Version=v4.5:";
```
MAybe it is a clue...

Another question. When you say "But no success." what exactly do you mean?. What is the behaviour?

**Comment by ravi2004** [comment]
Hi oleg-shilo, 

Thank for your reply.

Yes, I am using the NsisBootstrapper.

When I am using the given below Key value
PrerequisiteRegKeyValue = @"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full,Version=v4.7.2:",

The setup is not taking the action as per expectation. For example, If target machine already has Net Framework 4.7.2, that time, setup must bypass Framework installation. But it is always running the Net Framework Installation so looks like it is ignoring the PrerequisiteRegKeyValue. 

As per my expectation, if the target VM already have Net Framework 4.7.2,  or later release for the same that time Setup will directly execute the primary action. 

Please also check given below attached screenshot from macro.nsh file.
As per my understanding, the defined macro is just for reading the registry value without any logical check for registry Value.

Please advise of we can add or customize macro for his.


![image](https://github.com/user-attachments/assets/0091154d-932b-4ab4-b7c9-f5c026ec5a4f)

**Comment by oleg-shilo** [comment]
Sorry, I do not know NSIS script syntax so I cannot be very helpful with your question. Though...

>  just for reading the registry value without any logical check for registry Value.

While indeed it looks like that, the push/pop statements at the start and end of the script may indicate some sort of a stack that the ReadRegStr is placing the values into. Thus the whole script can be a method that checks the registry and returns the result via such stack to be later used as a condition for the installation of a bundle item.

But unfortunately, you only can discover that by analyzing the NSIS documentation.

I have another simple suggestion though. Why don't you use the very same reg path that is in the `DotNETBootstrapper.cs` sample? Then you can manually create/update this reg key (if it's not there) and see if it changes the behaviour. I suggest this simply because this sample has a strong chance of working as expected as it was contributed a long time ago and there were no defect reports against it. I simply speculate that somehow the registry path/value that you are using is not read correctly.
