### ISSUE TITLE
Snoop support

### ISSUE THREAD

**Issue by Barrent** [oleg-shilo/wixsharp#1605]
Hi,

Is there any way to attach [Snoop](https://github.com/snoopwpf/snoopwpf) to an installer created with wixsharp? If I run an installer as is, launch snoop and open list of processes via snoop UI to attach, there is no installer listed.

**Comment by oleg-shilo** [comment]
If you are running WPF UI with your msi then yes you can attach Snoop. If WinForms, then of course no. 

The trick is to find the right process to attach to. MSI does not make it easy. It runs every _custom action_ as a separate process. And your debuger (Snoop) also needs to be elevated.

Have a look at this article for details: https://github.com/oleg-shilo/wixsharp/wiki/Tips'n'Tricks#debugging

I cannot be sure but you might be even better off just debugging your UI instead of snooping.

**Comment by oleg-shilo** [comment]
It means that VS WPF visualizer cannot handle/reconstruct a visual tree for WPF runtime hosted in MSI process. 
May be because the process is elevated, or maybe because it's parent is a system service (msi service).

You may still try to attach snoop because you know for sure which process is hosting your WPF runtime. But the chances are that it will have the same difficulties as VS debugger. :(
