### ISSUE TITLE
Use LocalSystem for Windows Service.

### ISSUE THREAD

**Issue by lazyita** [oleg-shilo/wixsharp#1616]
Hello I'm trying WIX sample WinService/Wix_InstrallUtil to install service. When i run the .msi, it prompts for Set Service login. How do I manage to install service with LocalSystem? and Is there a way to provide username and password for service account

**Comment by oleg-shilo** [comment]
I cannot comment on WiX samples.
But with WixSharp you can use `CommonTasks.InstallService(string serviceFile, bool isInstalling, string username, string password)`

**Comment by lazyita** [comment]
Thanks. This indeed works for service account but LocalSystem it is still failing.

**Comment by oleg-shilo** [comment]
Then it is a limitation of the `InstallUtil.exe`. You can search its documentation.

Though, there is a chance that when WixSharp invokes it the CLI command is somehow invalid. If you can find the correct command that installs the service then you can invoke it from the AfterInstall event by yourself. Also, let me know and if it is indeed a bug then I will fix it.

BTW, is it possible that the problem is caused by you not being elevated?

**Comment by lazyita** [comment]
Hi Oleg, thanks for the response.
Yes I did elevated and it is working fine with username and password. If no arguments are passed then the msi prompts for the credentials. There's one way to get it done is install it as service account and then use sc command to switch it to LocalSystem.

The WixSharp invoke command seems to be correct and I do not think it needs any changes.

I managed to fix my issue by using ServiceInstaller approach.
