### ISSUE TITLE
Answer NO on "Do you want to restart now?" causes server restart.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#178]
When the software being replaced is in use, you get the following picture at the end of the installation:

_In order to complete the installation of ..., you must restart the computer. Other users are currently logged on to this computer, and restarting may cause them to lose their work. Do you want to restart now?_

When you answer NO, the computer nonetheless restarts fully.

Saw it on several OS versions.

Expectation: only restart directly when you choose "YES".

![image](https://user-images.githubusercontent.com/7579444/31127453-43ca5480-a84f-11e7-8223-79ee6e667d04.png)

**Comment by oleg-shilo** [comment]
MSI is extremely difficult to deal with when it comes to rebooting. Even the fact that MSI has property `REBOOT` with the possible values _Suppress_ and _ReallySupress_ already tells you that something is not as simple as we all want it to be. :)

Wix# is not involved in rebooting in any way. The message box is popped up by MSI runtime and Wix# has no control on if and how rebooting is performed.  Though you may have a look at the Reboot sample as it shows how rebooting manually and what is the API for accessing MSI reboot scheduling.

**Comment by monty241** [comment]
Hi Oleg, thanks. I am especially concerned since it reboots despite giving a "NO" answer. That confuses the user. For our installers, a reboot is only necessary when a file is locked during replacing.

I've checked the wxs file, the MSI with MSI analyzer and the WIX# source, but the result "reboot" upon answer "NO" seems to be determined elsewhere out of control from WIX#.

**Comment by emmoemminghaus** [comment]
Is there a Solution because "uncontrolled rebooting" a server with important services always isn't a good idea.

**Comment by oleg-shilo** [comment]
I don't have the answer you are looking for but I have been facing this very problem way too often.

My solution is outside of deployment as such. I move this to the initialization/configuration domain. It is more suitable for the task.

Thus I have released quite a few CS-Script plugins for popular editors. All of them have Roslyn as an engine.  A nasty creature when it comes to deployment. MS realized that it is extremely heavy to load and decided to cheat. Instead of exiting after the job done the C# compiled sits in the memory waiting for new compiling jobs. Making it impossible to replace on plugin update.

My solution was to pack Roslyn along with the plugin but... at plugin startup create a `%APPDATA%/CS-Script/NppPlLugin/version/RoslynBinaries` dir if it does not exist and copy Roslyn binaries to it.  This warrantees that the new copy of binaries will always go to the freshly created empty folder. 

After that I always (from every session) check in background if there are any `version/RoslynBinaries` of the lover version than the current. If there is, try to delete it. Even if it fails (e.g. old compiler is still active) eventually (e.g. after reboot) the old folder is purged.

I just feel that it is too cruel to ask user to reboot editor (I am not even talking about rebooting OS).
