### ISSUE TITLE
INSTALLDIR with russian symbols

### ISSUE THREAD

**Issue by F1nZeR** [oleg-shilo/wixsharp#185]
All russian symbols are replaced with a "?".
Any workaround?

**Comment by oleg-shilo** [comment]
The problem is caused by the default encoding on your environment (and mine btw).
You can easily fix it as this:
``` C#
project.Encoding = Encoding.UTF8;
```
Though your report has prompted me to reconsider then default value of the `project.Encoding`, which is currently `System.Text.Encoding.Default`. Thus I decided to change it to UTF8.

Marking the issue as enhancement.

Thank you.
