### ISSUE TITLE
WixQuietExecAction and deferred

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#206]
WixQuietExecCmdLine does not work if Execute is set deferred.
```
new WixQuietExecAction("notepad.exe", @"C:\boot.ini")
{
   Step = Step.CreateFolders,
   When = When.After,
   Execute = Execute.deferred,
}
```
In the logs there are such errors:
```
WixQuietExec:  Error 0x80070057: Failed to get command line data
WixQuietExec:  Error 0x80070057: Failed to get Command Line
WixQuietExec:  Error 0x80070057: Failed in ExecCommon method
```
The thing is that the Property name does not match the ID CustomAction
```
<CustomAction Id="Set_Action1_WixQuietExec_notepad.exe" Property="WixQuietExecCmdLine" Value="&quot;notepad.exe&quot; C:\boot.ini" />
<CustomAction Id="Action1_WixQuietExec_notepad.exe" BinaryKey="WixCA" DllEntry="WixQuietExec" Return="check" Execute="deferred" />
```

**Comment by Xaddan** [comment]
Also I can not change Id.
```
new WixQuietExecAction(new Id("Start_notepad_exe"), "notepad.exe", @"C:\boot.ini")
{
   Step = Step.CreateFolders,
   When = When.After,
   Execute = Execute.deferred,
}
```
or
```
new WixQuietExecAction("notepad.exe", @"C:\boot.ini")
{
   Id = "Start_notepad_exe",
   Step = Step.CreateFolders,
   When = When.After,
   Execute = Execute.deferred,
}
```
Id still remains auto-generated.

**Comment by oleg-shilo** [comment]
The only real problem is the ID assignment. Fixed. now.

As for deferred actions problem, it is how MSI works. None of the session properties can be accessed from the deferred actions. An since  WixQuietExec is relying on property to get the command line to be executed, it is heavily affect by the deferred actions limitation.

WixSharp lets you easy tunnel properties to the deferred environment. However, WixQuietExec is such clumsy attempt to solve a very simple problem in such a convoluted way. You are much better off with DeferredCustomAction or even project events:

```C#
project.AfterInstall += (SetupEventArgs e)=>
{
    Process.Start("notepad.exe", e.InstallDir.PathCombine("manual.txt"));
}
```

Have a look at "Setup Events" sample.
