### ISSUE TITLE
FileSearch

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#233]
It looks like Wix# does not support [FileSearch](http://wixtoolset.org/documentation/manual/v3/xsd/wix/filesearch.html).
Can you implement it? I think I can not handle it. :)
Example:
```
<Property Id="SQL_BROWSER_LOCATION">
   <RegistrySearch Id="SQL_BROWSER_LOCATION" Root="HKLM" Key="SYSTEM\CurrentControlSet\services\SQLBrowser" Name="ImagePath" Type="file">
      <FileSearch Name="sqlbrowser.exe"/>
   </RegistrySearch>
</Property>
```

**Comment by oleg-shilo** [comment]
Correct. It does not.

_File/Registry/SomethinElse_ Search is one of those convoluted MSI concepts that MS had to go with due to the MSI limitations. WixSharp fills the gap so one can have a proper routine with complex condition and flow control. 

Look how cleaner, more natural and more intuitive it can be done with WixSharp:
```C#
static public void Main(string[] args)
{
    var project = new ManagedProject("DreamProduct",
           ...
    project.AfterInstall += session =>
    {
        var browser_exe = (string)Registry.GetValue(@"SYSTEM\CurrentControlSet\services\SQLBrowser",
                                                     "ImagePath", null);
        if (File.Exists(browser_exe))
            Process.Start(browser_exe);
    };
```
Don't want to use ManagedProject? Still can do...  
```C#
static public void Main(string[] args)
{
    var project = new Project("CustomActionTest",
           ...
            new ManagedAction(CustomActions.StartSQLBrowser, ... Condition.NOT_Installed));
...

public class CustomActions
{
    [CustomAction]
    public static ActionResult StartSQLBrowser(Session session)
    {
        var browser_exe = (string)Registry.GetValue(@"SYSTEM\CurrentControlSet\services\SQLBrowser",
                                                     "ImagePath", null);
        if (File.Exists(browser_exe))
            Process.Start(browser_exe); 
         return ActionResult.Success;
    }
}
```

Saying that, I already have compromised once for RegistrySearch, which is implemented as `RegValueProperty`, I guess I can do something similar for FileSearch. But I really don't want to repeaat MSI mistakes. WixSharp supposed to be a 'better WiX' but not the same but with C#.

Thus I am putting it for voting. If community up votes this feature request, then be it.

**Comment by oleg-shilo** [comment]
Change of heart... :)

After some more considerations I decided to proceed with this feature. Nothing has changed. I do believe the MSI/WiX API paradigm is rather faulty, but... 

I cannot ignore the fact that some users are facing the task of porting legacy WiX solutions. In some cases using managed Custom Actions can also be difficult (hard to imagine but...). Thus accomplishing the tasks in such cases can be difficult.

Anyway, I scheduled it for the next release.

**Comment by oleg-shilo** [comment]
Done. Will be available in the next release:
```C#
new Property("SQL_BROWSER_LOCATION",
    new RegistrySearch(RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\services\SQLBrowser", "ImagePath", RegistrySearchType.file,
        new FileSearch("sqlbrowser.exe")))
```

**Comment by Xaddan** [comment]
Great news. Thank you so much.

**Comment by oleg-shilo** [comment]
This opens the gates for the implementation of all other `*Search` classes if the need arises.
