### ISSUE TITLE
Q: ManagedUI, Custom dialog and SetupEventArgs.IsUpgrading

### ISSUE THREAD

**Issue by dviry** [oleg-shilo/wixsharp#245]
I have an implementation question, here the details:

- using the ManagedUI, I've added a new custom dialog between the License and InstallDir dialogs
- I want to show this Dialog ONLY on Fresh installs (not on upgrades, nor uninstalls) - configured to support only MajorUpgrades
- attached to the UILoaded event, based on the property of setupArgs.IsUpgrading I then change the setupArgs.ManagedUI.Shell.Dialogs collection (to remove the custom and installDir dialogs) 

Q#1: is the .UILoaded event the correct place to make such changes?
Q#2: is changing the setupArgs.ManagedUI.Shell.Dialogs the best way?
Q#3: the property setupArgs.IsUpgrading is not available in the .UILoaded event (general comment: it's very hard to tell which properties are available when...), so how else would the v1 uninstaller know it's part of the upgrade? Not just for the dialogs, but to skip other tasks (like ServiceInstall) unrequired during upgrades.

My Solution: figure out if there is already a Version installed and set my own property, e.g.:

```c#
UILoaded += setupArgs =>
            {
                // on upgrades skip custom settingsDialog and installDir
                string upgradeCode = setupArgs.Session?.QueryUpgradeCode();
                Version version = AppSearch.GetProductVersionFromUpgradeCode(upgradeCode);
                if (version != null)
                {
                    setupArgs.Data.Add("_ISUPGRADE", "1");
                    if (setupArgs.ManagedUI.Shell.Dialogs.Count == 5)
                        setupArgs.ManagedUI.Shell.Dialogs.RemoveAt(1);
                    setupArgs.ManagedUI.Shell.Dialogs.Remove(Dialogs.InstallDir);
                }

            };
```

This feels like a "hack" and I was hoping someone here has a better way to implement this?

Thanks in advance

**Comment by dviry** [comment]
As a solution to Q#3, I am now using the suggested properties [as shown here](https://stackoverflow.com/questions/18531272/how-do-i-distinguish-between-a-normal-install-and-an-upgrade-in-wix).

Still pending an answer on Q#1,Q#2 as "best practices" based on your experience...

Thanks

**Comment by oleg-shilo** [comment]
Q#1-Q#2:  
Your approach is not necessarily a hack. MSI only provides two sets of dialogs "OnInstall" and "OnModify". Thus you have to modify somehow "OnInstall" set.

Anyway, your solution for modifying dialog set is OK. Though you may use an alternative technique that does not involve changing the dialog sequence but conditionally skipping some dialogs:
```C#
static void Project_UILoaded(SetupEventArgs e)
{
       e.ManagedUI.OnCurrentDialogChanged += ManagedUIShell_OnCurrentDialogChanged;
}
static void ManagedUIShell_OnCurrentDialogChanged(IManagedDialog obj)
{
    var session = obj.Shell.MsiRuntime().Session;
    if (obj.GetType() == Dialogs.Licence && session.IsUpgrading())
            obj.Shell.GoNext(); // skip licence dialog
}
```
It's not particularly better then your solution. Just an alternative.

Q#3:

May be you are dealing with the older version but the property you are looking fore is already there:
![image](https://user-images.githubusercontent.com/16729806/34317427-9530e95e-e802-11e7-9929-84d137b8dfdf.png)

Please also note that it is not possible to create the logical properties for ALL possible conditions the user may be interested in so instead of constantly modifying /extending `SetupEventArgs` WixSharp offers a set of extension methods for MSI `Session`. Thus if the property you need is missing you can always access the session properties directly or vie extension methods:
```C#
e.Session.IsUISupressed();
e.Session.IsUninstalling();
e.Session.IsUpgrading();
var is_upgrading = return session.IsModifying() && session.Property("UPGRADINGPRODUCTCODE").IsNotEmpty();
```

**Comment by dviry** [comment]
Thanks,

I've thought about your solution too (OnCurrentDialogChanged) - but wouldn't that still show the dialog for a microsecond and then switch to the next one?
I've been thinking of implementing exactly that to have multiple custom dialogs.

**Comment by oleg-shilo** [comment]
> ...but wouldn't that still show the dialog for a microsecond and then switch to the next one?

I don't think so. If I am not mistaken the message pump is blocked and rendering of the original dialog is effectively suppressed. But, of course, only the test will give you the answer. You can just use the standard "CustomUISequence" sample and in OnCurrentDialogChanged just skip one of the standard dialogs.
