### ISSUE TITLE
WixSharp doesn't remove temporary files if custom output name is specified

### ISSUE THREAD

**Issue by vers-one** [oleg-shilo/wixsharp#258]
Steps to reproduce:
1. Set `project.PreserveTempFiles` and `project.PreserveDbgFiles` to false.
2. Execute `project.BuildMsi("my name");`

Expected result: no temporary files in the output folder.
Actual result: three wixobj, wixpdb, and wxs files are in the output folder.

**Comment by oleg-shilo** [comment]
The problem is caused by the `"my name"` not being a proper file name. And this in turn prevents finding temp files for deletion. If you want to specify only a name instead of a path then you need to use `project.OutFileName = "my name"`.

Never the less it was a problem and now `project.BuildMsi("my name");` is converted into `project.BuildMsi("my name.msi");` on fly.

**Comment by vers-one** [comment]
It works!
Thank you!
