### ISSUE TITLE
Managed UI is running in 32bit mode. Custom Actions are running in 64bit mode.

### ISSUE THREAD

**Issue by Strohhalm** [oleg-shilo/wixsharp#283]
Hi,

I've made an Installer for 64 bit Application. And i'm reading previous configuration at the start of the install process to provide dialogs to change the configuration. And the changed configuration will be saved by custom actions. 

Now i discoverd that the ui is running in a differnt mode as the custom actions. Is there a possibility to change the ui to 64 bit?

thanks
Strohhalm

**Comment by oleg-shilo** [comment]
Sorry, the issue was closed without providing an adequate explanation at the time.

WixSharp (nor WiX) has no control over how the assembly, which implements EmbeddedUI is hosted. The choice of the CRL CPU architecture is entirely up to MSI runtime.

I cannot exclude that there is some magic MSI config value to trigger the desired behavior but I am afraid there is nothing you can do from WixSharp about it..
