### ISSUE TITLE
More problems with mixed x86 and x64

### ISSUE THREAD

**Issue by dhilgarth** [oleg-shilo/wixsharp#298]
I am trying to create an installer that

1. Installs into `Program Files` and not `Program Files (x86)`
2. Creates registry keys both in `Software` and in `Software\Wow6432Node`
3. Creates a folder in `ProgramData`

First thing I do is to set the Platform to x64, so this is a x64 installer.

Now, wix# seems to be adding all `RegValue` instances to the first directory it encounters ([reference](https://github.com/oleg-shilo/wixsharp/blob/736a49d16e2cadbf507765a07471f657d5b7d503/Source/src/WixSharp/Compiler.cs#L2237)). But this fails because the first directory is the ProgramFiles64 directory ("error LGHT0204: ICE80: This 32BitComponent Registry38 uses 64BitDirectory ProgramFiles64Folder").  
Then I tried to simply move the folder in `ProgramData` to the first position. This fixes the compilation errors, but now it thinks that this folder is the installation directory.  
Next, I tried to give the actual installation directory several IDs that I hoped would help. I tried `INSTALLDIR` and `INSTALLDIR_ABSOLUTEPATH`. This seemed to confuse the system even more, because now, the `[INSTALLDIR]` variable which I use in a regvalue got expanded to `C:\ProgramFiles64Folder`. Also, the property `INSTALLDIR_ABSOLUTEPATH` is always set to the first encountered directory ([reference](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp/AutoElements.cs#L588)).  
Finally, it seems to be impossible to add a `RegValue` to a `Dir`, to manually choose the directory it should be contained in ([reference](https://github.com/oleg-shilo/wixsharp/blob/736a49d16e2cadbf507765a07471f657d5b7d503/Source/src/WixSharp/Dir.cs#L369))

I am not sure how to proceed from here.

**Comment by dhilgarth** [comment]
My solution for now is to leave the actual install directory at the first position and to manually move the registry components to the other directory in the `WixSourceGenerated` event:

```
var namespaceUri = "http://schemas.microsoft.com/wix/2006/wi";
XNamespace @namespace = namespaceUri;
var namespaceManager = new XmlNamespaceManager(new NameTable());
namespaceManager.AddNamespace("wix", namespaceUri);
var registryComponents = doc.XPathSelectElements("//wix:RegistryKey", namespaceManager).Select(x => x.Parent).ToArray();
var parentDirectory = registryComponents.GroupBy(x => x.Parent).Single().Key;
var nextDirectory = parentDirectory.ElementsAfterSelf(@namespace + "Directory").First();
foreach (var registryComponent in registryComponents)
{
    registryComponent.Remove();
    nextDirectory.Add(registryComponent);
}
```

**Comment by dhilgarth** [comment]
Hm, this is still a problem and a bug, I would say.

**Comment by oleg-shilo** [comment]
Sorry, I was just closing all older 'question' issues that have been answered. The usual housekeeping after yet another release. 

I assumed that your question/issue is addressed with the work around you shared. Apparently I was mistaken. I am reopening it now and will have a look at it tomorrow.

**Comment by dhilgarth** [comment]
Well, the workaround helps, but it is still a bug in WiXSharp, don't you think?

**Comment by oleg-shilo** [comment]
Daniel, I just cannot do right now any deep investigation but I will come back to you tomorrow with the more more in depth explanation. 

But from the top of my head, ICE validation imposes some draconian restrictions (e.g. you must have at least a single component in the user profile). Thus user has only two options: 
* disable ICE
* insert dummy components

WixSharp inserts the components by default.  Apparently in your case it inserts the dummy component incorrectly it is a bug but not the one that happens all the time. It is a the first report for auto-insertion failure to be caused by x64. That's why I would really appreciate a simple "hello world" project that shows the problem
 
In a mean time you can disable this auto-workaround by setting `AutoElements.DisableAutoUserProfileRegistry = true`

**Comment by oleg-shilo** [comment]
After some real testing I can only confirm my initial conclusion: the _"user-profile" auto insertion_ does not exhibit any problems for the canonical setups (pure-platform deployment).

Thus I just added `project.Platform = Platform.x64;` to the "Shortcuts" sample and the setup can be built just fine.

This means that for the scenarios like yours (mixed x86 and x64) _"user-profile" auto insertion_ technique is not reliable and  should not be used. 

Thus you will need to disable it via `AutoElements.DisableAutoUserProfileRegistry` and handle all possible ICE validation failures by yourself. Simply, WixSharp's default ICE work around simply cannot cope with scenarios like yours.

Saying that, if you provide me with the sample that I asked I can have a look and possibly improve _"user-profile" auto insertion_ algorithm to cover your scenario as well.

**Comment by dhilgarth** [comment]
Thanks for taking the time to look into this. To be honest, I didn't really follow along with all the ICE and user profile stuff.  
But I will try and provide you with a sample.

**Comment by dhilgarth** [comment]
Thanks for the explanation.

This is a small sample that exhibits the problem I described:

```
            var project = new ManagedProject("MyProduct", new Dir(@"%ProgramFiles%\My Company\My Product", new File("Program.cs")))
            {
                Platform = Platform.x64,
                GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b")
            };

            project.AddRegValue(new RegValue(RegistryHive.LocalMachine, @"Software\test", "foo", "bar") { Win64 = false });
            project.BuildMsi();
```

**Comment by oleg-shilo** [comment]
OK. Thank to your sample it's all clear now.

I assumed that the ICE failure was caused by that "user-profile dummy registry" auto-insertion by WixSharp. I was wrong. When I disabled WixSharp auto-insertion (the one that I constantly hinted you about) it produced clean pure WiX definition, which..... triggers the same ICE validation failure: 
```
Support\testpad\MyProduct.wxs(16) : error LGHT0204 : ICE80: This 32BitComponent Registry1 uses 64BitDirectory INSTALLDIR
```
Meaning that it is the problem you are experiencing is caused not by the WixSharp ICE workaround but rather by the very nature of your setup. 

You are mixing x86 and x64. MS thinks that it is a bad idea and tells you about that. You may disagree with that (I do) but this is what ICE validation does. Ironically, despite this problem being reported as error it is in fact a warning and your very sample successfully builds into an msi. The produced msi correctly installs the all components.

If you don't want to see that error/warning you can suppress it via Light arguments:
```C#
Compiler.LightOptions += " -sice:ICE80";
``` 
As far as I WixSharp concerned this issue can be closed now as it is rather an MSI annoyance than a defect.

**Comment by dhilgarth** [comment]
Still, in plain Wix I could add the registry values to any component but in Wixsharp I don't have that choice and the registry values always get added to the first component hence producing this error/warning.

**Comment by dhilgarth** [comment]
This is a minimal example. And in my last comment I used the wrong terminology. What I meant was that I can't choose to which *directory* the reg values are added. They are always added to the first directory.
But why are they added to a directory at all? They have nothing to do with the file system and [the documentation](http://wixtoolset.org/documentation/manual/v3/xsd/wix/component.html) states that a `Component` can be added directly the the `Product` tag.

So I still think it is a wixsharp problem: It shouldn't add reg values to directories.

**Comment by oleg-shilo** [comment]
I 100% agree with your "_But why are they added to a directory at all? They have nothing to do with the file system_" But... an ugly MSI architecture requires that everything must be in the directory. 

> ... documentation states Component can be added directly the the Product tag.

But it still has to belong to the directory. The documentation on Component is very deceiving.

Yes the it says that component may be contained by the `Product` but it failed to mentioned that in this case `Component.Directory` attribute must be set to the ID of the directory that component belongs to. Otherwise compiler produces: ` error CNDL0010 : The Component/@Directory attribute was not found; it is required.` In other words in MSI you cannot possible have anything (permissions, envars, users etc.) that is not under a Directory umbrella. Shocking!

I would really prefer you not to take my word and verify it by yourself. Do a simple test. Build this:
```C#
var project = new Project("MyProduct", new Dir(@"%ProgramFiles%\My Company\My Product", new File("setup.cs")))
{
    Platform = Platform.x64,
    GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b")
};

project.AddRegValue(new RegValue(RegistryHive.LocalMachine, @"Software\test", "foo", "bar") { Win64 = false });

project.BuildMsiCmd();
``` 
Now, before executing `Build_MyProduct.cmd` modify 'MyProduct.wxs' by moving your registry component directly under `Product` element. Now execute `Build_MyProduct.cmd`. This will yield the Component/@Directory error.

I know, this ridiculous MSI architecture frustrates me too. The documentation isn' helping neither. This is in fact the reason why I created WixSharp - just to help with all this mess. But WixSharp can do only so much.

**Comment by dhilgarth** [comment]
I see. That really sucks :-(
So, what about allowing the user to choose to which directory the reg values are added? That's what my workaround does: It moves the reg values to a non-x64 directory.

**Comment by oleg-shilo** [comment]
> I see. That really sucks :-(

It absolutely does.

WixSharp goes far an beyond trying to address MSI shortcomings. Consider this:

```C#
var project = 
    new Project("MyProduct",
        new RegValue(RegistryHive.LocalMachine, @"Software\test", "foo_value", "bar"));

project.BuildMsi();
```

The deployment scenario is straight forward. The msi can be compiled and if installed it does exactly what it supposed to do. The relationship between setup itself and its asset(s) (RegistryValue in this case) is correct - "standalone deployable component". All great. However... WixSharp had to create a dummy directory in the WiX XML definition as otherwise the scenario is juts 100% impossible in the canonical WiX/MSI. 

Just to satisfy ICE80 validation. Ridiculous! 

----
Just after our yesterday conversation I reflected on the current handling RegValues and managed to update it to also insert second x86 dummy directory for the mixed CPU scenarios (like yours). Thus it does not longer trigger ICE80 failure (HotFix is available). But I have done it not because WixSharp had the problem but out of compassion to my fellow developers. 

I want to stress. WixSharp (as in the sample above) encodes deployment-assets relationships correctly while MSI/WiX does not. Thus the only truly adequate handling of this problem is to disable and ignore the faulty ICE warning. 

In fact, when I play with some XML injection I hide the fundamental MSIWiX conceptual flaw.

**Comment by shengxue** [comment]
@oleg-shilo  Thanks for your answer:
``` csharp
Compiler.LightOptions += " -sice:ICE80";
```
which gives me valuable hint on how to fix build errors on DevOps pipeline.

I met with over 60 ICE errors, and it is boring to hard code all these ICE errors.  After some google, I found this option:
``` csharp
Compiler.LightOptions += " -sval";
```
which suppresses all ICE errors.

**Comment by oleg-shilo** [comment]
Perfect, thank you for sharing
