### ISSUE TITLE
ServiceConfig functionality warning

### ISSUE THREAD

**Issue by steronydh** [oleg-shilo/wixsharp#299]
I'm seeing this warning when setting up a Windows Service:

`ServiceConfig functionality is documented in the Windows Installer SDK to "not [work] as expected." Consider replacing ServiceConfig with the WixUtilExtension ServiceConfig element.	`

Wix Toolset 3.111.2318
WixSharp 1.6.2

**Comment by steronydh** [comment]
Hi @oleg-shilo, has this been fixed or just closed?

**Comment by oleg-shilo** [comment]
No, it has been closed by mistake I treated it as a "_question_". It still has the original label "_enhancement_".  I am reopening it. 

Basically it is a feature request and it needs to be up-voted in order to be scheduled for implementation. Unless the migration to `WixUtilExtension.ServiceConfig` is trivial. I don't really know if it is or isn't.

**Comment by oleg-shilo** [comment]
I have checked it and it seems like it is much trickier then it seems.

The warning itself is questionable. This is a good post about it: https://stackoverflow.com/questions/43972417/configure-service-to-delayed-auto-start-and-auto-start-on-xp-2003

Basically "WixUtilExtension:ServiceConfig", despite being a newer implementation,  does not deliver even the same functionality as "ServiceConfig". 

WixSharp support for services emits both raw and util's `ServiceConfig`, tunneling `ServiceInstaller` properties to one ore another element depending on which one supports this property.

Thus WixSharp offers the maximum "feature coverage". This seems to be a good approach until WiX makes raw ServiceConfig element fully obsolete.

If you ask me there should not be any warning since one element does not really replaces another one.

**Comment by madelson** [comment]
Who is generating this warning? Is the recommendation to ignore it?

**Comment by oleg-shilo** [comment]
The warning is generated by WiX compiler. 
I cannot give an official recommendation as WixSharp has no affiliation with WiX. It is ultimatelly up to WiX people to comment on the warning.

But as a developer (not WixSharp) author I recommend ignoring it. The situation is actually ridiculous. WiX is saying "Please use library B because it earlier version A may or may not work under ceratain circumstances.  But... library B does not have all features of library A so you decide which one to use."

**Comment by madelson** [comment]
@oleg-shilo does it make sense for WixSharp not to flow that through as a build warning, then?

**Comment by oleg-shilo** [comment]
Not really, WixSharp does not intercept and or massage WiX compiling output. Thus what you see on the screen it is WiX at work. It's not WixSharp business to interfere with the tools it is using.

Sorry, I know it's not the answer you were hoping for.

**Comment by madelson** [comment]
@oleg-shilo good to know, and thanks for the context!

**Comment by tblong** [comment]
Adding link and quote to the [MsiConfigureServices Action](https://docs.microsoft.com/en-us/windows/win32/msi/msiconfigureservices-action) page which the WiX compiler is referring to (emphasis mine):

> Windows Services provides the ability to automatically perform predefined actions in response to a failure in a service. To support programmatically setting up these Recovery Actions when a service fails, **MsiServiceConfigFailureActions** was added to MSI in version MSI 5.0. However, **this functionality is not working as expected**.
To workaround this issue, an application developer should use the Custom Action functionality in MSI to run sc.exe and set the Recovery Options appropriately.

Adding this comment mainly to remind myself that I've been here already.
