### ISSUE TITLE
SetNetFxPrerequisite doesn't work with ManagedUI

### ISSUE THREAD

**Issue by Masterkatze** [oleg-shilo/wixsharp#316]
Hello, i have a trouble with checking if .Net Framework is installed or not on Windows 7. I created a small example based on CustomUI template from the Visual Studio to to illustrate this:
```
namespace setup1
{
    class Program
    {
        static void Main()
        {
            var project = new ManagedProject("Setup",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File(@"Files\MyApp.exe")));

            project.ManagedUI = new ManagedUI();

            project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                            .Add<LicenceDialog>()
                                            .Add<SetupTypeDialog>()
                                            .Add<FeaturesDialog>()
                                            .Add<InstallDirDialog>()
                                            .Add<ProgressDialog>()
                                            .Add<ExitDialog>();

            project.ManagedUI.ModifyDialogs.Add<MaintenanceTypeDialog>()
                                           .Add<FeaturesDialog>()
                                           .Add<ProgressDialog>()
                                           .Add<ExitDialog>();

            project.SetNetFxPrerequisite(Condition.Net45_Installed, "Please install .Net 4.5 First");

            project.BuildMsi();
        }
    }
}
```
If i run .msi on a system without .Net Framework installed i got nothing (no dialogs), install log: https://gist.github.com/Masterkatze/ea040b5136609825924d7fd5b9c84cf6

But if i delete all ManagedUI stuff SetNetFxPrerequisite will work as expected.
```
namespace setup1
{
    class Program
    {
        static void Main()
        {
            var project = new ManagedProject("Setup",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File(@"Files\MyApp.exe")));

            project.SetNetFxPrerequisite(Condition.Net45_Installed, "Please install .Net 4.5 First");

            project.BuildMsi();
        }
    }
}
```
Am i missing something or this is a bug?

**Comment by oleg-shilo** [comment]
It is an interesting one.

Since EmbeddedUI is an MSI technology that hosts UI on the CLR of the target system.  Thus I would expect it to do its own check for CLR presence and report it to user if it's not found. But it does not :(

Anyway, I have just added the launch condition to the 'EmbeddedUI' sample. 

```C#
project.SetNetFxPrerequisite("NETFRAMEWORK20='#77777'", "Please install .NET 2.0 first.");
```

![image](https://user-images.githubusercontent.com/16729806/37551812-2963113e-29fc-11e8-8f8b-5de1cbe4dee1.png)

Because of that `7777` it always show launch condition failure message. Always, except if embedded UI is used.

I also deliberately used 'EmbeddedUI' sample to completely eliminates WixSharp influence. This sample is an official MS Embedded UI sample.

Now this is what i am speculating. The `Condition` element is an instruction to show the message under certain circumstances. Though MSI runtime is doing it with native UI (message box). And when native UI is rerouted to EmbeddedUI MSI runtime fails to understand that it is still a I mode and suppresses all message boxes. If I am right then it is an MSI bug.

Unfortunately there is no good work around. One option is to use bootstrapper (Burn). This is a later MSI/WiX arrival and it plays nice with prerequisites. It simply installs minimal .NET version at startup if none is present on the target PC.

Alternatively you can have a look at 'Simplified Bootstrapper' project. It may (though not sure) just work for your scenario.
