### ISSUE TITLE
Custom BA dynamic logo

### ISSUE THREAD

**Issue by sanjuleo** [oleg-shilo/wixsharp#323]
Hi Oleg
I generate installers dynamically, which includes different logo and titles for same application installer.

I can pass the logo and product name to bundle definition but how to receive them in the customBA model which has BootstrapperApplication parameter. I need following information there -
   bootstrapper.IconFile
   bootstrapper.Application.LogoFile
   bootstrapper.Application.LicensePath

I hope this is doable.

**Comment by oleg-shilo** [comment]
As far as I a aware there is no interface between the bundle definition and the CustomBA.

This is my understanding that `bootstrapper.Application.*` are the instructions for the Burn compiler to pack these resources into the stock BA executable under well-known resource names, where they are extracted at runtime by the stock BA.   

Thus CustomBA cannot possibly benefit from the `bootstrapper.Application` properties. Your best chance is to include your required content into your CustomBA resources as stock BA does. 

Though there is a theoretical possibility to achieve what you want. You can have your CustomBA built in a separate assembly and packed with the default resources. 

In the on-source-generated project event you can read the location of the actual resource (e.g. logo file) and patch programmatically (substitute resources) your customBA assembly. That's it.

Patching resources of the binary file seems like a black magic but it's not. You can use ResourceHacker or any other similar solution.

If you build batch file instead of MSI (`project.BuildMsiCmd`) then you don't even have to subscribe for the project event.

**Comment by sanjuleo** [comment]
Got it. Thanks.
