### ISSUE TITLE
Embeded Ui - Upgrading and leaving old Apps & Feat. entries

### ISSUE THREAD

**Issue by Phoe351** [oleg-shilo/wixsharp#327]
Hi wixshapers,

I've created a EmbededUI Bootstrap installer based on the samples.  Through the trials of adopting
the samples had some great success.  
I now have one remaining issue I cannot resolve.  When upgrading the MSI from the bootstrap,
the old MSI is successfully uninstalled and the new MSI installed.  The old entry remains in Apps & Features (Win10). 
 I can uninstall the latest bootstrap upgrade. When selecting Uninstall from the previous Apps & Features entries this results in the cached installer running a new install again.  
The old versions remains in the registry HKLM....Uninstall.  Deleting this entry removes it from Apps & Features.
I have noticed the Uninstall registry GUID is lower case where most are not.  
Other Recommendation suggest GUIDs be uppercase.

[setupCS.txt](https://github.com/oleg-shilo/wixsharp/files/1850067/setupCS.txt)

**Comment by oleg-shilo** [comment]
A few points....

* I am not entirely sure about the Burn (bootstrapper) approach towards uinstalling an individual products. Though in any case I it is BA who is responsible for scheduling the install/uninstall plan during the startup. And since you are using your own BA then may be there is something wrong with scheduling. 
Anyway, try to use standard WiX BA - leave `project.Application` unassigned. See if it makes any difference. 

* From your code sample:
   > /* Which is better MajorUpgrade or MajorUpgradeStrategy? */

  Answer (from documentation):
  ```
   Note: MajorUpgradeStrategy yields WiX UpgradeVersion element, which is arguably the most
   comprehensive upgrade definition. However in the later versions of WiX a simplified upgrade 
   definition has been introduced. It relies on MajorUpgrade WiX element. For most of the upgrade
   scenarios you will find that MajorUpgrade allows to achieve the same result with much less
   effort. Wix# supports MajorUpgrade element via MajorUpgrade member.
  ```  
   Thus, may be try `project.MajorUpgrade` instead.

* From your post: 
   > I have noticed the Uninstall registry GUID is lower case where most are not.
      Other Recommendation suggest GUIDs be uppercase.

   WiX takes care about the upper-casing. If you look at your msi in Orca you will see that the all vital properties are in uppercase. Even if in WixSharp they were are in lowercase:

   ![image](https://user-images.githubusercontent.com/16729806/38003884-4e9b8940-3285-11e8-910d-2a450d71b16d.png)

![image](https://user-images.githubusercontent.com/16729806/38003943-9a9d6ad4-3285-11e8-88cf-46c0f14cd402.png)

**Comment by Phoe351** [comment]
Hi Oleg,
thank you for the quick and thorough response.  I reset the MsiPackage bundle to DisplayInternalUI = true, and Msi package UI to ManagedUI.Default. Doing this is showed that the Wix worked correctly,
removing the old version and installing the new version.  The Apps & Feat. showed only the current
version.
This lead me to need to understand more about what is happening in the Bootstrapper.Engine.
When the uninstall is detected in the OnDetectPackageComplete event
I could then launch the LaunchAction.Uninstall at the correct time.  

Thank you again, I'm enjoying WixSharp.

_Attached is the OnDetectPackageComplete to help others if they had the same journey.
I have also been using Revo Uninstaller to get the registry key of orphan Apps & Feat. 
and Powershell:
Get-Process | Where-Object {$_.Path -like "*MyInstaller*"} | Stop-Process -WhatIf
to avoid building with the output file in use error: 
".... /MSBUILD:WixBootstrapper_UI"" exited with code 255"_

[wix_sample_whatsolvedmyissue.txt](https://github.com/oleg-shilo/wixsharp/files/1854755/wix_sample_whatsolvedmyissue.txt)
