### ISSUE TITLE
How to read in installdir xml file value

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#328]
Hi Oleg, do you have some code example , how do i read values from XML file where my data like licensekey, connectionstring etc. saved ?  My Applicaion being installed and i do major upgrade, works fine. 
I tried to set if like another Property and get it from ManagedAction, but i dont get any Values from File.
I think this is because msi cant get xml file without session with Propertie.
In SetPropertieAction i found example and it looks like this
project.Properties = new[] { new Property("Licensekey", "empty")};
project.Actions = new WixSharp.Action[] { new SetPropertyAction("Licensekey", "[INSTALLDIR]" +  settings.getKey()) { When = When.Before, Step = Step.InstallExecute},
                    new ManagedAction(@"GetLicensekey") { Id = "Licensekey", Sequence  = Sequence.InstallExecuteSequence }};
Settings.getKey() should get saved key and then i can check if key are valid or not. After this i can execute update. 
How can i get value from INSTALLDIR\settings.xml during major upgrade ? 
Alternatively i think, i have to store destanation for any xml file in my registry and set if in session from Registry. this should surely work.

**Comment by oleg-shilo** [comment]
This is my personal view on the matter. MSI is fantastic with transnational install/uninstall actions. For anything behavioral or algorithmic it drastically fails. The constantly growing set of WiX Utils is gradually making it better but it does not address the fundamental problem - declarative programming paradigm is the best for expressing relationships but struggles with expressing algorithms.

That is why I always prefer to use custom actions for anything like your case. Particularly because now you can use C# in these routines. 

Have a look at `Setup Events` sample it shows how to access files during and after installations.

Though `DeferredActions` sample probably is the best for you as it shows XML file manipulations.

**Comment by Torchok19081986** [comment]
Ok. Thanks for help Oleg. Where can i find Setup Events sample ? Deffered Actions are in current Release Code 1.6.3.2 available. But i cant find Sample with Setup Events.

**Comment by oleg-shilo** [comment]
You can find it here: [Wix# Samples/Managed Setup/SetupEvents](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/SetupEvents)
