### ISSUE TITLE
How Can I preserve installed Features on Major Upgrade

### ISSUE THREAD

**Issue by gerardcarbo** [oleg-shilo/wixsharp#329]
Hi,
Is it possible with Wixsharp to preserve the already installed Project Features on previous Setup while performing a Major Upgrade of the product? 
Thanks

**Comment by oleg-shilo** [comment]
Short answer is "you cannot". This MSI upgrade mode is called "major" because it simply uninstalls the existing product completely and installs the newer version from scratch.

Though what you can do is to save the list of selected features by yourself in the well known location (e.g. registry) and on startup (if this list is found) enable these features before commencing the installation of the new version.
