### ISSUE TITLE
Dynamic feature list with checkboxes

### ISSUE THREAD

**Issue by petrovaOlia** [oleg-shilo/wixsharp#330]
Hi Oleg!

Could you help please...
I got stuck with the simple task: dynamic feature list with checkboxes.
WixUI_FeatureTree and ManagedAction allow to successfully apply FeatureCondition but I need checkboxes also.
ManagedUI and UILoaded handler provide simple way to construct custom set of dialogs and can show features with checkboxes but the FeatureCondition doesn't work in my sample: all features are shown even I set property to 0.
[setup.txt](https://github.com/oleg-shilo/wixsharp/files/1861002/setup.txt)

**Comment by oleg-shilo** [comment]
I suggest you instead of predefined `FeaturesDialog` dialog you use your custom version where you can extend the feature stat analysis with checking your `FeatureCondition`s. 

The simplest way to do this is to create a new ManagedUI project:
![image](https://user-images.githubusercontent.com/16729806/38185205-6a15c9ba-3690-11e8-9c84-ee18cbb7a489.png)

With this project type you will get the `FeaturesDialog` as a source code so you can modify the checkbox initialization routine anyway you want.
