### ISSUE TITLE
Capture build errors

### ISSUE THREAD

**Issue by sanjuleo** [oleg-shilo/wixsharp#353]
Hi Oleg
Many a time project.BuildMsi() fails as I miss out on a required file or due to something else. But it is difficult to find out such errors.

Project class does not have any error events. Is there any way to capture wix build errors?

Regards
Navin

**Comment by oleg-shilo** [comment]
It is close to impossible for WixSharp to detect errors. The actual compilers are executed as external processes and they don't report errors to the host environment but only emit text containing error description. This works well with the WixSharp VS projects as in this case the IDE filters the std output and flags errors (e.g. text `error: ` has been found).

But if you use WixSharp to build msi truly programmatically then you can only rely on two things. 
- The return value of the `BuildMsi(...)` call. If it is `null` they the build has failed. Otherwise it is the location of the new msi file.

- You can analyze the output of the WiX compilers by yourself:

  ```C#
  Compiler.OutputWriteLine = line =>
  {
      // check 'line' for errors here
      Console.WriteLine(line);
  };
  ```
