### ISSUE TITLE
Click No in UAC prompt

### ISSUE THREAD

**Issue by CarenWong** [oleg-shilo/wixsharp#363]
If I click No in UAC prompt, will go to Exit dialog with msg saying installation completed instead of user interrupt. Though, nothing is installed really.

In log:
Info: User cancelled installation.

I notice when processing msg:
```C#
if (messageType == InstallMessage.Info)
{
    if (messageRecord.ToString().Contains("User canceled installation")) //there is no other way
        UserInterrupted = true;
}
```

**Comment by oleg-shilo** [comment]
Fixed. Will be available in the next release

---
It is an accidental misspelling. To be more accurate the VS spellchecker "fixed" it to US version, which is not what MSI is using for logging at runtime. 

Please use the following work around (`Shell.Log.Contains`) in the Exit dialog until the fix is available.

```C#
if (Shell.UserInterrupted || Shell.Log.Contains("User cancelled installation."))
{
    title.Text = "[UserExitTitle]";
    description.Text = "[UserExitDescription1]";
    this.Localize();
}
```

Please note that that unfortunately MSI does not provide any deterministic way of detecting user cancellation and analyzing the log (the only possible way) is not reliable by nature.

**Comment by CarenWong** [comment]
Thanks!
