### ISSUE TITLE
"Newer version already installed" dialog does not show if using project.ManagedUI

### ISSUE THREAD

**Issue by KryuchkovAlexandr** [oleg-shilo/wixsharp#38]
Hello!
I want to show dialog if newer version already installed. Then stop the installation process.

![error](https://cloud.githubusercontent.com/assets/5755024/23737762/b0a97df0-04c7-11e7-9936-972bc1005974.png)

If i use **project.UI**. Dialog is shown and installation is stopped. 
`project.UI = WUI.WixUI_InstallDir;`

If i use **project.ManagedUI**. Dialog is not shown. Although the installation is stopped. And in log i see error with message "Newer version already installed"
```
project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                            .Add(Dialogs.Licence)
                                            .Add(Dialogs.InstallDir)
                                            .Add(Dialogs.Progress)
                                            .Add(Dialogs.Exit);
```
How to show this dialog when i use ManagedUI?

**Comment by oleg-shilo** [comment]
This is because MSI invokes `EmbeddedUI` as a complete alternative of the built-in UI. Thus while MSI still verifies if the prev version is installed, it doesn't show any message as it is supposed to be done through `EmbeddedUI`. 

You can do this from the `BeforeInstall` event and/or from `UILoaded` event. 

`AppSearch` class has a utility for checking presence of prev installs (see this post https://github.com/oleg-shilo/wixsharp/issues/31).
```c#
static void project_BeforeInstall(SetupEventArgs e)
{
    var installedVersion = AppSearch.GetProductVersionFromUpgradeCode(e.UpgradeCode);
}
```  

The code above is a new API and it will be released today or so.

**Comment by KryuchkovAlexandr** [comment]
Thanks!
