### ISSUE TITLE
Many times the UAC dialog to proceed with the installation is showed minimized

### ISSUE THREAD

**Issue by marcobeninca71** [oleg-shilo/wixsharp#381]
Dear Oleg
I know this is up to msi management but many times the UAC dialog to give the permissions to the installer is shown minimized. Is there any way to force the dialog to be shown of the top of the screen?
Best regards
Marco

**Comment by oleg-shilo** [comment]
No, not really. It is a known UI quirk of Windows. All work around solutions (including WixSharp) are not really reliable. 

Read about it in the wiki section starting from this line: [`ManagedUI, as well as all other implementations of EmbeddedUI`](https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#managed-standard-ui)

**Comment by marcobeninca71** [comment]
Thanks Oleg
maybe a workaround is to have a .exe as output of the wix project. I saw that in Wix it's possible to set as output type an executable. I found the following enum in WixSharp

`public enum OutputType
        {
            /// <summary>
            /// MSI file.
            /// </summary>
            MSI,

            /// <summary>
            /// Merge Module (MSM) file.
            /// </summary>
            MSM
        }`

In which Exe is missing. Is it possible to have an exe as output of the project?

**Comment by oleg-shilo** [comment]
No, it's not that simple :)

MSI setup is not an executable but a database file. This file has two formats 
- MSI - contains installation instructions for a product to be **installed**. 
- MSM - contains installation instructions for a product to be **merged** with (included to) another product setup.

Only msi file can be "executed". But the execution actually means starting `msiexec.exe` file and passing msia file as an argument. This is what Windows does when you double-click msi file. After starting `msiexec.exe` communicates with MSI runtime service and pushes msi file into it. 

Though Windows has an alternative msi execution model. Instead of stock executable `msiexec.exe` you can create your own. And you can even handle there multiple msi files in a sequence. Such an executable is called 'Bootstrapper' and it usually has a custom GUI.

WixSharp supports building bootstrappers for a single or multiple msi(s). You can find corresponding samples. However... boostatrapper is affected by that UAC problem as any other windows process. 

Meaning that still there is no a reliable solution to it.
