### ISSUE TITLE
Builderror "This file does not have a program associated... "when using WixSharp in ClassLib

### ISSUE THREAD

**Issue by sven-weber** [oleg-shilo/wixsharp#382]
Hi, 

we are currently developing a WixSharp wrapper for internal use. 
The Wrapper is provided as .Net Class Library using the latest WixSharp version 1.6.5 as Nuget. 

When trying to build the Library we detected some strange behavior during the build process. 

Build failed with the following error: 

![image](https://user-images.githubusercontent.com/39764491/40716200-706041ec-6408-11e8-8b51-e97ade1663c0.png)

We found out that the error is caused by the WixSharp.targets file located at \packages\WixSharp1.6.5\build\WixSharp.targets.

The line 

<Exec Command="&quot;$(TargetPath)&quot; &quot;/MSBUILD:$(ProjectName)&quot;" WorkingDirectory="$(ProjectDir)"/>

causes the fail because the target type "class library" (.dll) cannot be started executed.
The error does not occur when using Wix directly in e.g. a command line App. 

When removing the line from the file everything seems to be working fine. Setups are build and they can be executed as intended. 

What exactly is the aim of the "Exec Command" ? 
Is there something we are missing when using WixSharp in class libraries? 

We are happy to provide furthermore information when needed. 

Thanks in advance!

**Comment by oleg-shilo** [comment]
It's actually quite simple. WixSharp is a build tool not a _Class Library_. That is why it is an executable and the intention is to run this executable at the end of VS project build. Thus the purpose of _WixSharp.targets_ to achieve the integration of WixSharp compiler with MSBuild engine.

However you are not using WixSharp as an MSBuild tool but as an external assembly with the desired runtime behavior. Thus you will be better off just take the binaries from the WixSharp.bin package and instead of taking the whole package with the MSBuild integration content.

**Comment by sven-weber** [comment]
Hi Oleg, 
thanks for the quick response and sorry for me responding late. 

We will restructure our project in order to use the WixSharp.bin package as only dependency. 

I will close the issue. Thank your for the support!
