### ISSUE TITLE
How to create backup from installation

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#385]
Hi Oleg. I need some clarity. is there some posibility to create backup before installation ? 
Scenario: move or rename installed msi product in same folder, then install package. if installation failed for some reason show messagebox update or installation was failed, rename or move previous installation back and if not delete it. if i understand right, i can only execute CA between install and installfinalize. Is that corect ?

**Comment by Torchok19081986** [comment]
Thanks. i understand now. Sounds right. Ok, thats meaning all i can do for update is backup user settings in temp folder and restore it after update  if needed.

**Comment by oleg-shilo** [comment]
Bingo!

Though if you keep user settings in the global app data location then you don't even have to back them up. This is how it works:

1. User installs the software. Only the software **BINARIES** are deployed.
2. User starts the software for the first time. 
3. It detects absence of the user settings and creates them with all values initialized to their corresponding defaults in the `%AppData%\<Product>\Settings`.
4. Software loads the user settings found in the `%AppData%\<Product>\Settings`

The steps above is the set of typical deployment steps for any software that follows "good deployment practices". BTW if software does not do deployment this way it cannot be certified for "Designed for Windows (Vista/7/8/10)".

The deployment above automatically handles many otherwise challenging runtime scenarios:
* Upgrade/Rollback (your scenario)
* A freshly created user starts using already installed software product
* Corrupted user settings need to be restored. 
* Portable deployment (zip file) needs to be published as an alternative to msi.

All this without any extra effort. You can just benefit from a balanced proper deployment design.
