### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by gcostanzo** [oleg-shilo/wixsharp#386]
Hello,

I'm very new to WiX and WixSharp, but I'm really enjoying the technology so far, although I do find the many ways to accomplish a specific task slightly confusing, especially when there are so many contradicting posts online regarding the same issue. One such task I'm trying to accomplish is to create a setup package which prompts the user to select a language and then display the MSI in this language. I've read that there are 2 main ways to go about doing this: 1) single MSI with multiple transforms and calling MSIEXEC with language transform parameter and 2) bundling multiple language-specific MSIs in a bootstrapper application by utilizing the "InstallCondition". The latter seems to be a pretty good approach. The 3rd post by Phill Hogland from the following thread seems to describe what I'm looking to accomplish:
http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/Re-burn-bootstrapper-access-lang-as-a-property-or-variab-le-td7599256.html

How would I accomplish this with Wix#? Is there another way to do this?

I'm perfectly content to use the MSI UI, so if there's any way of selecting the language with a `Project` or `ManagedProject` without the need to use a bootstrapper, please let me know. I've managed to use the `UIInitialized` event of the `ManagedProject` class, along with `AppSearch` and .NET registry to detect the presence of a previous version of the same product, but packaged with another setup tool, and call the command to uninstall before running the MSI, so I was looking for an event-driven way to allow the user to select the language, but to no avail.

Any help you can provide would be greatly appreciated.

P.S. I wasn't sure where to send my question and noticed other asking it here, but if there's a better place for questions, please let me know for future reference.

**Comment by oleg-shilo** [comment]
This is actually is the best place to ask :)

Yes, I also found the amount of inconsistent semi-working WiX snippets completely overwhelming. That's why WixSharp comes with ~90 fully working complete samples for various deployment scenarios. 

* [Samples Library](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples)

I am not sure what triggers inclusion of multiple transforms in the compiled msi but alternatively you can include transforms as a binary file and just extract it on the target system before restarting msiexec  with th language required Id.

One of the possible restarting technique is described here: #384

Though the most relevant sample for your case is the `CustomUIDialog`. While is not native but a WinForms setup UI it shows how to load German content at runtime. Also being WinForm assembly helps as it lets you use standard .NET localization. 

But the technique from #384 may be just what you are looking for.

**Comment by oleg-shilo** [comment]
I have just committed the sample that restarts the msi elevated if it is not. YOur use case is practically the same except you are testing the system locale instead of the user privileges:
https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/RestartElevated(UI)

Though the best user experience can only be achieved with ManagedUI. Native UI is just too limited. :(

**Comment by gcostanzo** [comment]
Hello, thanks for the response. You mention the CustomUIDialog sample, but I am unable to locate it. Can you point me towards it? The Custom_UI sample doesn't seem to containt what you mentioned.

Also, the technique you described would use the "transforms" approach. When you say to include the transforms as binary files and extract them, are you referring to using the `Payloads` of the `MsiPackage` class?

What about the `InstallCondition` approach as described in the link of my original post?

Thanks again!

**Comment by oleg-shilo** [comment]
> CustomUIDialog sample...

https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUIDialog

> ...are you referring to using the Payloads of the MsiPackage class?

`MsiPackage.Payload` is a concept from the bootstrapper and we are trying to manage the solution within a single msi without any bootstrapper. This is what I meant: 
```C#
var project = new ManagedProject("MyProduct",
                  new Dir(@"%ProgramFiles%\My Company\My Product",
                      new File("readme.txt")),
                      . . .
                  new Binary(new Id("my_transform"), "whatever.file"),
                  . . . 

project.UIInitialized += (SetupEventArgs e) =>
{
    var isAdmin = new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator);

    if (!isAdmin)
    {
        MessageBox.Show(e.Session.GetMainWindow(), "You must start the msi file as admin", e.ProductName);
        e.Result = ActionResult.Failure;
        
        var transform_file= "<transform destination file>";
        e.Session.SaveBinary("my_transform", transform_file); 

        var startInfo = new ProcessStartInfo();
        startInfo.UseShellExecute = true;
        startInfo.WorkingDirectory = Environment.CurrentDirectory;
        startInfo.FileName = "msiexec.exe";
        startInfo.Arguments = $"/i \"{e.MsiFile}\" TRANSFORM:\"{transform_file}\""; // check CLI doco
        startInfo.Verb = "runas";

        Process.Start(startInfo);
    }
}
```

> What about the InstallCondition approach...

Again. `MsiPackage.InstallCondition` is a concept from the bootstrapper.
