### ISSUE TITLE
Custom WPF UI - Show dotNet Licence Prompt as BootStrapp Window

### ISSUE THREAD

**Issue by nadjibnet** [oleg-shilo/wixsharp#389]
Hi,

I'm working on my Custom UI for my BootStrapp. It include:
- dotNet 4.5 Offline Installer (/q /norestart)
- MyProduct msi installer.

When **dotNet 4.5** or grater are **Installed**. Every thing is OK. See the Screenshot below:

![Image 1](https://user-images.githubusercontent.com/39797899/41204538-b7695028-6cdd-11e8-9c4c-aee73385cd8f.PNG)

When **dotNet 4.5** or grater are **NOT Installed**. The Bootstraper show this Licence Prompt as  Window as shown on the screenshot below:

![Image 2](https://user-images.githubusercontent.com/39797899/41204481-d8fe95a0-6cdc-11e8-9a4b-953fac932b8e.PNG)

**Important !!**

**_After multiple retries, I noticed that if the dotNet 4.0 Client Profile is installed on the system, the installer show concretely the bootstrapper UI as on the first picture the 4.5 not installed ._**

Thanks

**Comment by oleg-shilo** [comment]
I am afraid I cannot help you much with this one. The behavior you are observing is fully controlled by WiX bootstrapper runtime. 

I am (only) guessing that what you see on the second image is the UI of the .NET installation that is bootstrapped into your package. 

The important point is that your Custom UI is a .NET application thus it requires .NET to be installed. That's why any bootstrapper always ensures it's installed before the Custom UI is displayed.

**Comment by nadjibnet** [comment]
Yes, sure ! but the dotNet 3.5 is installed by default in Windows 7.

![reg](https://user-images.githubusercontent.com/39797899/41228615-e43ef902-6d70-11e8-8c46-4ff3dfbacb7d.png)

**Comment by oleg-shilo** [comment]
Well, the way WiX bootstraps .NET is completely out of the user control. Thus I am only guessing about the WiX bootstrapping algorithm. May be at runtime it decides that v.3.5 is insufficient for your CA and installs 4.0. For example because your CA was compiled for v4.0 (but not v3.5) runtime. May be something else. 

The direct answer can only be obtained by analyzing the WiX implementation or getting the answer from the WiX team. 

Though there is a simple test that you can do in order to verify if the UI that is displayed is a bootstrapped .NET or yours. 

Change your bootstrapper definition to contain your very CA and a single MSI but no `dotNet 4.5 Offline Installer`. Run your bootatrspper and see if the .NET download/install is still happening. If it does then indeed that .NET install has nothing to do with your code but an internal WiX bootstrapper business. 

And... if indeed it is the case you may try to recompile your BA for .NET 3.5.

**Comment by Xaddan** [comment]
If you plan to install your application on Windows 7 and higher, then you can specify the target platform as .Net Framework 3.5.

I have 2 projects in my solution.
The first project is BA, whose target platform is specified as .Net Framework 3.5.
The second project is an installer with CA, whose target platform is specified as .Net Framework 4.5.

If you plan to install on Windows XP, you will have to accept the second screenshot or write BA on the .Net Framework 2.0.

**Comment by oleg-shilo** [comment]
Do I understand this right, that your previous post is guidance/explanation on how to solve this problem?

**Comment by Xaddan** [comment]
This is my solution of the problem.

I forgot to show my BootstrapperCore.config:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <sectionGroup name="wix.bootstrapper" type="Microsoft.Tools.WindowsInstallerXml.Bootstrapper.BootstrapperSectionGroup, BootstrapperCore">
      <section name="host" type="Microsoft.Tools.WindowsInstallerXml.Bootstrapper.HostSection, BootstrapperCore" />
    </sectionGroup>
  </configSections>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v2.0.50727" />
    <supportedRuntime version="v4.0" />
  </startup>
  <wix.bootstrapper>
    <host assemblyName="???">
      <supportedFramework version="v3.5" runtimeVersion="v2.0.50727" />
      <supportedFramework version="v4\Client" runtimeVersion="v4.0" />
    </host>
  </wix.bootstrapper>
</configuration>
```

**Comment by oleg-shilo** [comment]
Makes perfect sense. Instead of building BA for .NET3.5 re-configure it to target .NET3.5. 

I made this issue into "enhancement".

The next release will have your config file as the default "BootstrapperCore.config" and also updated the code sample to show how to pass custom config file:
```C#
// You can also use System.Reflection.Assembly.GetExecutingAssembly().Location instead of "%this%"
// Note, passing "BootstrapperCore.config" is optional and provided for demo purposes only
bootstrapper.Application = new ManagedBootstrapperApplication("%this%", "BootstrapperCore.config"); 
```

**Comment by Xaddan** [comment]
Glad I could help.
