### ISSUE TITLE
Pass arguments to msi during install

### ISSUE THREAD

**Issue by stefanhallg** [oleg-shilo/wixsharp#400]
Hi
I'm creating a msi installer.  The installer places an exe file in the install dir and a shortcut to the exefile in ProgramMenu.  all ok there.  But I have to pass arguments to the exe file, and those arguments must be set during install.  So I want to be able to run the installer something like this

msiexec /i setup.msi SERVER=net.tcp://xxx/sss.svc  
How can I get the variable, and use it in the ExeFileShortcut "arguments:"

**Comment by oleg-shilo** [comment]
You can usesomething like that ('shorcuts' sample):
```C#
new ExeFileShortcut("Uninstall MyApp", "[INSTALLDIR]yourfile.exe", "[SERVER]")
{
    WorkingDirectory = "%Temp%"
}
```

**Comment by stefanhallg** [comment]
Thanks Oleg.. that was way toooo simple  :)  works like a charm...

**Comment by oleg-shilo** [comment]
This is what `MSBuild.exe MyProject.proj` does:
- builds `MyProject.exe`
- executes `MyProject.exe` in the post-build event; this action will build the msi file

If you want to pass the arguments, you will need either:
- to hard code them in the project file post-build event
- to use some environment variables instead of arguments
- to execute `myproject.exe` not as post-build event but as a CI step
