### ISSUE TITLE
Custom UI for Bootstrapper in WPF

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#401]
Hallo Oleg. i have to create exe installer for few my programs. Sample WixBootstrapper_UI with wpf works great. Only few questions :  
1. is right, that exe before install extract msi is tmp folder and after that begin installation ? 
2. In sample i seen not installdir dialog and no license or type dialogs. Only welcome, progress and exitdialog. How do i add new Dialogs to msi which are being installed ? 
CustomUi.Add accepts only Dialog item but all Dialogs are of System.Type ? 
3. Is Concept for add Package like .NET Framework, for installation are same like in ManagedSetup ? Is there posibility to run installer for .NET Framework before Install my msi or is it not posible ?

**Comment by oleg-shilo** [comment]
>  ...extract msi is tmp folder ...

Most likely yes. This is really the question about Burn engine architecture that I have no info about. But since msi installation can only be done via _msiexec.exe_ executing an msi file on the file system I see no other way but to have msi being stored somewhere in temp folders.

> How do i add new Dialogs to msi which are being installed 

WiX Bootstrapper (Burn) by default shows its own UI. You can configure to show the UIs of the embedded msis. However because of the long standing WiX bug it cannot show CustomUI (EmbeddedUI).  If you want to your bootstrapper to show custom managed msi UI you need to use 'NsisBootstrapper'. See the sample from the latest release. And for the general information on the Bootstrapper topick see this wiki: https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-integration-notes

>CustomUi.Add accepts only Dialog item but all Dialogs...
 
See 'CustomUIDialog' sample.

>Is there posibility to run installer for .NET Framework before Install my msi or is it not posible ?

Yes see Bootstrapper samples (e.g. 'WixBootstrapper_UI').

**Comment by Xaddan** [comment]
Before starting the installation, the bootstrapper caches the installers in the folder 
 "C:\ProgramData\Package Cache"

**Comment by Torchok19081986** [comment]
Thanks for explanation. Sorry for late answer. I was on vaccation 👍 . 
Ist there some tutorial for NSISBootstrapper with dialogs, controls ... ? I need to install NSIS for use it in NSISBootstrapper right ?

**Comment by Torchok19081986** [comment]
Thanks again Oleg. Your answers is always helpfull. i look nsisbootstraper closer. I want only user-friendly installation with exe and some dialogs like licensenumber, sql server install or choose. after it installed on server will be there client-setup .exe or msi for install it on current pc, that all.

**Comment by oleg-shilo** [comment]
Though your users may feel uneasy downloading and running the exe. But it actually may not be your scenario.
