### ISSUE TITLE
Windows installer process stay open after build

### ISSUE THREAD

**Issue by manytwo** [oleg-shilo/wixsharp#42]
In few cases Windows Installer process remain active.
I have seen it when building project, and also after installing my application.

You can reproduce this by creating a project via visual studio.
Create project via WixSharp template  "WixSharp Managed Setup" & Install package nuget.

Generate the solution (the msi file should also been generated), and you will see in process Windows Installer will never stop.

If you kill it, and run the msi for installation, same happend after install. Few Windows Installer are runned, but one is never killed.

Sorry I didn't investigate a lot, I have no more informations/tests.

OS: Windows 10

**Comment by oleg-shilo** [comment]
> In few cases Windows Installer process remain active.

What are you referring to by "Windows Installer process"? It cannot be MSI as it is not a process but a database file, which is hosted by `msiexec.exe` process. If it is indeed `msiexec.exe` then it has nothing to do with the project building process as VS project builds msi but never launches it.

I have to assume that you are talking about the the executable that is created when VS project is built. 

This executable is built from C# file (e.g. `program.cs`) that is what I call "build script". This `exe` if executed invokes the WiX tools in order to produce MSI. At the end of the build the executable is launched either via *.targets or build event. And if this executable is hanging in the memory then there will be something either in this executable itself or in the way it invokes WiX tools.

It is relatively easy to debug this executable - it's just a .NET application. Just kill the currently running/hanging instance of that executable, place your breakpoints and press F5 in Visual Studio. This will show you what is preventing the executable from exiting.

**Comment by manytwo** [comment]
No no I m talking about `msiexec.exe` (called Windows Installer in task manager), this is why I m surprised.
Please can you try the few step I described? I m curious to see if you can reproduce this.
And It also happend when running the msi file.

**Comment by oleg-shilo** [comment]
OK. I see. Indeed during the msi build two instances of `msiexec.exe` are launched. One quickly disappears and another one stays. Though you normally cannot kill that instance ('access denied') and for a good reason - it is a Windows service `msiserver` and it supposed to be running until it decides to terminate itself (e.g. on idle). 

In my experiment this behavior did not prevent me from starting the installation. And I have to say that I see no reason for you to be concerned about it. In fact your original report did not described any actual problem or anomaly.

BTW Wix# never executes `msiexec.exe`. I am guessing WiX tools invoke the service indirectly. At least if I split building process into two phases "generating build.cmd with Wix#" and "running WiX compilers with build.cmd" it is the second phase that launches `msiexec.exe`.

**Comment by manytwo** [comment]
Ok thanks for your explication. It was just a question about a "strange" behavior, because MSI can modify many things on the system, I can't just see an msiexec process always running without ask what is the cause. It is not installing something because it don't lock the msi engine, so there is no real problem, but I m still curious to understand what this process is always running after install, and after a build!

First I was thinking on something not released like error popup in hidden process (I have seen it on another installer engine, but it locked the msi session and no other installation can be launched).
I was also thinking about msi server waiting for reboot to commit last changes, but why at build time?

I close the issue/question as it is not a wix sharp concern, it happend also with pure wix without anything of wixsharp runtime. But if somebody have some information... Please leave it here :)

**Comment by oleg-shilo** [comment]
I can only add that it's not so uncommon for tools to to stay active after the job is done. For example `VBCSCompiler.exe` (interface to Roslyn compiling services) stays a couple of minutes active after C# compilation is complete. This way MS ensures that consecutive compilations are done as quick as possible. Loading/initializing Roslyn services is extremely expensive and without such a "process caching" it would introduce an enormous overhead for every compilation. 

So may be msiexec is trying the same trick....
