### ISSUE TITLE
Postprocessing Files in AfterInstall 

### ISSUE THREAD

**Issue by note-do** [oleg-shilo/wixsharp#455]
Hello, @oleg-shilo 
I have a question about the way how wix# invokes events of ManagedProject, for instance, AfterInstall event. I implement some file manipulation with File.Move() in the subscription of the event. As the result, I have an issue in a case when installation path was a network share, for example, //server/myfolder/
In the case, I get the UnauthorizedAccessException - I can catch it in the log of the installation

`Info: Error UnauthorizedAccessException (   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.__Error.WinIOError()
   в System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   в InterStorageSetup.Components.Data.FileOperations.MoveFile(String source, String target)`

I found that the exception is usually related to issues of permission. Common advise solving the issue is to grant the permission for the account who invoke the process. But I don't understand how can it be that installer can copy files to share, but cannot move them? Are there two separate processes in the installation that have been invoked under different accounts?

**Comment by oleg-shilo** [comment]
> Are there two separate processes in the installation that have been invoked under different accounts?

Yes there are. I know, it's hard to believe but MSI is such an ugly creature that it starts a new process (_rundll32.exe_) for every custom action, including `AfterInstall` event handler. 

BTW, your Wix# schedules `AfterInstall` as elevated custom action, but since it does not help in your case I am afraid you will need to impersonate your routine as the user that has the required permissions.
