### ISSUE TITLE
Uninstall is performed when MSI is executed to upgrade previous version

### ISSUE THREAD

**Issue by feO2x** [oleg-shilo/wixsharp#460]
Hey Oleg,

We've been using Wix# for a few months now to create installers for several applications, and it's been working great so far. Yesterday, we experienced an interesting behavior when deploying one of our applications to production:

- a previous version of the application was already present on the target systems
- when the MSI installer was executed (either by a `Process.Start` from our automatic update feature, or via a manual double-click), it seemed to upgrade the application just fine.
- but when the installer was finished, the application was actually uninstalled

We only use a progress bar UI in our installers, and it showed the typical process: gathering information, installing, removing older versions of the product. The funny thing is that we could not reconstruct this behavior on our own computers nor the customer's staging server. When the MSI installer is executed on a system where the application is not present, the app installs just fine.

For the sake of completeness, here is how we configure our project:

```csharp
var project = new Project(
    appName,
    new InstallDir($@"%LocalAppData%\Company Name\{appName}",
                    new Files(Path.Combine(solutionDirectory.FullName, "ProjectName", "bin", configuration, "*.*"),
                              fileName => !fileName.EndsWith(".pdb") &&
                                          !fileName.EndsWith(".xml"))),
    new Dir("%Desktop%", new ExeFileShortcut(linkName, exeFileLink, string.Empty)),
    new Dir("%ProgramMenu%", new ExeFileShortcut(linkName, exeFileLink, string.Empty)))
{
    GUID = installerGuid,
    Version = AssemblyInfo.Version,
    MajorUpgradeStrategy = MajorUpgradeStrategy.Default,
    UI = WUI.WixUI_ProgressOnly,
    InstallPrivileges = InstallPrivileges.limited,
    OutDir = targetDirectory,
    OutFileName = $"Setup {AssemblyInfo.DisplayVersion}{configurationSuffix}",
    ControlPanelInfo =
    {
        Manufacturer = "Company Name",
        ProductIcon = Path.Combine(solutionDirectory.FullName, "Project", "Resources", "icon.ico"),
        InstallLocation = "[INSTALLDIR]",
        NoModify = true
    }
};
```

Nothing too fancy, I guess. The app is installed with limited privileges to the `%LocalAppData%` folder because the end-users do not have administrative rights (this is what the admins of our customers want). 

**Have you experienced something similar with other installers or do you have a guess what the problem could be?** We have deployed several versions of the application and we never had any problems with the installer being run while a previous version of the app was installed. I'm hitting the end of my understanding about the Windows Installer platform - to my knowledge, the application should not be uninstalled at all in this case. Could this maybe be caused by something like a group policy that is not active in our own company nor the staging server? Or is something going wrong during the removal of the old components that might cause the uninstall?

Thanks for your help in advance.

**Comment by oleg-shilo** [comment]
No I haven't experienced the behavior like that but it is not necessarily without an explanation.

The MSI **major upgrade** model implies that the previous version of the product (if found)  is automatically (and silently) uninstalled. Thus if for any reason the installation phase fails then you end up with the uninstalled product. 

Meaning that MSI warranties the **transnational** installation but not an upgrade.  

I think there is a good chance that in production your setup is failing for some reason. The very reason that does not exist oi your dev/test machines. 

I suggest that you try to install your msi with full logging enabled during the deployment to your production. Thus instead of 
```
Process.Start("<your msi>");
````
you start it as 
```
Process.Start("msiexec.exe", "/i \"<your msi>\" /log \"<log file>\"";
```

**Comment by feO2x** [comment]
Thanks Oleg for your quick reply. I think I have to be more specific: the application is actually not uninstalled (i.e. I can still find it in Apps & features and uninstall it), but the **installation directory is removed** during the upgrade install.

Fortunately, I could reconstruct the problem on the staging server and I created three log files (with verbose logging `/l*v` turned on):

- one with a complete fresh install (executed on my dev computer)
- one with a previous version being upgraded successfully (also on my dev computer)
- one where the upgrade fails (on staging server)

I'm not the best at reading MSI log files, but I specifically searched for the `FileRemove` operation. Here is a miniature overview of the log files and the occurance of `FileRemove` marked in yellow on the scroll bar:

![installer log files miniature](https://user-images.githubusercontent.com/7884158/44399384-b142b480-a547-11e8-9e4f-244b9c8d0f29.png)

As we can see, the fresh install (on the left) never calls `FileRemove`. The working upgrade install (in the middle) contains only one block of `FileRemove` (before the new files are installed), while the erroneous upgrade install (on the right) actually contains two of these blocks. I think the second block is actually the deletion of the target directory.

I'm wondering why the installer performs a second deletion of files and directories in the right case (or why the installer does behave differently on different computers at all). I couldn't find a discrepancy in the overall  actions that the installer performs.

**Is it useful to you if I provide you with the log files?** Of course, I don't want to eat up your precious time.

**Comment by oleg-shilo** [comment]
> Is it useful to you if I provide you with the log files?

To be hones I an not sure neither. 

I am not exactly a true expert in MSI/WiX advanced development. In fact I have developed WixSharp because I wanted developers to be able to abuild MIs without becoming experts in one. Obviously my plan did not work in your case.  :)

You can send me your logs but I wold only be able to detect the most obvious problems there. Something that most likely you've already done.

I suggest you investigate the produces WXS file and see if there anything suspicious.  Having this file may also help when searching in the WiX "online wisdom".

Sorry, I know, it's not the answer you were hoping for.
