### ISSUE TITLE
moidfy .wxs file and use candle and ligh to create the .msi failed

### ISSUE THREAD

**Issue by tcp-wegener** [oleg-shilo/wixsharp#476]
Hi Oleg,

I created a .wxs via Wix#.
1. candle "somthing.wxs"
2. light "something.wixsobj"

then I get this error:
error LGHT0094 : Unresolved reference to symbol 'WixUI:WixUI_ErrorProgressText' in section 'Product:{6FE30B47-2577-43AD-9095-1861EBD5889C}'.

What I have to do, so can work with candle and light?

Thanks in advance
Thomas

**Comment by tcp-wegener** [comment]
Oh sorry. I found it, I have just to copy the commands from the VS output window, right?

**Comment by oleg-shilo** [comment]
Not exactly :)

you can do even better if you call `project.BuildMsiCmd()` instead of `project.BuildMsi()`. This will prepare the all required wxs files and temp dlls and also create a batch file that would run candle and light with the correct args.

As for modifying sources on fly, you can do it without resorting to the batch file approach:
```C#
Compiler.WixSourceGenerated += document =>
    {
        document.Root.Select("Product/Package")
                        .SetAttributeValue("Platform", "x64");
    . . .
```
have a look at "InjectXML" sample it shows all available techniques...
