### ISSUE TITLE
Enviromental variables are not fully supported 

### ISSUE THREAD

**Issue by smth-mn** [oleg-shilo/wixsharp#487]
Trying to use %ALLUSERSPROFILE% env variable found that it makes the build process throw
`Unhandled Exception: WixSharp.ValidationException: WixSharp.Dir.Name is set to unknown environment constant '%ALLUSERSPROFILE%'.`
though in console that const seems to be defined.

Moreover, using %CommonAppDataFolder% turns the situation the other way round. Installer is created fine, but issues during installation process appears.

Of course, it doesn't make great sense while you can encapsulate all the commands in a script, but looks a bit strange

**Comment by oleg-shilo** [comment]
If you are referring to the install dir path like below
```C#
new Dir(@"%ProgramFiles%\My Product",`
```
then be aware that `%ProgramFiles%` is not an environment variable but a WiX constant. WixSharp allows you are to express these constants with canonical WiX syntax `"ProgramFilesFolder\My Product"` or more explicit WiXSharp notation `"%ProgramFiles%\My Product"` with the suffix `Folder` omitted and the name enclosed in double `%` character. 

https://github.com/oleg-shilo/wixsharp/blob/147060418249716c3918dc4033b0b7981099fbf7/Source/src/WixSharp/Compiler.cs#L3386

But since there is no WiX constant "AllUserProvileFolder" you will need to find the correct name and use it instead.

**Comment by oleg-shilo** [comment]
If you want to discover all mapped WiX just execute this code:
```C#
Compiler.GetMappedWixConstants(include64Specific: true)
        .ForEach(Console.WriteLine); 
```
Though the most accurate source of the WiX constants is WiX documentation.
