### ISSUE TITLE
Duplicate ID

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#495]
Hi Oleg.
I decided to upgrade from version 1.6.4.3 to version 1.9.2.0.
And I have errors with duplicate component and folder IDs.
I have folders with the same names (ru-RU) that are in different folders.
Previously, their IDs were:
```
Component.ru-RU
Component.ru-RU.1
Component.ru-RU.2
Component.ru-RU.3
```
Now they look like this:
```
Component.ru-RU
Component.ru-RU
Component.ru-RU.1
Component.ru-RU.2
```
That is, the first two components have the same ID.
I found out that this is due to the new `ResetAutoIdGeneration` method.

**Comment by Alex55040** [comment]
Maybe this helps https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming
section "ID allocation customization".

**Comment by oleg-shilo** [comment]
I will have a look at why the new id allocation algorithm is failing in this case.

In a mean time you can restore the old functionality as below:
```C#
Compiler.AutoGeneration.LegacyDefaultIdAlgorithm = true;
```

**Comment by oleg-shilo** [comment]
I looked at your sample and first thing that I noticed is the `error LGHT0091: Duplicate symbol 'Directory:ru_RU' found. This typically means that an Id is duplicated.`.

However... in the sample you merge multiple projects into a single one:
```C#
Project.MergeProject(new App1().Project)
       .MergeProject(new App2().Project)
       .MergeProject(new App3().Project)
       .MergeProject(new App4().Project);

Project.UI = WUI.WixUI_FeatureTree;  
```
All for projects build OK one by one. When you merge them... it fails. But since you are stepping out of a single project boundaries then it is up to you to ensure uniqueness of IDs between all 4 projects. 

You can use any of the techniques found in CustomID sample: https://github.com/oleg-shilo/wixsharp/blob/67c57624b5bc3db389f35ee6dd540da33070409d/Source/src/WixSharp.Samples/Wix%23%20Samples/Custom_IDs/setup.cs

**Comment by Xaddan** [comment]
Повторю что при использование 1.6.4.3 таких проблем не было.

Посмотри ID, в 'App2.wxs':
'Id="INSTALL_LOCATION_APP2.ru_RU"'

А в 'App1.wxs', где был добавлен 'FileShortcut', он уже по другому выглядит:
'Id="ru_RU"'

Если при объединение проектов ID будет выглядеть примерно так:
`"INSTALL_LOCATION_APP1.ru_RU"`
`"INSTALL_LOCATION_APP2.ru_RU"`
`"INSTALL_LOCATION_APP3.ru_RU"`
`"INSTALL_LOCATION_APP4.ru_RU"`
то это решит проблему.

**Comment by oleg-shilo** [comment]
> I repeat that when using 1.6.4.3 there were no such problems.

I perfectly understand what you are saying. Please be patient.

In order to be able to work on this problem I need to have a test case: a sample VS project that demonstrates that very problem but not a production code. The sample that you shared is not simple and has a workflow that is not intended to be supported(merging projects).

Please try to provide a test case that uses a single individual project (mot merged). Have that `FileShortcut` and I will have a look at it.

In anu case keep in mind that if you ever find the default ID allocation not suitable then you can define your own algorithm or use explicitly defined IDs.

**Comment by Xaddan** [comment]
I added the class `MyInstaller.cs`, which does not use merge projects. There are no duplicate IDs in it, but `FileShortcut` still affects IDs.
[TestInstall.zip](https://github.com/oleg-shilo/wixsharp/files/2533225/TestInstall.zip)
