### ISSUE TITLE
How to show VerifyReady Dialog inbetween the last Custom Dialog and the begin of the installation)

### ISSUE THREAD

**Issue by NeloBorcram** [oleg-shilo/wixsharp#502]
Hi,
I am building a CustomUI setup using some default Dialogs as well but I am not able to find the default VerifyReady Dialog which for instance pops up when I am just using UI = WUI.WixUI_InstallDir instead of ManagedUI:
```
project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                   .Add(Dialogs.Licence)
                   .Add(Dialogs.InstallDir)
                   .Add<MyCustomDialog>()
                   .Add<AnotherCustomDialog>()
                   // <-- here I would like to have the default VerifyReady  dialog
                   .Add(Dialogs.Progress)
                   .Add(Dialogs.Exit); 
```

Is this possible? How do I trigger it?
Thank you a lot!

**Comment by oleg-shilo** [comment]
The `VerifyReadyDialog` has been excluded from the default dialogs of the ManagedUI due to the insignificant practical value for the end user. 

Both MSI and WiX solutions are quite over-engineered  and WixSharp deliberately hides some of the lower value functionality in order to simplify dev experience. `VerifyReady` is a good example of that. 

Of course considering ultimately simple UX of this dialog (two static labels and two bound labels) you can easily implement it by yourself. If you indeed want to do that I suggest you create your project from "Custom UI" VS template and just make a copy of one of the dialogs and modify it to look like VerifyReady.

**Comment by NeloBorcram** [comment]
Thank you for the very fast answer.
I will try to implement it myself then.
