### ISSUE TITLE
ISession does not contain a definition for 'GetEmbededString'

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#521]
Hi

After I updated the nuget package my wixsharp project no longer works
I get  "ISession does not contain a definition for 'GetEmbededBitmap' and the best extension method overload 'Extensions.GetEmbeddedstring(session string) requires a receiver of type 'Session'

please help
Laz

**Comment by geghamyan** [comment]
Hi Laz,

Please consider using _ISession.GetResourceBitmap()_ on ISession object, or alternatively if you use it in managed forms you can use _MsiRuntime.MsiSession.GetEmbeddedBitmap()_. 

The reason the changes were made is because I am working on (unfortunately slowly) on reusing the ManangedUI framework in the burn bootstrapper.

Regards,
Tigran

**Comment by ltemimi** [comment]
Hi
Thanks very much I went through all my dialogues and replaced MsiRuntime.Session with MsiRuntime.MsiSession and it all worked thanks
