### ISSUE TITLE
Write some speicials to msi log

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#524]
Hallo Oleg, 
i tried to write some values into msi installer.log, but session.log doesnt write anything in log. 
I want to write some values from registry and endpoint like installdir for myproduct after install and maybe if customaction was executed or not , only if it possible. 
Log is some confusing, only last 2 sentences looks good . How can i change this ?

**Comment by oleg-shilo** [comment]
I cannot say for sure as there is no context in your description but it should be straight forward. The only case when logging might be affected is elevated/deferred CA, as in this case the session object is disconnected. 

Otherwise it works OK. You can try to use Managed UI and in the `ExitDialog` there will be a "view log" button. This way you will ensure you are opening the right log file.

**Comment by Torchok19081986** [comment]
Thanks oleg. 
I use ManagedUI and my view log looks like that. 
some example: 
=== Logging stopped: 30.10.2018  15:09:27 ===
MSI (s) (FC:30) [15:09:27:151]: Product: My Product -- Configuration completed successfully.
MSI (s) (FC:30) [15:09:27:151]: Das Product was through Windows Installer configured. Produktname: MyProduct. Produktversion: 2.6.1. Produktlanguage: 1033. Hersteller: Mycompany. Sucess - or. Errors new Configuration : 0.
In hole log is each action what msi was executed:  install, removefiles, windowsfirewall, registry, shortcuts etc.
