### ISSUE TITLE
MSI Unistall Shortcut dot not remove the program from ControlPanel(Remove/Add)

### ISSUE THREAD

**Issue by nadjibnet** [oleg-shilo/wixsharp#526]
Hi,
I have noticed that, when I uninstall my app from the shortcut in program-files, my app is uninstalled but it stay exit in the Control Panel Remove/Add Programs.

I think it is because of the Bootstrapper, my app was installed by a Bootstrapper (The MSI is included in).
What can I change in my code to replace the msi uninstaller shortcut by the Bootstrapper shortcut Uninstaller. 

Or What you suggest ?

**Comment by Xaddan** [comment]
You need to uninstall the application using bootstrapper. Set `Visible = false` in the properties of your `MsiPackage` so that the msi installer does not appear in the ARP.

**Comment by Xaddan** [comment]
With the label more difficult.
The delete line looks like this: `"C:\ProgramData\Package Cache\{GUID}\BootstrapperName.exe" /uninstall`

**Comment by oleg-shilo** [comment]
No, I don't know the answer. 

I have checked and it's not clear where that GUID is taken from. 

The bundle has multiple GUIDs defined. 

![image](https://user-images.githubusercontent.com/16729806/50499383-5db81880-0a9d-11e9-8bdf-a6a578cb4f45.png)

Embedded MSI appears in the _'Package Cache'_ exactly where you expect it to be:

![image](https://user-images.githubusercontent.com/16729806/50499448-df0fab00-0a9d-11e9-9b07-5a021b836c86.png)

However the location of the bundle has the GUID based location without any connection to the bundle definition:

![image](https://user-images.githubusercontent.com/16729806/50499489-167e5780-0a9e-11e9-9344-e2e8c5e4246c.png)

This is particularly strange because just 5 years ago according this [post](https://stackoverflow.com/questions/12287372/how-to-set-product-code-of-wix-bootstrapper-install) the location was based on the `Bundle.UpgradeCode`. But clearly today it does not behave this way.

It might be a new Burn feature or... a WiX defect.

**Comment by oleg-shilo** [comment]
Excellent! 
Meaning that `BootstrapperApplicationData.xml` is kind of XML equivalent of MSI-registry information but for WiX bootstrapper.
