### ISSUE TITLE
Advertised shortcut icon is "blank"

### ISSUE THREAD

**Issue by tb2johm** [oleg-shilo/wixsharp#529]
I'm trying to do an advertised shortcut. And the shortcut itself works, but the icon is just a blank paper sheet (like it didn't find any icon). If I use an nonadvertised shortcut, the icon works. Am I doing something wrong?

**Comment by tb2johm** [comment]
Or is it a bug?

**Comment by oleg-shilo** [comment]
The fact that it shows the icon in non advertised mode indicates that most likely you are doing it right.

I suggest you find a canonical WiX sample for advertised shortcut and compare it to WixSharp generated WXS. 

if there is something wrong with WixSharp output I will be able to guide you through.

**Comment by tb2johm** [comment]
I think my example here: https://github.com/tb2johm/WixSharpAdvertiseTest is almost exactly the same as your sample. If I first build my project, and run the install without the _Advertise_ then the icon is shown in the Start menu, but if I run it with the advertise, then no icon.

**Comment by oleg-shilo** [comment]
What I meant is slightly different. WixSharp is a transcompiler. It simply compiles C# into WXS and the rest is done by the WiX compiler and linker. Thus is WiX has some deficiencies (something does not install correctly) then WixSharp cannot possibly address it.

However, if WixSharp introduces some error when preparing WXS code for WiX compilers and this in turn leads to the runtime problems, then WixSharp definitely can do something about it.

And this is what I was trying to understand. Does WixSharp translates C# into WXS inadequately for your use-case?

Let's do it this way:
- Build your (or even my sample) project for advertised scenario. 
- Verify that it fails to associate the shortcut with the proper icon.
- Now collect the produced WXS code and check with WiX documentation if it is composed correctly for the purpose of advertised install.
- If it is, then nothing we can do about it. It's just one of the MSI/WiX limitations.
- However if there is a discrepancy, then I will guide you how to fix it and also will also adjust the WixSharp compiling algorithm so it's fixed in the next release.

**Comment by tb2johm** [comment]
Ok, so minor update... Mostly for future reference.
You need to set the _IconFile_ property on the _FileShortcut_ to a valid icon file, then it works.

**Comment by oleg-shilo** [comment]
Thank you for sharing the solution.

Though I am surprised that this optional parameter is resolved by MSI for normal install but not for the advertised :(
