### ISSUE TITLE
Install Dir Problem

### ISSUE THREAD

**Issue by Christobal25** [oleg-shilo/wixsharp#56]
Hey, 

I have in my Programm an µ in the Name so the Path where the Programm should installed had the µ in the Path, it was in 1.4.2 no Problem, but in 1.4.3 the µ is an __ so the Symbol is not correct resolved.

Thanks

**Comment by oleg-shilo** [comment]
This is an unfortunate side effect of Issue #45 fix. Which triggered illegal characters being escaping. And µ is an illegal character... but for the Id, not the name of the `Directory` element. 

The problem is corrected and the fix will be available in the very next release.
If you don't want to wait you may take the binary (`wixsharp.dll`) form https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples

Or you can alter the dir name in the post-generaion event:
```C#
project.WixSourceGenerated += ...
```

**Comment by Christobal25** [comment]
Thanks for your help
