### ISSUE TITLE
Multiple Custom UI Dialogs

### ISSUE THREAD

**Issue by SiyataDishmaya** [oleg-shilo/wixsharp#566]
The Custom UI Dialog is a powerful feature. Do you have any examples where multiple Custom Dialogs are used in a row where flow is passed from one to another before passing control back to the standard Dialogs? If not, do you have any tips that will help in this?
Thanks

**Comment by oleg-shilo** [comment]
The idea for this feature is to allow an injection of the managed code with visual UI into the standard dialog sequence. This is where the challenge was. But injecting multiple "pages" in the managed dialog is relatively trivial task and should be managed without any extra integration with MSI infrastructure.

Thus the conceptual solution for your use case should be something like that:
- Inject custom dialog as per sample
- Insert in your dialog a panel (_content panel_) that occupies the whole client area except navigation buttons.
- implement multiple "views" (window or user control) that represent your custom dialigs content
- During initialization place your first "view" directly into the _content panel_ (set `Parent`, resize, etc.).
- Update the implementation of the navigation buttons so that when user clicks "_Next_" the second "view" is placed into the _content panel_, and so on. If the button is clicked when the last "view" is visible then invoke the original handler of the "_Next_" button. 
  Similarly implement "Previous" navigation.

**Comment by SiyataDishmaya** [comment]
Thank you!
