### ISSUE TITLE
MSI setup suggests wrong installation folder

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/wixsharp#567]
In my WixSharp project, I'm specifying the root folder as:

```csharp
private static Project createProject(DirectoryInfo tempFilesRoot)
{
    var wixObjects = new List<WixObject>();

    // --

    var rootDir =
        new Dir(
            new Id(@"APPLICATIONROOTDIRECTORY"),
            @"%ProgramFiles%\Zeta Test");

    buildTree(
        rootDir,
        tempFilesRoot);

    wixObjects.Add(rootDir);

    // ...
```

Still, when installing, it suggests "`E:\ProgramFilesFolder`":

![image](https://user-images.githubusercontent.com/415439/51187235-a49a7080-18db-11e9-8cac-0846429227de.png)

The correct path would be "`C:\Program Files`" or "`C:\Program Files (x86)`".

I'm really clueless and checked alle examples, issues here on Github and still found no solution.

When executing `set` on the command line, it outputs, among others, this:

```cmd
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
```

So I do think, my environment variables are correctly set (in case it matters).

**My question:**

How can I acchieve that the default installation folder is being set to the actual program files (or x86) folder?

**Comment by oleg-shilo** [comment]
The problem you are experiencing is caused by the way you are accessing the installation dir.

WiX does not support root directory expressed as path (e.g. `@"%ProgramFiles%\Zeta Test"`). It forces user to use multiple nested elements. This would require creating `Dir` object twice in your case:
```C#
new Dir("%ProgramFiles%",
    new Dir("Zeta Test",
``` 
While WixSharp allows simplified syntax with the full path in a single `Dir` object one needs to be aware about what is happening under the hood. This article explains the details: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#installation-directory.

Thus the solution for your case would be around the correct access to the install dir:
```C#
var rootDir = new Dir(new Id(@"APPLICATIONROOTDIRECTORY"), @"%ProgramFiles%\Zeta Test");
var installDir = rootDir.Dirs[0];
```

**Comment by UweKeim** [comment]
Actually [your suggestion in this issue](https://github.com/oleg-shilo/wixsharp/issues/180#issuecomment-335644914) helped me out.

I'm now doing:

```cs
private static Project createProject(DirectoryInfo tempFilesRoot)
{
    var wixObjects = new List<WixObject>();

    // --

    var myRootDir = new Dir(new Id(@"INSTALLLDIR"), "Zeta Test");
    var rootDir = new Dir(@"%ProgramFiles%", myRootDir);

    buildTree(myRootDir, tempFilesRoot);

    wixObjects.Add(rootDir);
   
    // ...
```

And until now, everything looks OK and working.
