### ISSUE TITLE
Condition on RegValueProperty?

### ISSUE THREAD

**Issue by WayneHiller** [oleg-shilo/wixsharp#593]
Is there no way to specify a condition on RegValueProperty? The reason I am asking is because I load some 
 values into Properties and everything works fine on the first install. If I then run the install again without uninstalling it acts like the prev install did not finish correctly. I do not get the Repair, Remove etc. If I comment out the RegValueProperty lines it all works as expected. I would like to only call RegValueProperty if Condition.NOT_Installed returns true.

I also noticed Folder entries in the XML output when writing to the Registry. That does not seem correct.

```
<Component Id="Registry.1" Guid="6fe30b47-2577-43ad-9095-1861b742561a" Permanent="yes" KeyPath="yes">
   <RegistryKey Root="HKLM" Key="Software\My Company\My Product">
         <RegistryValue Id="InstallDir" Type="string" KeyPath="no" Value="[INSTALLDIR]" Name="InstallDir" />
    </RegistryKey>

    <CreateFolder />
    <RemoveFolder Id="ProgramFilesFolder" On="uninstall" />
</Component>
```

**Comment by oleg-shilo** [comment]
OK there are a few problems here.

First one is superficial. Neither `RegistryKey` nor `Registry` value WiX elements do not have condition attribute. Thus one needs to set the condition to the parent component:
```C#
regVal.AttributesDefinition += $";Component:Condition={yourCondition}";
```

However the second problem is more interesting. Running the very install again must trigger change/repair sequence and addressing it by injecting some _conditions_ probably is not the right way to solve the problem.

I had a look at the "Registry" sample in the distro and was able to trigger change/repair sequence by executing the msi again after the first installation:
![image](https://user-images.githubusercontent.com/16729806/53293332-1ee8d980-3826-11e9-89aa-a87fa2923fa5.png)

The only change you will need to do to the sample is to ensure Mondo UI so you can access change/repair buttons on UI instead of doing it from the ControlPanel: 
```C#
project.UI = WUI.WixUI_Mondo;
```

**Comment by WayneHiller** [comment]
I ended up just using a ManagedAction to read the Registry values and assign them to Session Properties. I used the Condition.NOT_Installed condition on the action.

As for the second part it seems Windows Installer will also display the Change, Repair, Remove page even when UI is set to WUI.WixUI_FeatureTree which is what I am using.

This code shows the issue I was having before switching to use a ManagedAction.

`
     private static void Main() {
            var fullSetup = new Feature( "App" ) {
                IsEnabled = false
            };

            var project =
                new Project( "MyProduct",
                    new Dir( @"%ProgramFiles%\My Company\My Product",
                        new File( fullSetup, @"Program.cs" ) ),
                    new RegValueProperty( "ADDLOCAL", RegistryHive.LocalMachine, @"Software\My Company\My_Product", "Features", "App" ),
                    new RegValue( fullSetup, RegistryHive.LocalMachine, @"Software\My Company\My_Product", "Features", "[ADDLOCAL]" ).SetComponentPermanent( true )
                ) {
                    GUID = new Guid( "6f330b47-2577-43ad-9095-1861ba25889b" ),
                    UI = WUI.WixUI_FeatureTree,

                    PreserveTempFiles = true
                };
            project.BuildMsi();
        }
`

The first time you run it, it seems to work fine. Running it a second time displays this dialog:

![image](https://user-images.githubusercontent.com/1186731/53303030-74b78480-381a-11e9-8710-b8393bbb266c.png)

Anyway I have it working now so it is no big deal.

**Comment by oleg-shilo** [comment]
Not a problem. 
But you need to remember that "Windows Installer will also display the Change, Repair, Remove" only if the UI type you specified contains this dialog.  `WUI.WixUI_FeatureTree` does not include this dialog but `WUI.WixUI_Mondo` (full UI) does. This explains why you don't see the dialog. 

BTW even if the UI you are using does not have this dialog the change/repair mode is still supported. This is what your very sample produces in ControlPanel:

![image](https://user-images.githubusercontent.com/16729806/53335589-fe1ca300-394f-11e9-8d4b-bb5c664f7b17.png)

As you can see you can invoke both _change_ and _repair_. Though because you don't have the dialog for that moth modes will simply trigger reinstallation.

**Comment by WayneHiller** [comment]
I think the Change, Repair Remove is built into the Default dialogs, it will only be displayed if you run the installation again after it has already been installed. If you comment out the RegValueProperty line in my example code it will work properly and be displayed the second time you run the install (without uninstalling first).  The RegValueProperty seems to cause an issue when the install is run a second time and is already installed.

Running a second time without first uninstalling with the RegValueProperty line in the code.

![image](https://user-images.githubusercontent.com/1186731/53343356-11366100-38c5-11e9-8b26-61b947c0d29f.png)

Uninstall first. Comment out the RegValueProperty line, build and install (Note that you will need to Select the App Feature to be installed manually).  Running a second time without first uninstalling with the RegValueProperty line commented out in the code. 

![image](https://user-images.githubusercontent.com/1186731/53343541-712d0780-38c5-11e9-8597-34cf896427d3.png)

![image](https://user-images.githubusercontent.com/1186731/53343566-7ee28d00-38c5-11e9-9bb8-e7e4e20810ef.png)
