### ISSUE TITLE
Is it possible to suppress the "UAC prompt" text if UAC is not enabled?

### ISSUE THREAD

**Issue by jimfoye** [oleg-shilo/wixsharp#604]
Well, Oleg, you know we WixSharp users are never completely satisfied :smile: 

I like this prompt when UAC is enabled, but when UAC is not enabled, it looks a little funny. I've even had users ask me about it. Is there any way for WixSharp to detect that UAC is not enabled and just hide it in this case?

**Comment by Xaddan** [comment]
```C#
/// <summary>
/// Determines whether the current user is administrator.
/// </summary>
static public bool IsAdmin()
{
    var p = new WindowsPrincipal(WindowsIdentity.GetCurrent());
    return p.IsInRole(WindowsBuiltInRole.Administrator);
}
```

**Comment by oleg-shilo** [comment]
>...WixSharp users are never completely satisfied ...

I expect nothing less :o)

It is actually a good idea. I only don't know the detection algorithm from the top of my head. And google reviled nothing. 

Note it is not about detecting if the current execution context is elevated (running as admin) as it will never be. It is about detecting if UAC is actually enabled as an OS setting . Exactly as you put it in the title.

If you find a bit of time and can develop such an algorithm I will be happy to incorporate it into the UI dialogs.

Jim, quite possibly we have already discussed it... I am really unhappy about the WixSharp UAC handling solution. I spent endless hours trying to use even the dirtiest tricks. But none of them work reliably. I have nothing to work with. If only that smart bottom who made this brilliant decision to allow UAC prompt to hide itself spend a little more time analyzing the implications of that decision!!!  

Yes I feel frustrated.... From one side I had users who complained because they though WixSharp is responsible for hiding the UAC prompt. So I put the message saying "hey it's not me". And also have users like yours who is puzzled about this very message.

That's why if I can at least keep a half of the users happy I am keen to do that.

BTW you can unconditionally disable UAC prompt if you prefer this way:   
```C#
AutoElements.EnableUACRevealer = false;
```

**Comment by jimfoye** [comment]
I do believe you originally put this in as a result of an issue I opened, where I was asking if there is anything you can do about the UAC prompt being minimized.

I can totally understand the frustration and aggravation dealing with this and with everything related to the MSI Monster. I (and I'm sure a lot of other people) are amazed that you've done so much work on WixSharp, and it's most appreciated!

Of course it would be nice if Microsoft would not abandon the technologies that their users are so dependent on. This is a typical Microsoft show, they create something that their users need and become dependent on, and then all the developers who worked on it cash out their stock options and move on, and the technology becomes frozen (MSI) or even abandoned (Silverlight, and even WPF!). They will never go back and fix or improve anything.

Most days I think the folks at MS really have no idea what their customers are actually doing.

Anyway, I had forgotten to mention in my original post that I have tried turning this off and it's not working. (Of course I'm ambivalent about that, if UAC is enabled, then I would actually like the prompt to be there). My bad on that.

I set this just inside main() (I'm working in F#):


```
let main _ = 
    AutoElements.EnableUACRevealer <- false
    project.BuildMsi() |> ignore
    0

```
But it doesn't work:

![image](https://user-images.githubusercontent.com/4249676/54283036-3be21400-456b-11e9-8a25-d36c5f5dde57.png)

Any ideas?

**Comment by oleg-shilo** [comment]
> But it doesn't work...

Oh... then it is a defect. Will have a look at it. 

And you are spot on in your observations about MS attitude towards their own technologies the relationship with the customers. I am not totally bashing them. They are responsible for some real beauties. It's just sometimes impossible to not to wander about some small silly mistakes that cause an extreme usability damage while bringing no other benefits whatsoever.

I did a bit further googling and found that there is a reg key that indicate UAC being enabled. Registry - not ideal but probably good enough to ease the pain :o)

Will work on it.

**Comment by oleg-shilo** [comment]
My apologies `AutoElements.EnableUACRevealer` controls the **revealer** (routine that sets the focus on UAC prompt) but not the warning message. 

Fixed, now you can use `AutoElements.UACWarning = "";` to hide the message unconditionally.

An addition to this you the message will be hidden if UAC is disabled or the process is already elevated:
```C#
if (!WindowsIdentity.GetCurrent().IsAdmin() && Uac.IsEnabled())
{
    this.waitPrompt.Text = Runtime.Session.Property("UAC_WARNING");
    this.waitPrompt.Visible = true;
}
```

Will be available in the next release (in a few days).

**Comment by jimfoye** [comment]
Awesome! Finally I will be able to start delivering the quality software my customers expect of me! :laughing:

**Comment by jimfoye** [comment]
I did some testing with 1.9.5.1 today.

I replaced 

`AutoElements.EnableUACRevealer <- false`

with

`AutoElements.UACWarning <- ""`

I didn't extensively test this setting, it worked in the first case I tried, and I assume it's likely to work correctly all the time.

(Is the revealer routine what makes the UAC prompt appear in the foreground rather than on the taskbar? If so, that seems to work well; I noticed today that the UAC prompt never appeared minimized).

I then commented that out line, and this time I decided to get a little more systematic about testing the appearance of the warning message. The three variables I used were

User admin/non-admin
UAC enabled/disabled
Install per-user/per-machine

By "per user" here I mean I have this line

`project.InstallScope <- Nullable InstallScope.perUser`

and by "per machine" I mean, I comment out that line (so, fall back to default WIX# behavior, which I assume is per machine).

There are still some cases where the message is showing up, but shouldn't be. What do you think?

![image](https://user-images.githubusercontent.com/4249676/55516010-b3b6d200-5631-11e9-92d8-61c030ac16e4.png)

**Comment by oleg-shilo** [comment]
Thank you, an excellent stats capture.
I will have a look.

But before I do, lets check that we are talking about the same things. :)

> I replaced ....EnableUACRevealer with UACWarning...

No, they are very different creatures and one does not replace (nor affect) another one.

- _**EnableUACRevealer**_
It enables routine that just before starting that actual elevated install tries to change the focus to any desktop application so windows UAC will understand that the **system UAC prompt dialog** should appear in the foreground rather than on the taskbar. You are right. This trick works only in ~70% of case :o(  

- _**UACWarning**_
It is a runtime text value of the label on the the text on the **WixSharp progress dialog**.

I expect `AutoElements.UACWarning <- ""` to be the most reliable way of unconditionally remove the warning text from WixSharp progress dialog. Thus you can always use do it this way if for whatever reason you cannot solve the prompt problem any other way. But you are saying that sometimes it does not work?

Are we on the same page here? Do I miss anything from your description?

**Comment by jimfoye** [comment]
I think suppressing the warning does always work. The remainder of my testing was without the warning suppression.

I'm assuming that Wix# wants to be smart about this and if it knows the UAC prompt is not going to appear, then it will not show the warning. This seems to be the case when the user is an Admin and UAC is not enabled (row two in the test results). If UAC is not enabled, shouldn't the result be the same for a non-admin user?

If the installation is per-user, then the Windows Installer will never elevate, right? At least, that's what I read somewhere. So that's the last four rows - in all these cases WIX# could safely hide the warning? But maybe that rule is not 100% reliable.

I do realize that in the grand scheme of things, the presence or absence of this warning text is not that big a deal, and I can just suppress it entirely (thanks for that option). I guess I'm just a perfectionist.

**Comment by jimfoye** [comment]
I just noticed that when I set UACWarning to an empty string, this warning is emitted:

> warning CNDL1006 : Property 'UAC_WARNING' does not contain a Value attribute and is not marked as Admin, Secure, or Hidden.  The Property element is being ignored.

**Comment by oleg-shilo** [comment]
Yeah, I will need to ensure empty string is rather converted in the constant value (e.g. `<empty>`) that does not trigger warning and yet sets empty text to the UAC warning text.

> I do realize that in the grand scheme of things, the presence or absence of this warning text is not that big a deal...

Yes, agree. But this only means that this enhancement is of a lesser priority that's it. I still take it as an opportunity to improve UX and yes "Wix# wants to be smart" :). Of course within the limits. 

Anyway I am assigning this issue to a lesser priority but it is in the backlog nevertheless.

You see, I am also a hopeless perfectionist :)
