### ISSUE TITLE
After installing WixSharp to WPF project, then project cannot be built and ran

### ISSUE THREAD

**Issue by tomasfil** [oleg-shilo/wixsharp#611]
Hello, I have fully working console app building msi. But I want to be able create like msi creator bundle, to setup few things. 
But after I install wixSharp to my WPF project from nuget, it cannot be ran, not even on brand new created poject. This error appears: 

`Severity	Code	Description	Project	File	Line	Suppression State
Error		The "SetEnvVar" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin" directory.	OutlookOSP_MSI_Creator			
`

Can I do anything about it? Thanks.

**Comment by oleg-shilo** [comment]
The problem is caused y the fact that you probably copied the project file form some other VS project created from WixSharp project template. By doing so you have left out some vital project items. In this case _SetEnvVar.dll_. Ironically the latest WixSharp VS project templates do not longer rely on _SetEnvVar_ thus you would not have any problems if you copied the project file of the latest format.

Anyway, you can easily fix the problem by manually removing the following lines from your project file:
```xml
<UsingTask AssemblyFile="$(SolutionDir)packages\WixSharp.1.9.3\build\SetEnvVar.dll" TaskName="SetEnvVar" />
<Target Name="BeforeBuild">
  <SetEnvVar Values="ProjectName=$(ProjectName);ProjectDir=$(ProjectDir);SolutionName=$(SolutionName);SolutionDir=$(SolutionDir);ConfigurationName=$(ConfigurationName)" />
</Target>
```

**Comment by tomasfil** [comment]
Hello.

Thanks for the answer, but actually, it happens even for brand new solutions, once I install wixSharp from nuget.

I tried to locate your lines, but nor the csproj file, or any other file in solution contains it.

**Comment by tomasfil** [comment]
Ok, I did figure it out, I did try to download wixsharp from releases and installed it with bat file.

Once I unninstalled it, reinstalled wixsharp from nuget, it started working again.
