### ISSUE TITLE
Project ID 

### ISSUE THREAD

**Issue by digitalsigi** [oleg-shilo/wixsharp#615]
Hi Oleg,
I have set the project.id to "\*" as I did in former plain WIX Project Element. This is base on the recommendation in the "WIX Developers Guide", saying WIX will generate a uiniqe ID for every compile.
Now in Wix# when I set the Id="*", the resulting ID is the same as the UpgradeCode with just the last digit changed. The same happens when I set Id to any other value.
Maybe I misunderstand the concept, but I believe that the project.id should be unique for every newly generated msi package to guarantee upgrade functionality.
How can I handle this?

**Comment by oleg-shilo** [comment]
The identity management in MSI and WiX is grossly overengineered.

Please read this section: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming

It explains how WixSharp is trying to untangle this problem.

**Comment by digitalsigi** [comment]
Hi Oleg,
thx for the link, I think I got the point. However, life is not without history.
So my "old" WIX XML is obviously "over-engineered" as MSI and contains some elements based on misunderstandings. 
However, the question is, how to go on to overcome the pitfalls and shortcomings without forcing the enduser to a manual uninstall before install upgrade procedure. I guess #614 is related to this and the view of msi on component id may explain my experience. Is there any further hit you can give me to get out of this situation and migrate to Wix#?

**Comment by oleg-shilo** [comment]
As for the IDs (GUIDs) you don't have to follow the WixSharp 'single guid' model. You can still allocate the IDs explicitly as you would do it for an orthodox MSI:
 
```C#
project.ProductId = new Guid("<desired_guid>");
project.UpgradeCode = new Guid("<desired_guid>");
```

As fro components, the difference in WiX vs WixSharp approaches is actually not that important. It would be if ine installs and upgrades **components** not product (e.g. minor upgrade). But since you support only major upgrade then having extra components with WixSharp would not make any difference. Well... I don't expect it to :)
