### ISSUE TITLE
WixSharpAddInSetup.exe" "/MSBUILD:WixSharpMsiSetup" "/WIXBIN:"" exited with code -532462766

### ISSUE THREAD

**Issue by Aharon-Tam** [oleg-shilo/wixsharp#622]
This annoying error keeps showing up when compiling the WixSharp setup for Excel Addin.
Is there a log file to see where this is coming from?

**Comment by oleg-shilo** [comment]
You can troubleshoot it by building a "build batch file" instead of msi itself.

```C#
project.BuildMsiCmd();
```
This will emit batch file that runs pure WiX compilers (candle and light) to build an msi. This way you can see where exactly the error is coming from. Otherwise the all log output is intercepted and redirected in the VS build output window.

As a side note, there were some problem with VS WixSharp templates, which had similar symptoms. The problem has been addressed now. I suggest you grab the latest templates from here: https://marketplace.visualstudio.com/items?itemName=OlegShilo.WixSharpProjectTemplates

Test them with the fresh project and then move your content into it.
