### ISSUE TITLE
WixUI_InstallDir also shows FeatureTree dialog

### ISSUE THREAD

**Issue by sdc4** [oleg-shilo/wixsharp#63]
WixSharp 1.4.3 Wix 3.11 RC 2

I've set the project.UI property to "WUI.WixUI_InstallDir", but also the "FeatureTree" dialog is shown.
This list of dialog's is included in generated .wxs file

 <DialogRef Id="BrowseDlg" />
      <DialogRef Id="DiskCostDlg" />
      <DialogRef Id="ErrorDlg" />
      <DialogRef Id="FatalError" />
      <DialogRef Id="FilesInUse" />
      <DialogRef Id="MsiRMFilesInUse" />
      <DialogRef Id="PrepareDlg" />
      <DialogRef Id="ProgressDlg" />
      <DialogRef Id="ResumeDlg" />
      <DialogRef Id="UserExit" />

``` XML
      <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="LicenseAgreementDlg">1</Publish>
      <Publish Dialog="LicenseAgreementDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg">1</Publish>
      <Publish Dialog="LicenseAgreementDlg" Control="Next" Event="NewDialog" Value="InstallDirDlg">1</Publish>
      <Publish Dialog="InstallDirDlg" Control="Back" Event="NewDialog" Value="LicenseAgreementDlg">1</Publish>
      <Publish Dialog="InstallDirDlg" Control="Next" Event="SetTargetPath" Value="[WIXUI_INSTALLDIR]" Order="1">1</Publish>
      <Publish Dialog="InstallDirDlg" Control="Next" Event="NewDialog" Value="CustomizeDlg" Order="2">1</Publish>
      <Publish Dialog="InstallDirDlg" Control="ChangeFolder" Value="[WIXUI_INSTALLDIR]" Property="_BrowseProperty" Order="1">1</Publish>
      <Publish Dialog="InstallDirDlg" Control="ChangeFolder" Event="SpawnDialog" Value="BrowseDlg" Order="2">1</Publish>
      <Publish Dialog="CustomizeDlg" Control="Back" Event="NewDialog" Value="InstallDirDlg">1</Publish>
      <Publish Dialog="MaintenanceWelcomeDlg" Control="Next" Event="NewDialog" Value="MaintenanceTypeDlg">1</Publish>
      <Publish Dialog="MaintenanceTypeDlg" Control="Back" Event="NewDialog" Value="MaintenanceWelcomeDlg">1</Publish>
      <Publish Dialog="MaintenanceTypeDlg" Control="RepairButton" Event="NewDialog" Value="VerifyReadyDlg">1</Publish>
      <Publish Dialog="MaintenanceTypeDlg" Control="RemoveButton" Event="NewDialog" Value="VerifyReadyDlg">1</Publish>
      <Publish Dialog="ExitDialog" Control="Finish" Event="EndDialog" Value="Return" Order="9999">1</Publish>
      <Publish Dialog="CustomizeDlg" Control="Next" Event="DoAction" Value="Action3_ShowCustomDialog" Order="1">1</Publish>
      <Publish Dialog="CustomizeDlg" Control="Next" Event="NewDialog" Value="VerifyReadyDlg" Order="2"> Custom_UI_Command = "next" </Publish>
      <Publish Dialog="CustomizeDlg" Control="Next" Event="EndDialog" Value="Exit" Order="2"> Custom_UI_Command = "abort" </Publish>
      <Publish Dialog="VerifyReadyDlg" Control="Back" Event="DoAction" Value="Action3_ShowCustomDialog" Order="1">1</Publish>
      <Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="CustomizeDlg" Order="2"> Custom_UI_Command = "back" </Publish>
```

I still have to pay attention to anything else?

Thank you very much.

**Comment by oleg-shilo** [comment]
Cannot comment much on this one. Though a few obvious things that are not clear...
You mentioned `project.UI` and I am not sure why your .wxs contains any dialogs at all. Are you building your own dialog sequence instead of relying on WixUI_InstallDir?
____
To be honest I found native MSI dialogs extremely limiting and abandoned any effort to improve developer experience for them. You just cannot make a racing horse out of a donkey. Thus it is only available as a "lab" effort.

It was the reason why I implemented ManagedUI where you have both full control and full power. And also you don't need to abandon your programming experience and learn something rather obsolete (MSI/WiX UI markup).

Have a look at ManagedUI may be it is what you need?

**Comment by sdc4** [comment]
Thank you for your comment.

I have injected one custom dialog, via InjectClrDialog, in the sequence, could this be the problem?

Thank you for your hint. I will try ManagedUI.

**Comment by oleg-shilo** [comment]
>I have injected one custom dialog, via InjectClrDialog,...
It could. You'll need to look into generated wxs to see what's going on. But... I would really recommend to go with ManagedUI. Any time I would go with it. There is only one scenario (caused by WiX defect) where  InjectClrDialog has advantage - Bootstrapper with multiple MSIs displaying their own UI. Thou according WiX team v4 will have it fixed.

**Comment by sdc4** [comment]
@oleg-shilo Thank you very much for you answer.
