### ISSUE TITLE
MajorUpgradeStrategy, why not uninstall first with Step.InstallInitialize

### ISSUE THREAD

**Issue by Sushifix** [oleg-shilo/wixsharp#634]
Hallo Oleg,

I have a similar requirement as #342 .

What I wondering is that an upgrade is installed first before uninstalling. Schedule is set to: 
UpgradeSchedule.afterInstallInitialize. But even if with UpgradeSchedule.afterInstallFinalize, the software will be upgrated first and then uninstalled. Even though I understand the general idea to upgrade first and then unstall.

```
            productProj.MajorUpgrade = new MajorUpgrade
            {
                Schedule = UpgradeSchedule.afterInstallInitialize,
                DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
            };
```

I used this sample to verify it.

https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/WixBootstrapper/setup_upgrade.cs

Thank you for your help

**Comment by oleg-shilo** [comment]
> What I wondering is that an upgrade is installed first before uninstalling.

Sorry, but it is not how MSI major upgrade works.

MSI claims to uninstalls previous version first. I know, in some specific scenarios the behavior may indicate otherwise but I am positive that MSI does the way it claims to do. Though keep in mind that it is the behavior for **Major Upgrade** model. Minor Upgrade is a completely different story and WixSharp simply (and deliberately) does not include this feature.

The usual cause of misinterpreting install/uninstall order is that one is making the conclusions based on the deployment artifacts being present on the target system.

However the correct way will be to log the installation events. Either with MSI logging or... just pop up message boxes with the indication of the installation stage/state.  Exactly as Managed Setup sample  "Setup Events" does.

**Comment by Sushifix** [comment]
The logging say the same as I find out and you confirm " Though keep in mind that it is the behavior for Major Upgrade model". Okay, thats a pitty, because I cannot use this simple approach to uninstall an other Software (which is forein) first. Similar cases here use the bootstrapper embeeded UI which is not suittable for me (silent install). And to run the uninstall in a custom action is not possible due to the limitation that only one msi can run at the time.

Any other hints? Otherwise I need to remove the suff manually which is of cause a high effort.

**Comment by oleg-shilo** [comment]
> I cannot use this simple approach to uninstall an other Software (which is foreign) first

That's new. It is something that needed to be in the problem description from the start.

It makes sense now. Major Upgrade model is the model for upgrading the same product to a new version. And during the upgrade the old version is uninstalled first. However if you are trying to uninstall  different product then it is no longer "upgrade" and I do not expect Major Upgrade to work at all. 

> Any other hints? Otherwise I need to remove the suff manually which is of cause a high effort.

You can restrict your setup to always run with UI. Why you need GU sequence? Because UI sequence is excluded from the restriction of one active MSI session at the time. One can have many MSI UI session at the time but only a single one in the active installation phase. Thus you can uninstall your exterrnal product from one of the US sequence custom action and then proceed with your setup.

Have a look at "Simplified Bootstrapper" example. It follows practically the same scenario except it installs an external MSI before installing itself and you will need to change it to do uninstall.

**Comment by Sushifix** [comment]
I am not so sure, that WIX detect or undserstand that this is a "foreign" setup, because the GUID is the same. And from a functional point of view it run an uninstall, but in the wrong order. The solution would be so simple, if the "Schedule" element in MajorUpgrade work in some way, but it doesn´t matter what I set, the uninstall will be run AFTER the installation which does not help.

To run with UI always is not an option because my organisation need to run it without UI.

Yes, I will double check the bootstrapper possibilities. That would be a perfect place to do some custom uninstallation. I will come back with my finding. Thank you!

In the meantime, any hints are welcome.

**Comment by Sushifix** [comment]
Currently I understand that the bootstrapper is the one that "override" the behaviour that I expect from the documentation.

That are my findings:

1.	MSI Packages work as expected. UpgradeSchedule.afterInstallValidate will uninstall first then install
2.	With Bundles (burn) a bootstrapper will destroy this behaviour. Burn call always install first then uninstall
3.	Ref: https://stackoverflow.com/questions/15156081/wix-bundle-upgrade-a-new-version-of-msi-is-installed-before-the-old-version-is
4.	Ref: http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/Burn-upgrades-td7582052.html
5.	Ref: https://support.firegiant.com/hc/en-us/articles/230912387-Bundle-chain-execution-order- 
6.	Ref: https://sourceforge.net/p/wix/mailman/message/32999772/

I wish I would find a way where I can override the schedule of the bootstrapper, but only solutions I found was done by overriding methods in custom C++ bootstrappers.

Any idea with some magic inject xml? Remember I do not have any GUI

**Comment by oleg-shilo** [comment]
Well, then it is quite a revelation. MSI MajorUpgrade model is in direct unresolvable conflict with Burn upgrade model!

I am not sure what is the solution path WiX team had in mind when they introduced that reversed model. I don't know how one can change it without resorting to the use of non-Burn bootstrapper.   :o(

If you eventually find some "magic xml" I will be able to help you to incorporate it but otherwise I have nothing to offer you within Burn solution.

Should you decide to go with a custom bootstrapper have a look at the WixSharp samples:

![image](https://user-images.githubusercontent.com/16729806/57765495-ee3f7e80-7748-11e9-80f0-d85a2601eadb.png)

A custom bootstrapper is nothing else but an application that contains multiple msi files embedded as resources. This application simply extracts the msi files one by one and runs them with `Process.Start("msiexec.exe", $"/i \"{msi_file}\"")`. That's it. One can easily implement this simple logic.

The complexity of Burn bootstrapper comes not from the complicated business logic but from:
- the need to provide a generic setup launcher/bundle engine
- the need for a generic declarative way of defining multiple MSI/exe/WebDownload packages
- the need for complicated algorithm of converting declarative syntax into a runtime behavior algorithm.
- the solution that needs to satisfy ALL spectrum of ALL possible deployment scenarios
  
Though if you have a luxury if needing to implementing only your specific deployment scenario then the task is actually quite simple.

**Comment by Sushifix** [comment]
Yes, a custom bootstrapper ist the one that would really simplified the task (change order, do a custom uninstallation). If I try to do a uninstallation command in a custom action (inside msi) I will be blamed with a error that say only one installer task can be run. The only choice is really the bootstrapper.

I was wondering why this important (exsiting) component cannot be customized in such was to change/add functions. That would be perfect. But no overridables...

Out of your samples and notes to that I am not sure if an own bootstrapper fit to my needs. As you say, there a many aspects including further major upgrades.

Another idea that came up is to live with it to not change the order of uninstall last and to just install new versions in "new" directories. E.g. "My Product\2.0", then it doesn´t matter that an uninstall will be run after the installation in case of an major upgrade. Of course, absolut not perfect, especilly if you merge data.

**Comment by oleg-shilo** [comment]
Bingo!

Let's look how ClickOnce does it. Mind you ClickOnce is a result of MS taking on board all ugly lessons learned fro the MSI struggle.

Every install goes into the new dedicated dir. 

And another prominent sample....
You may have guessed it... WiX

![image](https://user-images.githubusercontent.com/16729806/57770247-36639e80-7753-11e9-8d89-f49af7ff37ce.png)
