### ISSUE TITLE
Cannot use PathGetDirName

### ISSUE THREAD

**Issue by fschlaef** [oleg-shilo/wixsharp#653]
I am completely unable to use string.PathGetDirName() with 1.9.7.

`CS0121	The call is ambiguous between the following methods or properties: 'WixSharp.Extensions.PathGetDirName(string)' and 'WixSharp.Extensions.PathGetDirName(string)'`

I don't understand this error, why is the call "ambiguous" between two identical functions ?

**Comment by oleg-shilo** [comment]
> I don't understand this error...

It means that the same method signature is implemented in two different assemblies.
This is an unfortunate side affect of both WixSharp.dll and WixSharp.Msi.dll being bundled together.  It will be fixed in a day or two. But in a meant time avoid using the extension method and use `System.IO.Path.GetDirectoryName()` instead.

**Comment by oleg-shilo** [comment]
Fixed in 
Revision: 8e71e154921ed278539c160239124d6127c4f942
Release v1.9.8
