### ISSUE TITLE
AutoElements.UACWarning should be visible when uninstalling

### ISSUE THREAD

**Issue by fschlaef** [oleg-shilo/wixsharp#657]
Hello,

I think `AutoElements.UACWarning` should be displayed on uninstall, as the UAC behavior is exactly the same (sometimes stays in taskbar).

**Comment by oleg-shilo** [comment]
`AutoElements.UACWarning` defines the string that is to be displayed by the custom UI during **install.** It in fact cannot be "displayed on uninstall" simply because MSI does not allow custom UI dialogs during **uninstall**. Basically MSI is fully responsible for interacting with user on uninstall.

And "_[UAC dialog]_ sometimes stays in taskbar" during uninstall is just another illustration of the fact that this problem is not related to WixSharp and is a fundamental usability flaw of Win UAC focus management and its integration with MSI. 

WixShar is simply trying to draw user attention to the problem  but it cannot fix it or even do anything to ease this painful user experience.    

Sorry, I don't think it is the answer you were hoping for.

**Comment by fschlaef** [comment]
No problem, I've been accustomed to MSI limitations (and many, **so many** flaws) recently, I was wondering if it was a Wix# decision or not.

Since this is not a Wix# bug, I'm closing this. Thank you for answering 👍
