### ISSUE TITLE
How to remove wisharp files *.g.wxs from version control

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#661]
Hi
The wixsharp generated files are causing a lot of TFS (team services) conflicts with other team members. 
Is it correct to think the files do not need to be tracked by git? If so I tried gitignore and gitattributes to untrack them to no avail.

Please help. Thanks

**Comment by oleg-shilo** [comment]
Yes, `*.g.wxs` are not needed at all. They have been added on dev demand for assisting with troubleshooting. You can safely exclude them with gitignore. The syntax will be something like that: 
```
**/wix/*.g.wxs
```

**Comment by AndersJuul** [comment]
Hi Oleg, 
Is it possible to not generate the file? Or at least not modify my project file?

**Comment by oleg-shilo** [comment]
Yes it is possible. 
Instead of `WixSharp` NuGet package use `WixSharp.bin`. It will not modify the project. Though then building the project will simply compile the builder console application `{ProjectName}.exe`. And you will need to execute this app from your project post-build event. 

The rest is the same.

**Comment by AndersJuul** [comment]
Fast reply! Thanks! And precisely what I was looking for!

**Comment by ltemimi** [comment]
Brilliant this is also what I was looking for as it makes code review a lot easier. Thanks very much Oleg

**Comment by oleg-shilo** [comment]
You are very welcome guys 😄
