### ISSUE TITLE
Equivalent of "WixQuietExec64"? 

### ISSUE THREAD

**Issue by nathanbedford** [oleg-shilo/wixsharp#662]
Hello! I'm trying to run a script using Powershell, and this particular script needs to be run in the 64-bit context.  I know Wix has "WixQuietExec64" for this sort of thing, but I'm just finding "WixQuietExecAction" in WixSharp. Am I missing something?

I used 'dark' to look at the binary that 'WixQuietExecAction' is using, and I can see that WixCA is 32-bit (at least for my project), and I'm pretty sure that's what's giving me grief.  I proved this out by making a custom action to execute the Powershell script - the 32-bit very gave me the same error, but the 64-bit version worked as expected.

Any help would be appreciated!

For what it's worth, this Powershell script is running "Remove-WebApplication" to clean up some items in my IIS site.

**Comment by oleg-shilo** [comment]
As an immediate idea I think you can consider forking a 64 powershell process in the `project.AfterInstall` event. Easy to implement, control and troubleshoot. And you will be already elevated. WiX has prepackaged `WixQuietExecAction` simply because executing a custom user routine is tricky. With Wix# it's is not. So why not to do it in C# in after install?

**Comment by nathanbedford** [comment]
Thanks for the answer @oleg-shilo, I ended up doing exactly that in a custom action.  I'll check out project.AfterInstall though too, good tip!
