### ISSUE TITLE
Are other event types supported besides `Click` events for buttons?

### ISSUE THREAD

**Issue by LatteAno** [oleg-shilo/wixsharp#719]
Are other event types supported besides `Click` events for buttons?

For instance, I want to react to radio-button selection change, this way:

```
			// 
			// RadioButtonsGroup
			// 
			this.RadioButtonsGroup.BoundProperty = "PRODUCT_TYPE_TO_INSTALL";
			this.RadioButtonsGroup.ControlType = WixSharp.Controls.ControlType.RadioButtonGroup;
			this.RadioButtonsGroup.EmbeddedXML = radioButtonGroupXmlContent;
			this.RadioButtonsGroup.Hidden = false;
			this.RadioButtonsGroup.Id = "RadioButtonsGroup";
			this.RadioButtonsGroup.Location = new System.Drawing.Point(12, 97);
			this.RadioButtonsGroup.Name = "RadioButtonsGroup";
			this.RadioButtonsGroup.Size = new System.Drawing.Size(247, 108);
			this.RadioButtonsGroup.Text = "What to install .Text?";
			this.RadioButtonsGroup.Tooltip = null;
			this.RadioButtonsGroup.WixAttributes = null;
			this.RadioButtonsGroup.WixText = "What to install .wixText?";
			this.RadioButtonsGroup.EnabledChanged += Changed;
```

And then run e.g.:
```
		private void Changed(object sender, EventArgs e)
		{
			this.Do(ControlAction.DoAction, nameof(CustomActions.LogInstallationType));
		}
```

That code above doesn't work, but is something similar anyway possible?

**Comment by oleg-shilo** [comment]
> Are other event types supported besides Click events for buttons?

As far as I know now. Unfortunately MSI native UI is shockingly limited. OK, I'll need to correct myself. Embarrassingly limited.

That's why MS introduced another UI hosting approach _Embedded UI_, which allows one to have a normal UI implemented in any language/framework. WixSharp provides a ready to go _Embedded UI_ scaffolding which is "Managed UI" VS project template. If you use it then you can do in your UI absolutely anything. Anything that you would do in your desktop UI application. 

As everything it does have some limitations but rather minor.

**Comment by LatteAno** [comment]
I'm trying to postpone the embedded UI path as it means building the whole UX from scratch...

Thank you for all your help!

**Comment by oleg-shilo** [comment]
> ...building the whole UX from scratch...

Not exactly. The ""Managed Setup - Custom UI" VS project template comes with the reagy to go dialogs that repeat layout and UX of the all the most important native MSI dialogs.
