### ISSUE TITLE
Cannot get installation cost of features 

### ISSUE THREAD

**Issue by TheToughGuy** [oleg-shilo/wixsharp#722]
![DiskCostDlg](https://user-images.githubusercontent.com/39625895/65313809-eaa38480-db8c-11e9-80c6-ba83821fda1c.png)
I am trying to recreate the DiskCostDlg from wixUI in a wixsharp installer, the cost steps seem to be there but I do not see how to access the information and the dialogue is missing from the managedUI dialogs.

**Comment by oleg-shilo** [comment]
Indeed ManagedUI does not include this dialog due to the low value and high effort associated with implementing such a dialog. Obtaining the size of the partitions is not a problem. The required setup space is a challenge. 

If you eventually solve the problem please share the solution and I will include it in the ManagedUI sequence.
