### ISSUE TITLE
error for FirewallException

### ISSUE THREAD

**Issue by said1231231231** [oleg-shilo/wixsharp#748]
Hi Oleg.
I want to use FirewallException and i have a problem.
I'm taking a test case FirewallException in your samples and it works.
but if I change the culture:
    project.Codepage = "1251";
   project.Language = "ru-ru";//"ru-ru";
   project.Encoding = System.Text.Encoding.UTF8;
it doesn't work. what is the reason?
Thanks

**Comment by oleg-shilo** [comment]
I don't know the answer but if you take and compare the WXS before and after the change then may be you will get some clue.

**Comment by said1231231231** [comment]
![CompareResult](https://user-images.githubusercontent.com/10078333/67391742-f3321500-f5a7-11e9-8fba-d29fd34c304f.jpg)

Compared.The only difference is in the language settings. I think that the reason is deeper-in the features of WIX. Thanks.

**Comment by oleg-shilo** [comment]
> I think that the reason is deeper-in the features of WIX.

I think so too. Really do not see how :(

I thought , maybe some strings are forming the FW exception algorithm (e.g. they are getting compared at runtime). But they are address and port - strings that are not affected by localization...

If you find the solution please share it here. I think it can be useful for others.

**Comment by said1231231231** [comment]
hi, Oleg.
I solved the problem like this.
I have tried for a long time to bring the localization files to the desired level, but to no avail-wix does not see the changes. In the end I got to the description:
https://wixtoolset.org/documentation/manual/v3/howtos/ui_and_localization/specifying_cultures_to_build.html
and the Msi file was assembled as needed.
The bottom line is that if there are not enough localized messages, then you need to refer to the EN-Us culture as follows: project.Language = "ru-ru; en-US"; then wix searches for the missing strings in the EN-US culture.
your test case ..wix#\wixsharp-master\Source\src\WixSharp.Samples\Wix# Samples\FirewallException\setup.cs. look like this:
![Безымянный](https://user-images.githubusercontent.com/10078333/67670339-be95d300-f984-11e9-8005-7afa4dd2deff.png)

**Comment by oleg-shilo** [comment]
Fantastic. Txs for sharing.
I have updated the sample with your localization code.

**Comment by said1231231231** [comment]
Thanks. Your project helps me a lot in my work. I wish you luck.

**Comment by oleg-shilo** [comment]
It should not generate any error. The sample (from the release) contains the offending code commented out:

https://github.com/oleg-shilo/wixsharp/blob/76451f85e57671f0d13fca122663984063b7ab6c/Source/src/WixSharp.Samples/Wix%23%20Samples/FirewallException/setup.cs#L31-L39

The reason is that the sample is not about the localization but the use of `FirewallException`. 

However, I am willing to update it and to include the required *.ru.wxl. Would you be able to share it? I cannot type in Russian.

**Comment by said1231231231** [comment]
Hello. Well, a little later. This needs to be tested. I'm a little busy right now. I need to finish the current project.

**Comment by Xaddan** [comment]
If in the indicated example change the language as "ru-ru", then the following errors appear:
![image](https://user-images.githubusercontent.com/14925308/69079726-1095ba00-0a54-11ea-8180-cd9f8eeece4a.png)
![image](https://user-images.githubusercontent.com/14925308/69080043-ac272a80-0a54-11ea-86ed-a2a0f100165d.png)
These errors are due to the fact that in Wix there are no localizations of these lines for the Russian language.

Original lines can be found [here](https://github.com/wixtoolset/Firewall.wixext/blob/master/src/wixlib/en-us.wxl).

Localization in Russian:
```xml
<?xml version="1.0" encoding="utf-8"?>
<WixLocalization Culture="ru-ru" xmlns="http://schemas.microsoft.com/wix/2006/localization">
  <String Id="msierrFirewallCannotConnect" Overridable="yes">Не удалось подключиться к брандмауэру Windows.  ([2]   [3]   [4]   [5])</String>

  <String Id="WixSchedFirewallExceptionsInstall" Overridable="yes">Конфигурирование брандмауэра Windows</String>
  <String Id="WixSchedFirewallExceptionsUninstall" Overridable="yes">Конфигурирование брандмауэра Windows</String>
  <String Id="WixRollbackFirewallExceptionsInstall" Overridable="yes">Откат исключений для брандмауэра Windows</String>
  <String Id="WixExecFirewallExceptionsInstall" Overridable="yes">Установка исключений для брандмауэра Windows</String>
  <String Id="WixRollbackFirewallExceptionsUninstall" Overridable="yes">Откат исключений для брандмауэра Windows</String>
  <String Id="WixExecFirewallExceptionsUninstall" Overridable="yes">Удаление исключений для брандмауэра Windows</String>
</WixLocalization>
```

**Comment by oleg-shilo** [comment]
Thank you.
Done. Waiting for release.
