### ISSUE TITLE
Using WPF-based external UI from Add/Remove Programs?

### ISSUE THREAD

**Issue by BillHenning** [oleg-shilo/wixsharp#751]
Hello,

I am new to WixSharp, and have started working with it based on recommendations from others.  I started building my own WPF-based installer UI based on your example here (https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/External_UI/WpfSetup).  I have it working great, and it looks spectacular.

To start with, I have been just using the small stub MSI you used in your WpfSetup sample.  Now I'm about to start building my own MSI using WixSharp.  But before I do that, I noticed something.

After we run the "WpfSetup.exe" that is the external WPF-based UI, there is a Windows Add/Remove Programs entry for the MSI.  However pressing the "Uninstall" button there uses the MSI's built-in dialogs instead of calling into the "WpfSetup.exe" with the external UI.

I've read through the various documentation and I know there are many ways Wix supports UI customization, but being new with all this, my head is spinning.  Is there a way we can have the entry in Add/Remove Programs just have an "Uninstall" button (no "Modify" button) and have that Uninstall button call back to our .exe with the custom external UI instead of using MSI dialogs?

Thanks in advance for the help.  I've really enjoyed using WixSharp so far as the core of my installer's external UI.

**Comment by sonicbhoc** [comment]
In your ProductInfo, make sure NoRemove is true. If your custom installer has an option to remove the program, the only button you want available is Change, which should run your installer with the custom UI again. Try setting NoRemove, NoModify, and NoRepair all to true and see what happens.

**Comment by oleg-shilo** [comment]
I don't think you can achieve it. 

External UI is nothing else but a fancy GUI launcher that invokes _MSI runtime_ method against your msi file. This GUI collects user input and then proceeds with the installation. 

Windows has another launcher for that (default one) _msiexec.exe_.  It has no own GUI so it "asks" _MSI runtime_ to use its own default GUI. 

_MSI runtime_ can also use custom GUI (EmbeddedUI), which is not an external GUI app but a user supplied routine embedded in the msi. Msi file is marked in a special way so _MSI runtime_ knows to trigger embedded UI instead of the default one. Though both EmbeddedUI and MSI default UI are UIs that are part of msi installation sequence. This is quite different to the _External UI_, which is simply a launcher with UI and it is not part of the msi installation sequence.

ARP only "knows" how to invoke MSI UI either default or embedded one. For repair/modify it can be either one and for uninstall it can only be the default one.

That's why ARP cannot invoke your external UI (external app).   :o(

Saying that I cannot completely exclude that there is some MSI magic that is in the registry where one can specify the command line string to be invoked on "repair/modify". Then you can potentially re-raut the execution to your external UI.

**Comment by BillHenning** [comment]
Thank you for the reply Oleg.  I think that for now we will disable the Modify button and will have the Uninstall button just directly execute the MSI's uninstall procedure with progress UI.  We mostly care about the new install experience using our nice external UI.
