### ISSUE TITLE
Files() with feature and dirs without files

### ISSUE THREAD

**Issue by juvo64** [oleg-shilo/wixsharp#76]
Hi,
I want to include subfolders controlled by a feature, e. g.
```
 var project = new ManagedProject("MyProduct",
			new Dir(@"%ProgramFiles%\My Company\My Product", 
					new Dir(myFeature, "f1", 
							new Files(myFeature, @"f1\*.*"))));

```
In my example f1 is a folder including an empty folder f2 and a folder f3 containing one file test.txt

The empty folder f2 is going to the feature "Complete" and not to "myFeature":
```
   <Feature Id="myFeature" Title="myFeature" Absent="allow" Level="1" Description="Test">
      <ComponentRef Id="Component.INSTALLDIR" />
      <ComponentRef Id="Component.test.txt" />
      <ComponentRef Id="ProgramFilesFolder.My_Company.My_Product" />
      <ComponentRef Id="ProgramFilesFolder.My_Company" />
    </Feature>

    <Feature Id="Complete" Title="Complete" Absent="allow" Level="1">
      <ComponentRef Id="f2_.EmptyDirectory" />
      <ComponentRef Id="ProgramFilesFolder.My_Company.My_Product" />
      <ComponentRef Id="ProgramFilesFolder.My_Company" />
    </Feature>
```
Thus f2 won't be installed when only "myFeature" is selected.
Shouldn't Files(...) add the given feature to all files and folders?

Thanks for your help.

**Comment by oleg-shilo** [comment]
The sample either incomplete or was executed under older version of Wix#.

The current release (v1.4.4.1) produces the following wxs:
```C#
<Feature Id="MyFeature" Title="MyFeature" Absent="allow" Level="1">
  <ComponentRef Id="Component.INSTALLDIR" />
  <ComponentRef Id="f2_.EmptyDirectory" />
  <ComponentRef Id="Component.f3_" />
  <ComponentRef Id="Component.test.txt" />
  <ComponentRef Id="ProgramFilesFolder.My_Company.My_Product" />
  <ComponentRef Id="ProgramFilesFolder.My_Company" />
</Feature>
```
I have attached the complete sample: [Issue #76.zip](https://github.com/oleg-shilo/wixsharp/files/1030807/Issue.76.zip)

**Comment by juvo64** [comment]
I'm using VS 2015 and copied your example into a solution, got  a fresh wix# package from nuget, but I'm still not getting your result. What do I miss?
My sample: [MyIssue76.zip](https://github.com/oleg-shilo/wixsharp/files/1030911/MyIssue76.zip)

**Comment by oleg-shilo** [comment]
It's not you. I am missing something. I was testing your code against current codebase assuming that the relevant functionality is the same as the last release. This is where I am wrong - it was some change in WildCard resolution. 

I am just a few steps away from making the release but I don't want to release without verifying that this issue is addressed.

Can you please do a simple test. Remove all your packages and add manual reference to the assembly from  git: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/WixSharp.dll

Ensure you set working dir in the project options and run the build script with F5:
 
![image](https://cloud.githubusercontent.com/assets/16729806/26483809/3fe01de2-4232-11e7-9c94-f42681c7df81.png)

If the result is as expected I will be proceeding with the release.
Txs

**Comment by juvo64** [comment]
Now everything looks fine :-)
```
    <Feature Id="MyFeature" Title="MyFeature" Absent="allow" Level="1">
      <ComponentRef Id="Component.INSTALLDIR" />
      <ComponentRef Id="f2_.EmptyDirectory" />
      <ComponentRef Id="Component.f3_" />
      <ComponentRef Id="Component.test.txt" />
      <ComponentRef Id="ProgramFilesFolder.My_Company.My_Product" />
      <ComponentRef Id="ProgramFilesFolder.My_Company" />
    </Feature>

```
Again: thank you very much!

**Comment by oleg-shilo** [comment]
Cool. Txs. 
Will do the release over weekend.

**Comment by oleg-shilo** [comment]
The release v1.4.5 is out. 
Closing it now.
