### ISSUE TITLE
Custom UI with bundled Bootstrapper

### ISSUE THREAD

**Issue by trilok567** [oleg-shilo/wixsharp#793]
Hello, 
I am building a Installer for our product and it requires to install a couple of pre-requisites. We have build an Installer with default UI(RtfTheme.xml). As an enhancement we are trying to link with a custom UI with EULA, Progress of Pre-requisites, Install Path Ui input and few config settings. 

Can I get some sample(s) pointing to these requirements?

Thanks in advance.
Trilok

ps: Wixsharp is wonderful in saving our time from code revamp from existing WIXtoolset

**Comment by oleg-shilo** [comment]
Thank you, I am glad WixSharp is helping you.

Unfortunately showing MSI internal custom UI from the bandle is impossible due to the long standing WiX bug. Read this [wiki](https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-integration-notes), section "_Q: Why setting DisplayInternalUI to true works for native MSI package UI but not for the EmbeddedUI?_"

One of WixSharp users even contributed an alternative bandle approach to overcome this problem. See [NsisBootstrapper](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs) sample

**Comment by trilok567** [comment]
![snipped](https://user-images.githubusercontent.com/5064168/73050632-7f552080-3ea6-11ea-91aa-5c9a25a3c932.PNG)

Hello @oleg-shilo , Thanks for your reply. A part of the Ui should look this way. Didnot really understand, how Nsis bootstrapper would work here. 

Trilok

**Comment by oleg-shilo** [comment]
You may create an individual msi for each of:
- Angular
- Node.js
- Your DB
- . . .

Then chain then in bootstrapper either WiX Burn or NSIS.

If I was facing something like your use case I would go with a simple WiX Burn bootstrapper and no UI for individual MSIs. 

And if you truly need UI then either use bootstrapper app custom UI or better yet a GUI config utility it is a product configuration that you are trying to do from UI.
