### ISSUE TITLE
Can I use your tool to parse MSP files?

### ISSUE THREAD

**Issue by Eldertri** [oleg-shilo/wixsharp#798]
In my task, I need get patch info - upgrade code, product version, required target product version. 
Does your product include such features?

**Comment by oleg-shilo** [comment]
Not sure.
 
WixSharp does include the portion of API for parsing MSI files but I cannot say if this portion is sufficient for parsing all file formats supported by MSI technology (e.g. *.msp).

Note, this API is implemented by MS and WixSharp simply tunnels the user calls into the actual implementation of the API in `msi.dll` . That's why it's close to impossible to say if WixSharp "includes such features".  

Sorry, I know its not the answer you were hoping for.
