### ISSUE TITLE
Install WixSharp in a class library

### ISSUE THREAD

**Issue by ayman-eltemsahi** [oleg-shilo/wixsharp#811]
I have 2 projects to generate MSIs, each project will generate one, and I have some shared code between them so I put it in a shared Class Library and installed WixSharp in the 3 projects.

When building the solution, the class library fails to build because it tries to run the dll file of the class library after compilation.

`
The command ""********************\TestWix\ClassLibrary1\bin\Debug\ClassLibrary1.dll" "/MSBUILD:ClassLibrary1" "/WIXBIN:"" exited with code 9020.	ClassLibrary1			
`

The error is generated without writing any code, it's enough to install WixSharp in the class library project. 

Is there a way to stop WixSharp from running the generated app after compilation?

**Comment by oleg-shilo** [comment]
This is because when you add WixSharp package you effectively modify the way your project is built. And the project itself is expected to be a "console app" project and the output of the project build is expected to be an MSI file. Not your case. You want it to be an assembly.

What you need to change is the package name to ["WixSharp.bin"](https://www.nuget.org/packages/WixSharp.bin/)

As for the project structure, instead of having a shared class lib (assembly) I would opt to the shared source code so you don't need to include your shared assembly in the MSI payload. Just less headache...

**Comment by ayman-eltemsahi** [comment]
Yes, now works :), thank you.
