### ISSUE TITLE
Project Afterinstall

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#82]
Hallo, i have some Problem with Managed Setup - CustomUI. In my Setup Project i use Standardtemplate and in project.AfterInstall += project_AfterInstall i need to show state of Installation, but project_Afterinstall Event appears during ProgressDialog. In Managed Setup Project appears MessageBox with Installationstate correctly.  
Is there something doesnt work correctly in Afterisntall event or how do i show MessageBox after Install in Managed Setup - CustomUI ? 
Can someone help me with this. Thanks for answers.

**Comment by oleg-shilo** [comment]
The behavior you observe is caused by the execution model implemented by MSI. 
It maintains two independent sequences: _InstallUISequence_ and _InstallExecuteSequence._ 

The _project_AfterInstall_ handler is scheduled for after _InstallFiles_ action/step (see [Managed-Setup-Model wiki](https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model)). Bothe sequences have this step executed thus in both UI and non-UI scenarios the even is fired. 

However, in _InstallExecuteSequence_ the after-InstallFiles action is practically the last step whereas in _InstallUISequence_ some dialogs are still shown and being in transition.

Thus I guess the after-InstallFiles time point happens after the instillation is completed but before user exits the UI progress dialog. 

If you are rather interested (not in "AfterInstall" but) in "AfterUIComplete" then you need catch that moment and fire your routine form the UI (e.g. on ProgressDialog closed). 
```C#
static void Project_UILoaded(SetupEventArgs e)
{
        e.ManagedUIShell.OnCurrentDialogChanged += ...
 }
```

A good sample for events is in the "Managed Setup/Setup events" sample.

**Comment by Torchok19081986** [comment]
Thanks Oleg for explanation. I will try it as well in my App Installation and give some feedback.

**Comment by Torchok19081986** [comment]
Works fine. Your Example was good. thanks.
