### ISSUE TITLE
Backup and restore application data during repair/upgrade

### ISSUE THREAD

**Issue by noctis0430** [oleg-shilo/wixsharp#820]
I'm using WixSharp 1.11.0 and I need to backup some application data (registries, configuration files, binaries) during a repair/upgrade process. For the backup process, I've tried to do so with `ManagedProject.Load` event. Backup of configuration files and binaries works, but the backup of registries failed with `Requested registry access is not allowed`.  

How should I do?

**Comment by oleg-shilo** [comment]
It is because the event handler is not elevated. Basically you need to run
your routine as admin if you want to do what you are trying to do there

However a berrter approach would be to open the registry key for read only
operation. In this case you do not need elevation. And by default registry
api is trying to open the key for read-write.

It makes sense. You are only need to read registry...




-- 
Oleg Shilo
--------------------------------------------------------------------------------------------
Website: http://www.csscript.net
E-Mail: csscript.support@gmail.com

**Comment by noctis0430** [comment]
Ahh, silly me 🤦‍♂️. Didn't notice that I'm actually trying to read the registry value with write access. Thanks for the tips and your valuable time!

**Comment by oleg-shilo** [comment]
Glad to help.
