### ISSUE TITLE
Localization with managedUI

### ISSUE THREAD

**Issue by Tenjim** [oleg-shilo/wixsharp#828]
Hi there,

I have tried to use a managedUI for customDialog like wixsharp samples.
We have an issue when we define multi language for localization. 
like this : `project.Language = "en-US,fr-FR";`

We have noticed when we use a managedUI, we had a french msi in english but when we look on the msi => all actionText are translated in french.
Thereby managedUI take only english as default localization.

On another side, when we use the default managedProject UI, it's work when we have two different msi with two targets languages.

Does wixsharp have a specific method to solve this problem?

in the code below, you'll have the setup.cs we use for : 

```C#
static public void Main(string[] args)
{
	var project = new ManagedProject("ManagedSetup");
	UACRevealer.Enabled = true;

	project.ManagedUI = new ManagedUI();
	

	project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
        .Add<LicenceDialog>()
	.Add<MyProduct.GdprDialog>()
	.Add<InstallDirDialog>()
	.Add<MyProduct.VerifyrReadyDlg>()
	.Add<MyProduct.CustomProgressDialog>()
	.Add<ExitDialog>();

	project.ManagedUI.ModifyDialogs.Add<WelcomeDialog>()
	.Add<MyProduct.CustomProgressDialog>()
	.Add<ExitDialog>();
	project.ControlPanelInfo.Manufacturer = "MyProductFacturer";
	project.SourceBaseDir = @"";
	project.Platform = Platform.x64;
	project.Package.AttributesDefinition = "Platform=x64";
	project.AddBinary(new Binary(new Id("GdprRtf"), @"..\..\Resources\MyProductFacturer_US.RTF"));

	project.Include(WixExtension.Util);
	project.Language = "en-US,fr-FR";
	project.LicenceFile = @"..\..\Resources\MyProductFacturer_EULA_US.rtf";
	project.PreserveTempFiles = true;

	project.BuildMultilanguageMsi();

}

```

Thank in advance for your time !

**Comment by oleg-shilo** [comment]
The biggest problem with MS multi-language support is that ... it is not supported. The same way as CPU multi-target (x86 vs x64) is not supported neither. Yes MSI is such an old technology that it does not support transparent runtime switching and does require one to create a specific msi for a specific target system.

Thus all work around attempts (including WixSharp) are just work around and may not get you too far in some cases.

Thus `BuildMultilanguageMsi` simply builds two msi files `en` and `fr` and then generates conversion en->fr script and embeds it into the `en` msi so at runtime the conversion can be triggered at runtime if French OD is detected. This is the recommended MSI/WiX technique.

Note the order of the languages in `project.Language = "en-US,fr-FR";` is **very** important.
Read more here: https://github.com/oleg-shilo/wixsharp/wiki/Localization

I suggest you 

1. Create a simple "Hello World" en/fr setup with native UI and see if it works with your build process. 
2. Then convert it to ManagedUI so you can ensure there is no hiccup with managed UI integration.

Step `#1` is well tested and documented so most likely you will be able to handle any problems there by yourself. 
If step `#2` fails then I will have a look at it. Just in case there is something missing there.

**Comment by Tenjim** [comment]
Thank for your fast reply. 

What I can confirm is that we have already done an simple sample without ManagedUI. 
It's when we use ManagedUI that take only the default language => en.

A work around of this, is to build the project per language we want.

**Comment by oleg-shilo** [comment]
OK, it does make sense. 
ManagedUI simply takes the strings from the embedded wxl file and since during the build it was only one file embedded (en-US) then it is the only language you can see.

I will try to see if it is possible to extract the strings not from the resource file but from the MSI table. This may work but it means sticking with the MSI unelegant localization model. But it may be the way....

In a mean time I have created the sample that shows the intended localization technique of the ManagedUI: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/MultiLanguageUI/setup.cs

The only tricky part here is to understand what language to use at startup. Checking the therad `UICulture` will not help as it will be set to the project language, which is English anyway.
  
So the options are:
- Use OS language
- Check MSI runtime for the current MSI language (not sure if MSI allows that)
- Let user choose the language.
