### ISSUE TITLE
Adding language resources

### ISSUE THREAD

**Issue by gw-ubunye** [oleg-shilo/wixsharp#850]
Forgive me if this has been asked and answered elsewhere.

As you know language resources are compiled to dll's which are put into sub directories of each project's output folder. 

Now, if you have multiple features in your installer, how do you added these dll's to the installer project based on features? Since they all have to go to the same language specific sub folder under the installation folder, e.g.

```C#
var projectA = new Project("MyProject")
                {
                    Dirs = new []
                    {
                        new Dir("[INSTALLDIR]", new Dir("de", new DirFiles(@"pathToRoot\de\*.dll")),
                            new Dir(_featureA, "de", new DirFiles(@"pathToProjectA\de\*.dll")),
                            new Dir(_featureA, "de", new DirFiles(@"pathToProjectB\de\*.dll")))
                    }
                };
```

I get a Duplicate symbol error when compiling my project.

Thanks.

**Comment by oleg-shilo** [comment]
Since you are using wildcards  there is always a possibility that you can pick a few filses with the same name even though from the different location.

Thus you have to resolve these duplications manually. 

You can do it either removing the dulpicates after calling  `project.ResolveWildCards()` or by specifying the predicate as the second parameter in the constructor. So it does not pass through a file if it is already there.

Have a look at the `WildCard Files` sample for ideas.

**Comment by gw-ubunye** [comment]
Thanks for your reply Oleg. I should have been clearer about the error I get:

> Duplicate symbol 'Directory:INSTALLDIR.de' found. This typically means that an Id is duplicated.

Obviously all the resource dlls have to go to the same language specific sub-directory under the installation directory ("de" in this case). I have verified that there are no duplicates in the folders, only the folder name itself is a duplicate - which it has to be.

**Comment by oleg-shilo** [comment]
Closing it as I am not sure if it is still an active issue. 
Reopen if it is and I will schedule the investigation.
