### ISSUE TITLE
First Icon Selected of taskbar when installing

### ISSUE THREAD

**Issue by Tenjim** [oleg-shilo/wixsharp#858]
Hi oleg,

Want to ask some question about this case.
I had  the behavior to have selected the first icon of the taskbar when you install some package is a bit wierd.

As I already searched into the community, I have seen that wierd behavior is for force UAC prompt.
Can you explain me why you do that ?
If you don't do that, what's happen ?

There is an update of this issue and a solution to avoid that behavior ?

Thanks in advance.

**Comment by oleg-shilo** [comment]
It was an attempt to address the usability bug of the Windows UAC prompt implementation. The attempt was only partially successful. So partially that I cannot really suggest it even though it will work in some cases very well.

Read the Limitation point that starts with "ManagedUI, as well as all other implementations of EmbeddedUI," at this page https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios

>Can you explain me why you do that?

To avoid other aps stealing focus from your setup UI and effectively completely hiding UAC prompt so that it can only be found as a blinking item on the taskbar.

> If you don't do that, what's happen?

Nothing shocking :)
But you may be asked by your users "why I don't see the UAC prompt dialog". 
But since the work around is not reliable anyway, I see no drama in disabling UAC revealer completely.
```C#
UACRevealer.Enabled = false;
```

**Comment by Tenjim** [comment]
Hi Oleg, 
Thank to your answer about it.

We'll check on Wix side or maybe C++ can do an workaround with wix.

**Comment by oleg-shilo** [comment]
I gave up :)

But if you do find a good work around please share it so I can include it in Wix#.
