### ISSUE TITLE
Problems with CommonAppDataFolder generating wrong install script

### ISSUE THREAD

**Issue by sylvesp** [oleg-shilo/wixsharp#865]
This code:

	var project = 
		new ManagedProject("My Product Name",
			new Dir(@"%CommonAppDataFolder%\Folder_A",
					new WixEntity[]
					{
						new Dir("SubFolder1", new WixSharp.File(@"c:\temp\Dockerfile")),
			                        new Dir("SubFolder2", new WixSharp.File(@"c:\temp\Dockerfile"))
					}));

Will generate the proper installation into the folders
C:\ProgramData\Folder_A\SubFolder1
and
C:\ProgramData\Folder_A\SubFolder2

BUT

	var project = 
		new ManagedProject("My Product Name",
			new Dir(@"%CommonAppDataFolder%",
					new WixEntity[]
					{
						new Dir("SubFolder1", new WixSharp.File(@"c:\temp\Dockerfile")),
			                        new Dir("SubFolder2", new WixSharp.File(@"c:\temp\Dockerfile"))
					}));

Will not do a substitution of % CommonAppDataFolder% and will install into

C:\CommanAppDataFolder\SubFolder1
and
C:\CommonAppDataFolder\SubFolder2

It should be installing into:
C:\ProgramData\SubFolder1
and 
C:\ProgramData\SubFolder2

Peter

**Comment by oleg-shilo** [comment]
This is the solution to your problem. And I will provide the explanation a bit later.
```C#
Compiler.AutoGeneration.InstallDirDefaultId = "CommonAppDataFolder";

var project = new Project("My Product Name",
                    new Dir(@"%CommonAppDataFolder%",
                            new WixSharp.Dir("SubFolder1", new WixSharp.File(@"c:\temp\Dockerfile")),
                            new WixSharp.Dir("SubFolder2", new WixSharp.File(@"c:\temp\Dockerfile"))));

project.BuildWxs();
```

**Comment by oleg-shilo** [comment]
Now let's talk about it. 

Problem

Wix# does need to detect the root directory that is an installation directory in the dir structure. It is required for integrating the setup algorithm with the UI. Thus UI has a dedicated dialog (InstallDirDialog) that allows user to alter the default installation directory. It is typically the first directory with multiple children:
``` C#
new Dir("A1",
    new Dir("B1",
        new Dir("C1"),
        new Dir("C2"),
.
└── A1
    └── B1
        ├── C1
        └── C2
// Installdir is B1 
```
```C#
new Dir("A1",
    new Dir("B1",
        new Dir("C1",
            new Dir("D1"),
            new Dir("D2",
                new Dir("E1"),
                new Dir("E2"),
                new Dir("E3"),
.
└── A1
    └── B1
        └── C1
            ├── D1
            └── D2
                ├── E1
                ├── E2
                └── E3
// Installdir is C1 
```  
Wix# always tries to identify the install dir and mark it with a dedicated ID value. That's why you see that:
```C#
// auto-assign InstallDirDefaultId id for installation 
// directory (the first directory that has multiple items)
static string AutoAssignInstallDirId(Dir[] wDirs, string dirId)
{
    . . . 
    firstDirWithItems.Dirs.Count() == 1
```
However if the logical installdir is one of the special dirs then setting it's ID  to a `INSTALLDIR` will interfere with the "special folder" naming convention of WiX. And WixSharp is very explicit about it by generating an informative warning, which you probably just missed:
```C#
new Dir("%CommonAppDataFolder%",
    new Dir("SubFolder1") 
```
![image](https://user-images.githubusercontent.com/16729806/84649230-7f36e980-af49-11ea-89d2-b79b1492bd3b.png)

=================

As a side note, you probably should never install anything in the _special folder_ root. Instead you should install in the product subfolder:
```C#
new Dir(@"%CommonAppDataFolder%\MyProduct",
    new Dir("SubFolder1") 
```

**Comment by sylvesp** [comment]
Hi Oleg,

Thank you very much for your help. I really appreciate it.
All this make sense.
The warning you mention didn’t escape my attention, just that neither setting
Compiler.AutoGeneration.InstallDirDefaultId = null;

Nor using
var project = new Project(versionedProductName,
                new InstallDirDir(@”%CommonAppDataFolder%”,,

did help, and then I’ve ran out of good guesses.

Also thank you for your warning about not installing in common folders directly. I’ve am familiar with this, and

new Dir(@"%CommonAppDataFolder%\MyProduct", new File()…)



Is already installing in a subfolder “My Product” of the common folder.

One more question if you don’t mind
Now that I am following your advice, all works well, my files are properly installed under



CommonAppData

    └── Company 1

        ├── File 1,

        └── File 2

    └── Company 2

        ├── File 1,

        └── File 2

The only issue I’ve left is that the installer is automatically adding a new Feature named “Complete” to the feature list shown in the installer.
Is it possible to have that not show?

[cid:image002.jpg@01D642EF.B745F300]

Again, appreciate all your help! Have a nice week.
Peter

**Comment by sylvesp** [comment]
Once more - thanks for your help.
I did resolve the problem with the "Complete" feature being added by manually setting the
project.DefaultFeature  to a feature I have in my installer.

**Comment by oleg-shilo** [comment]
Great. Glad it all worked out for you.
