### ISSUE TITLE
Packaging satellite assemblies into the Embedded UI

### ISSUE THREAD

**Issue by theodor-stanbeca** [oleg-shilo/wixsharp#867]
Hi!

I'm currently working on a wixsharp project with a WPF manager UI. For localization purposes, the UI makes use of satellite asemblies for each additional supported language, that are located in folders such as `.\ja-JP`, `.\fr-FR`, etc

However, I cannot manage to add them properly into the `RefAssemblies` field of `project.EmbeddedUI` so that they will be placed in their respective subdirectories in the temp folder when running the MSI.

How can I specify that certain assemblies should be placed in a certain subdirectory?

Thanks!

**Comment by oleg-shilo** [comment]
The problem is caused by the fact that you cannot control how your managed UI is hosted on target system. MSI does it a a very primitive way. It extracts the so called `EmbeddedUI` assembly (the one that implements WixSharp Managed UI), places it in a temp folder and invokes a special entry point.

Thus when MSI runtime places the assembly entry point it does not recognizes the need to support satellite assemblies. Thus it's not much you can do about it.

The only direction you can explore is to pack your satellite assemblies into your primary assembly resources and then use one of them at runtime to do the dynamic localization. But this is a pure WPF task and not a simple one.
