### ISSUE TITLE
Running msiexec from a windows service as LocalSystem account

### ISSUE THREAD

**Issue by konrad-szerwinski** [oleg-shilo/wixsharp#873]
Hello,

I am working on a service that updates software developed by me. 
The service downloads the latest versions of the application and starts the installer as the LocalSystem user. 
For the first time, the application must be installed by the administrator for the service to see what it can update.

The problem occurs when the updater installs the update.

For example, let's call the application "test".

The administrator installs the "test" application version 1.0.0. The updater, after some time, sees that version 1.0.1 has been released.
The updater downloads and installs the update but not in major upgrade mode. The new version does not appear in the control panel, there are two entries in the registry in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`.

From solutions on StackOverflow: 
https://stackoverflow.com/questions/2603969/running-msiexec-from-a-service-local-system-account
the only ones that work are a change of the user running the service but I can't use it.

I have already set `InstallScope` to `perMachine` in script. `GUID` is the same for all versions of "test" application.

Installer form updater is launched by 

```c#
string command = $"/i {installerPath} /l \"{installerDirectory}\\log.txt\" /passive REINSTALL=All REINSTALLMODE=vomus";

ProcessStartInfo installProcessStartInfo = new ProcessStartInfo
{
    FileName = "msiexec",
    UseShellExecute = false,
    RedirectStandardError = false,
    Arguments = command
};

Process msiexec = Process.Start(installProcessStartInfo);
```

When I remove "test" application, files from later version still exists in folder and registry key created by system local exists too. There is one way to delete this entries, you need to manually install the same version as the updater already did and then you can uninstall it from the control panel.

**Comment by oleg-shilo** [comment]
Sorry, my answer will not be the one that you are hoping for.  :)

I do not know what exactly happening in your case but that "installs the update but not in major upgrade mode. " makes me question why you don't use major upgrade. It would solve your problem in the most direct way.

======================


The scenario you are implementing is a typical use case that have been solved I would also so many times by many products that you already know and use. Notepad++, VSCode, Paint.NET, FIleZilla....

None of them resorted to installing the updater service. The all follow a very simple approach:
- At startup check for updates
- If the update is available, ask user if he/she wanst to install a new version (right away or after exit).
- If user agrees start the downloader/updater and exit the current instance of the app.

And there is even a complete deployment build around this use case: **ClickOnce**

**Comment by konrad-szerwinski** [comment]
One of my applications is running as a service all time and there is no way to show message about update. 
The reason why I want to make updater run as the localUser is that users which use my applications could not have permissions to run installation, what is required.

I think I have misspelled. I use major update. "The updater downloads and installs the update but not in major upgrade mode." is how application behaves in this specific situation (when I first install application as administrator, then updater runs installer as LocalSystem user). Next updates performed by updater works almost properly except it does not remove old version installed by other user.

**Comment by oleg-shilo** [comment]
> ...users which use my applications could not have permissions to run installation, what is required.

I see. Then indeed the requirement above makes the difference.

I can only suggest to see if the upgrade removes the old install when executed from the user session, not the service.
Normally _MajorUpgrade_ msi removes the old version without any problems.

You also try to use the _MajorUpgrade_ sample from the distro. It works on its own so you can use it as a benchmark in your scenario. 


>  no way to show message about update.

Yes, for years it was possible for services to interact with the user (by enabling "allow interact with desktop"). It's no longer the case. If you still need to interact with the user then you can use the OS task scheduler to execute an immediate task with the desired privileges and the ability to interact with the user.

**Comment by konrad-szerwinski** [comment]
> I can only suggest to see if the upgrade removes the old install when executed from the user session, not the service.

Upgrade successfully removes old install when it's run from user session.
If I change user that runs service from localSystem to other user with admin privileges, installation runs properly as well (which is not good solution because I will have to change user every time updater gets updated).

> you can use the OS task scheduler to execute an immediate task with the desired privileges and the ability to interact with the user.

Thank you for the hint :D

**Comment by oleg-shilo** [comment]
Then, I am puzzled. I cannot see any logical reason for MSI to be have differently for localSystem and an elevated user. 
If indeed your findings are accurate then it might indicate the bug in the MSI implementation. Doesn't give you much hope :(

**Comment by konrad-szerwinski** [comment]
Sorry for wasting your time... there is something strange with my os... I tried this on virtual machine and it works properly... on my friend's computer and works too... It's time to do fresh os installation 😢

**Comment by oleg-shilo** [comment]
It is in fact the preferred outcome :)

**Comment by jzabroski** [comment]
@konrad-szerwinski There are multiple things problematic with your approach.

First, I'm not joking when I say, "Don't use ClickOnce."  I would suggest Squirrel in the past (even Microsoft Teams was using it), but it has become semi-abandoned.  A new framework, [snapx](https://github.com/fintermobilityas/snapx), has emerged.

Second, LocalSystem uses a unique AppData folder, so it's easy to create a Rube Goldberg machine with your current approach.  If it "works on my machine" but not others, this could be why.

Third, ClickOnce's check for updates mechanism leaks request counts, which eventually causes ClickOnce applications to stop checking for updates.  See my description and workaround here: https://github.com/jzabroski/Home/blob/8c2896377658a2f5b51674924a15549c9f9e5c72/CSharp/ClickOnce/README.md

**Comment by JesperTreetop** [comment]
I am not a WixSharp user although I have heard very good things about it, but for anyone googling this in the future: I ran into the exact same issue that @konrad-szerwinski encountered.

`msiexec` started from a service running as LocalSystem has a tendency to get stuck. In my case, the service started an intermediate update program (since the service was the program to be updated and it would otherwise be in use) which started `msiexec` and it got stuck. I also tried to create a scheduled task running as LocalSystem but no dice, I saw the same behavior.

I'm guessing MSI running as LocalSystem in a background session without desktop (which happens both for non-interactive scheduled tasks and for services) runs into some sort of deadlock or requires access to the UI session.

My workaround for this was to switch the installer from MSI to Inno Setup, which works as advertised even in this scenario.

**Comment by jzabroski** [comment]
The lack of a desktop session makes the most sense to me.

I deal with excel users who have excel running direct queries against a database, and when their screen locks, the session is unavailable, and that causes the thread that draws the query results to the screen to livelock because there is no session available for the thread to draw on.

However, I think you misunderstood the virtualization issue. You mentioned that another program launches the msiexec for you.  If the Windows service is 32 bit, it will use the system profile, which I believe has a separate location under virtualization.

**Comment by jzabroski** [comment]
> I wrote both the service and the other program, an "update trampoline".

...That's what Squirrel does. It builds an Update.exe and a YourApp.exe.

I mentioned snapx above as well, as a more modern successor to Squirrel.  But Squirrel is what Microsoft Teams uses.

**Comment by JesperTreetop** [comment]
Yep! And the reason I don't use Squirrel is because I'm updating a Windows service on a machine I can't assume anyone watches. If someone updates an interactive desktop application and it breaks, you can trust that they will see that and be on the case. But for doing background service updates, it's more involved, and I think most automatic update frameworks don't even handle migrating Windows services well if at all.

As it stands, I have a throughline for progress reporting for the state of the upgrade to flow back to the mentioned external application (which can be a management console halfway around the world). For example, it currently checks application-specific metrics before and after, and is able to decide "this was probably a bad idea" and roll back. Theoretically, the new version could do that, but if the new version is borked, who knows if that part of it works.

Either way, this issue is closed so I just wanted to add some additional eyewitness reports for the next unhappy soul trying to google this issue.
