### ISSUE TITLE
Using System.Resources.Extensions makes the msi crash on startup

### ISSUE THREAD

**Issue by Gimly** [oleg-shilo/wixsharp#888]
We have a non managed project with a WPF UI.

To be able to build with `dotnet build` when we use non-string resources, we need to add the NuGet package `System.Resources.Extensions` (see https://github.com/dotnet/msbuild/issues/4704).

Unfortunately, doing so makes the MSI crash on startup with a "FileNotFoundException" because it seems that it's missing some dll. I've tried to do `project.DefaultRefAssemblies.Add()` for all dlls defined in the NuGet package (and the dependency packages), but it didn't help.

For now I've circumvented the issue by removing the non string resource and use the images as "Build Action" Resource, but it makes using them in XAML a bit more complex.

**Comment by oleg-shilo** [comment]
I understand your challenge and indeed it's not easy.

Most likely the CLR is failing at runtime to load some of the assemblies because it is missing or not of the right version. Using "project.DefaultRefAssemblies" is the right way to address this issue but sometimes it's close to impossible to guess these assemblies right. Though in case of the version mismatch you may also define your custom assembly probing to be used in production not only as a troubleshooting technique.

My recommendation debug and see what exactly CLR is failing to load so you will need define your own assembly probing and 
debug it when it triggers. This is the pseudo-code:


```C#
static void assembly_entry_method()
{
    AppODmain.Current.ResolveAssembly += (s,e)=>
    {
        var missing_assembly_name = e.Name;
        // put breakpoint here
        return null;
    };
    assembly_UI_loading_method();
}

static void assembly_UI_loading_method()
{
    . . .
}
```
