### ISSUE TITLE
Open installed application without Admin permissions

### ISSUE THREAD

**Issue by bdrachinsky** [oleg-shilo/wixsharp#889]
Hi @oleg-shilo , is there a way to open my installed application without admin permissions or always set it to be opened as admin

Every time I started an app I see that 
![image](https://user-images.githubusercontent.com/13419649/88456626-b6bd7d80-ce87-11ea-838f-6edc604b6118.png)

I tried to set both
  project.InstallScope and project.InstallPrivileges but nothing works for me. Do I need to get digital certificate for my app and setup this one? If I do -- could you explain how can I do this?

**Comment by oleg-shilo** [comment]
It is not much related to the installation of the app but rather to the app itself. If you embed into your app the manifest file that requires elevation. It will always start with the UAC prompt.

Though I personally prefer an approach where the app analyzes the excustion context decided how it should be started (elevated or not). But... it is a separate story.

There is a chance that you are forcing your app to start elevated because the way it is installed. I cannot really answer your question but I can suggest that you look at any of the WixSharp samples (e.g. InstallFiles). All of the are designed to start the application unelevated. This could be a good starting point for your investigation.
