### ISSUE TITLE
Property SetupEventArgs.IsModifying has other behavior than method Extensions.IsModifying()

### ISSUE THREAD

**Issue by hawkunsh** [oleg-shilo/wixsharp#9]
I noticed that `SetupEventArgs.IsModifying` uses other logic than `Extensions.IsModifying()`, thus returning different values, at least in some install scenarios.

        public bool IsModifying { get { return IsInstalled && !Data["REINSTALL"].SameAs("ALL", ignoreCase: true); } }

vs

        static public bool IsModifying(this Session session)
        {
            return session.IsInstalled() && !session.IsUninstalling();
        }

They should be equivalent (maybe a good time to implement the **DRY** pattern), or am I missing something?

**Comment by oleg-shilo** [comment]
Thank you. Indeed it is a defect. Has been fixed in the codebase and will be available with the very next release. 

As for **DRY**, I am not convinced it is not exactly the case. :)
Session extension methods and SetupEventArs are completely different creatures and they work with very different runtime objects. One with a short living property bag Session (belongs to WiX) to and another one with a custom persistent dictionary (belongs to Wix#) . While they do share part of the API, their implementing classes Extensions and SetupEventArgs have very different responsibilities. 

Implementing an external abstraction layer would satisfy **DRY** (and possible this is what eventually is going to happen) but considering the amount of overlap and the current complexity of the implementation I think it would be rather an **over-optimization** and also violation of **YAGNI**. :)

But thank you again. I missed it.

**Comment by hawkunsh** [comment]
Thanks.

As for **DRY**, I hear you and understand your reasoning. Would probably have done the same. But perhaps one could argue that the fact that this bug was missed is proof that **DRY** would have been a good choice  ;)
