### ISSUE TITLE
Add an extra config file for an admin install

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#907]
we would like to install our product as an "silent admin install". But here we would need an extra config file to configure the product. So an "admin" would run the msi as "msiexec /a xyz.msi extra.config"; could this been done somehow ?

best

Carsten

**Comment by Torchok19081986** [comment]
Hi Carsten, 
1. there is sample of Admininstall in Sample Folder in Wix#, maybe this can help you. 
2. msiexec /a ist install of Administration Installation Point msi. AFAIK is install msi from AIP , installation msi should be "created" as AIP.  Good Example is Adobe Reader msi. There is always AIP msi installer . Browse this output msi with orca from Net Framework. Maybe this can help you. 
load current exe from ftp://ftp.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/
in version down there at ...43 is msp. Extract exe and apply msp to it.
 Substep 1: 
@echo off

rem -------------------------------------------------------
rem
rem Extract contents of AcroRdr*.exe go C:\AdobeFiles
rem
rem see http://www.klaus-hartnegg.de/gpo/msi_acroread.html
rem
rem -------------------------------------------------------

if exist c:\AdobeFiles\nul goto exists

set rc=
for %%i in (AcroRdr*.exe) do set rc=%%i
if "%rc%."=="." goto notfound
set dupe=
for %%i in (AcroRdr*.exe) do if not "%%i"=="%rc%" set dupe=1
if not %dupe%.==. goto dupe

echo Extracting %rc% to C:\AdobeFiles ...
%rc% -nos_oc:\AdobeFiles -nos_ne
echo ready
pause
start "" explorer /e,C:\AdobeFiles
goto end

:exists
echo Error: Directory C:\AdobeFiles already exists
goto error

:notfound
echo Error: File AcroRdr*.exe not found
goto error

:dupe
echo Error: More than one file AdbeRdr*.exe found
goto error

:error
pause

:end

Substep 2: 

@echo off

rem ---------------------------------------------------------------------------
rem
rem Description:
rem    Creates slipstreamed updated AIP
rem    by applying a patch from a MSP-file either to a 
rem    MSI-file or to an administrative installation point (AIP).
rem
rem Use:
rem    1. create new directory
rem    2. copy AIP or MSI-file there
rem    3. copy MSP-file there as well
rem    4. copy this batch there as well and execute it
rem 
rem Notes:
rem - must be run with admin rights (if patching Adobe Reader 10)
rem - should be run on PC where Adobe Reader was never installed
rem - if patching MSI-file will create directory AIP and put all output there
rem - installation does not need just the new MSI-file. Copy the whole AIP path!
rem - resulting MSI-file should be renamed to reflect new version number
rem
rem For more info and newer version of this:
rem http://www.klaus-hartnegg.de/gpo/msp.html
rem
rem ---------------------------------------------------------------------------

rem Verify that we have admin rights
"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system" >nul 2>&1
if errorlevel 1 echo ** WARNING: this may require admin-rights

set error=

rem Search MSI- and MSP-file
call :search msi
set msi=%rc%
if not %error%.==. goto error
call :search msp
set msp=%rc%
if not %error%.==. goto error

echo.
echo ------------------------------------------------
echo Will patch MSI-file
echo    %msi%
echo.
echo with patch from MSP-file
echo    %msp%
echo ------------------------------------------------


rem echo Do you want me to apply the patch to a MSI-file,
rem echo or to an Administrative Installation Point (AIP)?
rem echo.
rem echo Note: If you select MSI, I will extract the MSI-file
rem echo to a new AIP, otherwise I will use the existing AIP.
rem echo.
rem echo Please enter MSI, AIP, or Q to quit.
rem set /p type="Reply: "
rem echo.

if exist "Data1.cab" (
   set type=msi
) else (
   set type=aip
)

if %type%.==msi. goto doMSI
if %type%.==MSI. goto doMSI
if %type%.==aip. goto doAIP
if %type%.==AIP. goto doAIP
if %type%.==q. goto end
if %type%.==Q. goto end
echo ** ERROR: unknown reply %type%
goto error


:doMSI
if exist AIP\NUL goto dupeaip
mkdir AIP
cd AIP
set aip=%CD%
echo ** Extracting MSI-file to AIP %aip%
C:\Windows\System32\msiexec.exe /qb /a "%msi%" TARGETDIR="%aip%"
if errorlevel 1 goto err1
echo ** Searching extracted MSI-file in AIP
call :search msi
set msi=%rc%
if not %error%.==. goto error
echo ** Found MSI-file in AIP: %msi%

:doAIP
echo ** Applying patch from MSP-file
C:\Windows\System32\msiexec.exe /qb /a "%msi%" /p "%msp%"
if errorlevel 2 goto err2
echo ** SUCCESS 
pause
start explorer /e,.

goto end


:search
set rc=
for %%i in (*.%1) do set rc=%%i
if "%rc%."=="." goto no%1
set dupe=
for %%i in (*.%1) do if not "%%i"=="%rc%" set dupe=1
if not %dupe%.==. goto dupe%1
set dupe=
set rc=%CD%\%rc%
if not exist "%rc%" goto whoops
goto:eof

:nomsi
echo ** ERROR: no MSI-file found
set error=1
goto end

:dupemsi
echo ** ERROR: more than one MSI-file found
set error=1
goto end

:nomsp
echo ** ERROR: no MSP-file found
set error=1
goto end

:dupemsp
echo ** ERROR: more than one MSP-file found
set error=1
goto end

:whoops
echo ** UNKNOWN ERROR
set error=1
goto end

:dupeaip
echo ** ERROR: directory AIP already exists
goto error

:err1
echo ** ERROR: extraction of MSI-file to AIP failed
goto error

:err2
echo ** ERROR: applying patch failed
goto error

:error
pause
:end

with this 2 batches. can you extract msi from exe and apply msp on it. 

3. What should extra.config content have? Do you need some additional parameter or ? Elevated Managed Action maybe can help you.

**Comment by hcarsten** [comment]
Oleg,
thx for the reply. I saw the sample you your extra give me a good direction.
The application to be installed is a system where normally we run basic configuration wizard on the first run. Basically we would like to do is using the config file to run the configuration unattended. There is a use case where a rollout should be done for about 10K students during the current covid crisis.

Anyway technically I would need a way to access the command line arguments to the installer, so in the above script something like: 

> C:\Windows\System32\msiexec.exe /qb /a "%msi%" TARGETDIR="%aip%" CUSTOM_CFG=xyz.config

So I can extract the CUSTOM_CFG value within the (maybe elevated) Managed Action ?

best

Carsten

**Comment by oleg-shilo** [comment]
The commamnd line you provided sets two MSI properties `TARGETDIR` and `CUSTOM_CFG` 

While the first is processed for you by MSI runtime, the second one is for you to consume.
Thus you can read it from any of custom actions.

```C#
project.DefaultDeferredProperties += ",CUSTOM_CFG";

project.AfterInstall += e
{
    if (e.IsInstalling)
    {
        string config = e.Session.Property("CUSTOM_CFG");
        . . . 
    }

};
```
