### ISSUE TITLE
Can we build installers for MVC 5 using Wixsharp?

### ISSUE THREAD

**Issue by bob53050** [oleg-shilo/wixsharp#91]
Hello,

If this is possible, are there examples to review and/or documentation for this?

Thanks,

Bob

**Comment by oleg-shilo** [comment]
Hi Bob,

Wix# does not distinguish between types of the Web applications or the frameworks that were used to develop them (e.g. WebForm or MVC). 

You can have a look at 'IIS_ASP_NETApp' sample to get the idea about what is involved in authoring Web application setup, but otherwise it is not a Wix# question (nor even MSI one).

When you know exactly what you need to distribute with your MVC 5 application then you can start planing and developing your setup. But before that none of the deployment framework (Wix#/WiX/MSI) can be used effectively.

**Comment by bob53050** [comment]
Thanks Oleg
