### ISSUE TITLE
Trouble on Installations on Windows 10 20H2

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#972]
We are getting bug reports from Users installing on Windows 10 20H2. This problem is relating to writing to the registry (SetValue) which fails with a "Permission not allowed" error. 
The same code runs under older versions. 

```
private static void Project_AfterInstall(SetupEventArgs e)
{
    RegistryKey localMaschine64View = RegistryKey.OpenBaseKey(
        Microsoft.Win32.RegistryHive.LocalMachine, RegistryView.Registry64);

    ...
    RegistryKey chromeKey = localMaschine64View.OpenSubKey(@"SOFTWARE\vendor\app", true);
    RegistryKey hKey = chromeKey.CreateSubKey(@"somekey", true);

    // this line fails
    Registry.SetValue(LocalMaschine + @"SOFTWARE\vendor\app\somekey", "", "12345");
    ...
}

```

**Comment by onefreddy** [comment]
This is managed code. I think Oleg will not like your message, because it does not apply to the installer. You can execute this code from any program

**Comment by hcarsten** [comment]
right the question is how W10, 20H2 is effecting the Setup. Thus as fare as I know Project_AfterInstall should be called elevated. So this might be the problem (and so the issue becomes a setup issue again, and maybe Olegs like me again :) ).
Or the issue is related to something that prevents the elevated user to accessing the registry ?

**Comment by oleg-shilo** [comment]
> The same code runs under older versions.

I have just rebuild and republished the last (18 days ago) release that targets now lower version of  targetframework - v4.5.1.
This is done due to the problems reported against upgrated (4.6.1) build.

To be honest I doubt 4.5.1 vs 4.6.1 can cause the permissions problem. But still, since it was the most significant change since the last release I suggest you try the latest release Wix# v1.16.2.0

If it does not help, try to  verify that `Project_AfterInstall` indeed runs elevated. Just place a messagebox in the afterinstall handler:
```C#
bool isAdmin = new WindowsPrincipal(WindowsIdentity.GetCurrent())
                             .IsInRole(WindowsBuiltInRole.Administrator);

MessageBox.Show($"IsAdmin: {isAdmin}");
```
It is important to verify as the permission exception can be throw either because you are not elevated or the operation is not allowed even for elevated user. 

>and maybe Olegs like me again

LOL 
I do like you all
