### ISSUE TITLE
RegistryKey "Software\WixSharp\Used" being added to every component

### ISSUE THREAD

**Issue by DanHibbert** [oleg-shilo/wixsharp#98]
Hi,
   Can you think of any reason why the RegistryKey below is being added to every component?

```
<RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
   <RegistryValue Value="0" Type="string" KeyPath="yes" />
</RegistryKey>
```

Thanks Dan

**Comment by oleg-shilo** [comment]
It is required for auto-compliance with various ICE tests. As for me these tests sometimes plain ridiculous but if they are not satisfied your msi cannot be built. Thus you have three options to deal with ICE:
* Disable it completely via `Compiler.LightOptions`. 
* Let Wix# to inject regkeys to the components.
* Disable Wix# auto injection and insert the reg keys manually. 

You can disable the auto-injection via `AutoElements.DisableAutoUserProfileRegistry = true;`.

And this is what `DisableAutoUserProfileRegistry` doc says:
```
Disables automatic insertion of user profile registry elements. Required for: AllInOne,
ConditionalInstallation, CustomAttributes, ReleaseFolder, Shortcuts, Shortcuts (advertised), 
Shortcuts-2, WildCardFiles samples. 
Can also be managed by disabling ICE validation via Light.exe command line arguments.
```

**Comment by eagleoriginal** [comment]
Oleg-shilo.
Please give a link for explaining why keypath="yes" on registry 
HKCU key="Software\WixSharp\Used" is normal.
Is keypath for same path is not not wrong behaviour for component with diferent Guid?

**Comment by oleg-shilo** [comment]
Please read my post "oleg-shilo commented on Jun 29" above. 

----

Sometimes MSI/WiX forces developers to insert otherwise not required (dummy) elements in the  WXS document. WixSahrp can assist by doing this automatically. If you feel that the automatic insertion is inadequate then you can disable this feature and do it manually:
```C#
AutoElements.DisableAutoUserProfileRegistry = true;
AutoElements.DisableAutoKeyPath = true;
```
As opposite to WiX and MSI, WixSharp doesn't force you. :)

This is what WixSharp says about keypath auto insertion:

![image](https://user-images.githubusercontent.com/16729806/33508004-0da910ea-d74c-11e7-85cd-268d1cd306a1.png)

>Is keypath for same path is not not wrong behaviour...

It's hard for me to comment on this one. I know that after setting the keypath the ICE validation passes OK. And if keypath is not set then ICE fails. Thus it is not "wrong" from ICE point of view. But explaining ICE validation internals and reasoning is really beyond of WixSharp scope.

**Comment by eagleoriginal** [comment]
Thanks Oleg. 
I am stuck in my initially post with "FileShortcut()", witch make this stub regkey in component belogned to this file, on output *.wix file. like this:
```
            <Component Id="Component.LearnSharpWix.exe" Guid="4855f305-9aa5-4222-920c-a4d4c03a7be8" Win64="yes">
              <Condition>MyProp1="MyValue1"</Condition>
              <File Id="LearnSharpWix.exe" Source="Bin\Debug\LearnSharpWix.exe">
                <Shortcut Id="Shortcut.LearnSharpWix.exe.LearnSharpWix.exe_" WorkingDirectory="INSTALLDIR" Directory="INSTALLDIR" Name="LearnSharpWix.exe.lnk" />
                <Shortcut Id="Shortcut.LearnSharpWix.exe.LearnSharpWix.exe.1" WorkingDirectory="INSTALLDIR" Directory="DesktopFolder.MyApp3" Name="LearnSharpWix.exe.lnk" />
              </File>

              **<RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
                <RegistryValue Value="0" Type="string" KeyPath="yes" />
              </RegistryKey>**
            </Component>
```
After some experiments i figured that removing this keypath("Software\WixSharp\Used") dont affect deleting files on deinstall, or restore product.
