### ISSUE TITLE
Working with embedded WPF UI and MSI 

### ISSUE THREAD

**Issue by NickeManarin** [oleg-shilo/wixsharp#99]
Looking at the examples found inside the folder _Samples_, I can see a project that uses WPF:

- Samples\External_UI\WpfSetup

While compiling that project, I noticed that it creates a **.exe** instead of a **.msi** (external).

Is it possible/easy to create an installer with WPF UI inserted into the MSI dialog sequence?

I can see examples with custom UI (that create MSI files) are all using WinForms, deriving from a ManagedForm class.

**Comment by oleg-shilo** [comment]
No, there is no WPF favor of the the MSI dialog sequence. It's just not implemented.

Yes, you can have msi setup that uses WPF UI. Though you need to have a look at the different sample. You need `Wix# Samples\Custom_UI\EmbeddedUI_WPF\SampleEmbeddedUI.cs`. It implements EmbeddedUI use-case (the same as WinForms). 

And the sample you were referring to is for the external msi host (exe).

**Comment by NickeManarin** [comment]
I'm a little bit lost. Could you build an example project using that EmbeddedUI sample? 

The sample alone, creates a dll (and copies this dll: `Microsoft.Deployment.WindowsInstaller`) to the build folder.

**Comment by oleg-shilo** [comment]
Sorry the objective of the sample was to build the assembly - dll that implements WPF UI. The other practical identical WinForm sample  shows how to set your MSI to use a specific UI assembly:
```C#
 project.EmbeddedUI = new EmbeddedAssembly(<location_of_the_UI_assembly>);
```
However because of the sample is indeed incomplete/confusing I have updated it and now you can grab it from [GitHub](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Custom_UI/EmbeddedUI_WPF) or just add to your build script that code line above.

**Comment by NickeManarin** [comment]
Thank you!
