### ISSUE TITLE
IgnoreWildCardEmptyDirectories with 1.17.0 causes Wxs generation to never finish with multiple top-level dirs

### ISSUE THREAD

**Issue by wrouesnel** [oleg-shilo/wixsharp#995]
With a project like:
```csharp
Compiler.Autogeneration.IgnoreWildcardEmptyDirectories = true;

project = new Project("myproduct",
   new Dir("%Desktop%"),
   new Dir("%ProgramFiles%");
```

I have found that the build step to generate Wxs code loops endlessly in the Project.ResolveWildcards. Setting `IgnoreWildcardEmptyDirectories` to `false` fixes the problem, but this definitely seems like bad bahavior.

Note: it might eventually finish, but I had a CPU pegged for over an hour with no sign of progress.

**Comment by oleg-shilo** [comment]
Hi Will, 

it does sound like a bug .
Will have a look at it.

BTW, gritting from Melbourne 😃

**Comment by oleg-shilo** [comment]
Indeed it was a defect. The problem was caused by the fact that the "remove empty dirs" algorithm is was trying to purge the AllDir collection until no empty dirs left and because it mistakenly was not testing root dirs the "break" condition was never met => infinite loop.

Fixed. Will be available in the very next release.
