### ISSUE TITLE
Side-effects of setting Compiler.AllowNonRtfLicense = true

### ISSUE THREAD

**Issue by Krzmbrzl** [oleg-shilo/wixsharp#997]
So we want to use a plain text license file for our installer but when specifying that, we get the following exception:
```
System.ApplicationException: License file must have 'rtf' file extension. Specify 'Compiler.AllowNonRtfLicense=true' to overcome this constraint.
   at WixSharp.Compiler.GenerateWixProj(Project project)
   at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
   at WixSharp.Compiler.Build(Project project, String path, OutputType type)
   at WixSharp.Compiler.Build(Project project, OutputType type)
   at WixSharp.LocalizationExtensions.BuildMultilanguageMsi(Project project, String path)
```

The exception already states how to fix this but given that this restriction exists by default, I was wondering what the implications of setting `Compiler.AllowNonRtfLicense = true` are. As I could not find that in the docs I wanted to ask here if someone could give me some ideas?

**Comment by oleg-shilo** [comment]
It is an interesting one. :)
WiX/MSI implementation of the native UI has a constrain: the licences file has to be an rtf file. Otherwise the licences dialog shows the dialog with empty text area.

WixSharp is the tool that checks this and warns the user "you should not do this". However since WiX oficially does not publish this constrain WixSharp has no business unconditionally restrict non -rtf licence files so it uses the condition `Compiler.AllowNonRtfLicense`.

Thus the implications: the lucence doc will not be displayed even though MSI/WiX think it's OK.

If indeed non rtf licence is a must then consider using managed UI. It's a WinForm UI so you have full freedom of rendering any document.

**Comment by Krzmbrzl** [comment]
Alright thanks for the info! :)
